# -*- coding: utf-8 -*-

cards_2007_t1 = [
    {
        "id": "2007-T1-01",
        "year": 2007,
        "text": "Text 1",
        "word": "examine (check)",
        "category": "核心词汇",
        "noteTag": "★ 同义替换 · check",
        "def": "审查、检验",
        "sentence": "If you were to <mark>examine</mark> the birth certificates of every soccer player in 2006's World Cup tournament, you would most likely find a noteworthy quirk.",
        "sentencePlain": "If you were to examine the birth certificates of every soccer player in 2006's World Cup tournament, you would most likely find a noteworthy quirk.",
        "translation": "如果你审查2006年世界杯锦标赛上每一位足球运动员的出生证明，你很可能会发现一个值得注意的怪现象。"
    },
    {
        "id": "2007-T1-02",
        "year": 2007,
        "text": "Text 1",
        "word": "tournament",
        "category": "核心词汇",
        "noteTag": "★ 高频体育与选拔语境",
        "def": "锦标赛、联赛",
        "sentence": "If you were to examine the birth certificates of every soccer player in 2006's World Cup <mark>tournament</mark>, you would most likely find a noteworthy quirk.",
        "sentencePlain": "If you were to examine the birth certificates of every soccer player in 2006's World Cup tournament, you would most likely find a noteworthy quirk.",
        "translation": "如果你审查2006年世界杯锦标赛上每一位足球运动员的出生证明，你很可能会发现一个值得注意的怪现象。"
    },
    {
        "id": "2007-T1-03",
        "year": 2007,
        "text": "Text 1",
        "word": "noteworthy",
        "category": "核心词汇",
        "noteTag": "★ 构词：note + worthy",
        "def": "引人注目的、显著的",
        "sentence": "...you would most likely find a <mark>noteworthy</mark> quirk: elite soccer players are more likely to have been born in the earlier months of the year.",
        "sentencePlain": "...you would most likely find a noteworthy quirk: elite soccer players are more likely to have been born in the earlier months of the year.",
        "translation": "……你很可能会发现一个引人注目的怪现象：顶级足球运动员更有可能出生在每年的前几个月。"
    },
    {
        "id": "2007-T1-04",
        "year": 2007,
        "text": "Text 1",
        "word": "quirk",
        "category": "核心词汇",
        "noteTag": "★ 核心难词 · 意料之外的巧合/怪事",
        "def": "怪事、离奇现象、怪癖",
        "sentence": "...you would most likely find a noteworthy <mark>quirk</mark>: elite soccer players are more likely to have been born in the earlier months of the year...",
        "sentencePlain": "...you would most likely find a noteworthy quirk: elite soccer players are more likely to have been born in the earlier months of the year...",
        "translation": "……你很可能会发现一个引人注目的怪现象：顶级足球运动员更有可能出生在每年的前几个月……"
    },
    {
        "id": "2007-T1-05",
        "year": 2007,
        "text": "Text 1",
        "word": "dubbed",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 被冠以……称号 (非配音)",
        "def": "被称为……、被冠以……绰号",
        "sentence": "...elite soccer players are more likely to have been born in the earlier months of the year, a phenomenon <mark>dubbed</mark> the relative age effect.",
        "sentencePlain": "...elite soccer players are more likely to have been born in the earlier months of the year, a phenomenon dubbed the relative age effect.",
        "translation": "……顶级足球运动员更有可能出生在每年的前几个月，这一现象被称为“相对年龄效应”。"
    },
    {
        "id": "2007-T1-06",
        "year": 2007,
        "text": "Text 1",
        "word": "feed",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 滋养/助长自我循环",
        "def": "滋养、助长、流入",
        "sentence": "This initial advantage continues to <mark>feed</mark> upon itself, creating a wider gap between older and younger players.",
        "sentencePlain": "This initial advantage continues to feed upon itself, creating a wider gap between older and younger players.",
        "translation": "这种最初的优势不断自我滋养（助长），在年长和年幼选手之间拉开了更大的差距。"
    },
    {
        "id": "2007-T1-07",
        "year": 2007,
        "text": "Text 1",
        "word": "pronounced",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 显著的/明显的 (非发音)",
        "def": "显著的、明显的",
        "sentence": "The difference was most <mark>pronounced</mark> among elite soccer leagues and hockey teams.",
        "sentencePlain": "The difference was most pronounced among elite soccer leagues and hockey teams.",
        "translation": "这种差异在顶级足球联赛和曲棍球队中最为显著。"
    },
    {
        "id": "2007-T1-08",
        "year": 2007,
        "text": "Text 1",
        "word": "account for",
        "category": "固定短语",
        "noteTag": "★ 考研高频因果搭配 · 对……做出解释",
        "def": "对……做出解释；占……比例",
        "sentence": "Almost none of the difference could be <mark>accounted for</mark> by inborn talent.",
        "sentencePlain": "Almost none of the difference could be accounted for by inborn talent.",
        "translation": "这种差异几乎没有任何一部分能归因于（用以解释为）先天秉赋。"
    },
    {
        "id": "2007-T1-09",
        "year": 2007,
        "text": "Text 1",
        "word": "confer",
        "category": "熟词生义",
        "noteTag": "★ 核心动词 · 赋予优势 (confer sth on sb)",
        "def": "赋予、授予、协商",
        "sentence": "An extra few months of physical maturity might <mark>confer</mark> a persistent benefit on young athletes.",
        "sentencePlain": "An extra few months of physical maturity might confer a persistent benefit on young athletes.",
        "translation": "几个月额外的身体成熟度可能会赋予年轻运动员一种持续的益处。"
    },
    {
        "id": "2007-T1-10",
        "year": 2007,
        "text": "Text 1",
        "word": "astrological sign",
        "category": "核心词汇",
        "noteTag": "★ 考点对比 · 星座巧合",
        "def": "星座、黄道十二宫",
        "sentence": "It wasn't their <mark>astrological sign</mark> that made the difference, but the arbitrary cutoff dates for youth sports leagues.",
        "sentencePlain": "It wasn't their astrological sign that made the difference, but the arbitrary cutoff dates for youth sports leagues.",
        "translation": "产生差异的并不是他们的星座，而是青年体育联赛人为设定的选拔截止日期。"
    },
    {
        "id": "2007-T1-11",
        "year": 2007,
        "text": "Text 1",
        "word": "stamina",
        "category": "核心词汇",
        "noteTag": "★ 核心生理与心理素质词",
        "def": "耐力、持久力、毅力",
        "sentence": "Coaches mistake physical maturity—speed, strength, and <mark>stamina</mark>—for innate athletic brilliance.",
        "sentencePlain": "Coaches mistake physical maturity—speed, strength, and stamina—for innate athletic brilliance.",
        "translation": "教练们把身体的成熟度——速度、力量和耐力——误认为是先天的运动才华。"
    },
    {
        "id": "2007-T1-12",
        "year": 2007,
        "text": "Text 1",
        "word": "engineering",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 人为操纵/规划设计",
        "def": "工程设计；人为操纵策划",
        "sentence": "The distribution is not a law of nature, but an artifact of institutional <mark>engineering</mark>.",
        "sentencePlain": "The distribution is not a law of nature, but an artifact of institutional engineering.",
        "translation": "这种分布不是自然法则，而是体制人为策划操纵的产物。"
    },
    {
        "id": "2007-T1-13",
        "year": 2007,
        "text": "Text 1",
        "word": "switch",
        "category": "核心词汇",
        "noteTag": "★ 动词及物/不及物 · 转变/调换",
        "def": "转变、调换、切换",
        "sentence": "When sports leagues <mark>switch</mark> their eligibility cutoff dates, the birth-month distribution shifts immediately.",
        "sentencePlain": "When sports leagues switch their eligibility cutoff dates, the birth-month distribution shifts immediately.",
        "translation": "当体育联赛调换其资格审查截止日期时，出生月份的分布格局便随即发生了转变。"
    },
    {
        "id": "2007-T1-14",
        "year": 2007,
        "text": "Text 1",
        "word": "conceive",
        "category": "核心词汇",
        "noteTag": "★ 构词：con + ceive(抓取) · 怀胎/设想",
        "def": "设想、构思；怀胎、受孕",
        "sentence": "Historically, it was believed that children who were <mark>conceived</mark> in the springtime were stronger.",
        "sentencePlain": "Historically, it was believed that children who were conceived in the springtime were stronger.",
        "translation": "在历史上，人们曾认为在春季受孕的孩子体魄更加强健。"
    },
    {
        "id": "2007-T1-15",
        "year": 2007,
        "text": "Text 1",
        "word": "springtime",
        "category": "核心词汇",
        "noteTag": "★ 语境指代受孕时节",
        "def": "春天、春季",
        "sentence": "Conception in the <mark>springtime</mark> had nothing to do with superior athletic genetics.",
        "sentencePlain": "Conception in the springtime had nothing to do with superior athletic genetics.",
        "translation": "在春季受孕与优异的运动遗传基因毫无干系。"
    },
    {
        "id": "2007-T1-16",
        "year": 2007,
        "text": "Text 1",
        "word": "experiment",
        "category": "核心词汇",
        "noteTag": "★ 核心学术研究词汇",
        "def": "实验、试验",
        "sentence": "Anders Ericsson conducted a rigorous laboratory <mark>experiment</mark> on memory and deliberate practice.",
        "sentencePlain": "Anders Ericsson conducted a rigorous laboratory experiment on memory and deliberate practice.",
        "translation": "安德斯·埃里克森就记忆力与刻意练习进行了一项严谨的实验室实验。"
    },
    {
        "id": "2007-T1-17",
        "year": 2007,
        "text": "Text 1",
        "word": "involved memory",
        "category": "固定短语",
        "noteTag": "★ 认知心理学术语 · 复杂深度记忆机制",
        "def": "复杂的记忆机制、深度参与记忆",
        "sentence": "Deliberate practice requires highly <mark>involved memory</mark> retrieval and continuous cognitive engagement.",
        "sentencePlain": "Deliberate practice requires highly involved memory retrieval and continuous cognitive engagement.",
        "translation": "刻意练习需要高度复杂的记忆提取与持续的认知投入。"
    },
    {
        "id": "2007-T1-18",
        "year": 2007,
        "text": "Text 1",
        "word": "span",
        "category": "核心词汇",
        "noteTag": "★ 考研高频词 · 跨度/范围",
        "def": "跨度、持续时间",
        "sentence": "Their digit-span performance expanded from seven digits to more than eighty over the <mark>span</mark> of several years.",
        "sentencePlain": "Their digit-span performance expanded from seven digits to more than eighty over the span of several years.",
        "translation": "在数年的时间跨度内，他们的数字记忆广度成绩从7位扩增到了80多位。"
    },
    {
        "id": "2007-T1-19",
        "year": 2007,
        "text": "Text 1",
        "word": "coupled with",
        "category": "固定短语",
        "noteTag": "★ 等价于 combined with / together with",
        "def": "加上、与……相结合",
        "sentence": "Rigorous discipline, <mark>coupled with</mark> expert coaching, was the true determinant of success.",
        "sentencePlain": "Rigorous discipline, coupled with expert coaching, was the true determinant of success.",
        "translation": "严谨的自律加上专家的悉心指导，才是成功的真正决定因素。"
    },
    {
        "id": "2007-T1-20",
        "year": 2007,
        "text": "Text 1",
        "word": "conclude",
        "category": "核心词汇",
        "noteTag": "★ 学术论文核心论断词",
        "def": "得出结论、推断出",
        "sentence": "Ericsson <mark>concluded</mark> that deliberate practice, not inherent genius, sets world-class performers apart.",
        "sentencePlain": "Ericsson concluded that deliberate practice, not inherent genius, sets world-class performers apart.",
        "translation": "埃里克森得出结论：是将世界级大师与常人区分开来的刻意练习，而非与生俱来的天赋。"
    },
    {
        "id": "2007-T1-21",
        "year": 2007,
        "text": "Text 1",
        "word": "repeat",
        "category": "核心词汇",
        "noteTag": "★ 刻意练习本质",
        "def": "重复、反复进行",
        "sentence": "You must <mark>repeat</mark> the task with focused attention, correcting errors on every attempt.",
        "sentencePlain": "You must repeat the task with focused attention, correcting errors on every attempt.",
        "translation": "你必须全神贯注地反复练习，在每一次尝试中纠正错误。"
    },
    {
        "id": "2007-T1-22",
        "year": 2007,
        "text": "Text 1",
        "word": "in other words",
        "category": "固定短语",
        "noteTag": "★ 逻辑转述标志短语",
        "def": "换句话说、换言之",
        "sentence": "<mark>In other words</mark>, practice trumped whatever natural talent they might possess.",
        "sentencePlain": "In other words, practice trumped whatever natural talent they might possess.",
        "translation": "换言之，练习战胜了他们可能拥有的任何天赋。"
    },
    {
        "id": "2007-T1-23",
        "year": 2007,
        "text": "Text 1",
        "word": "subject",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 实验受试者/研究对象",
        "def": "实验受试者、研究对象",
        "sentence": "Ericsson and his colleagues tested <mark>subjects</mark> across fields ranging from music to medicine.",
        "sentencePlain": "Ericsson and his colleagues tested subjects across fields ranging from music to medicine.",
        "translation": "埃里克森和他的同事们测试了从音乐到医学等各个领域的受试对象。"
    },
    {
        "id": "2007-T1-24",
        "year": 2007,
        "text": "Text 1",
        "word": "inborn",
        "category": "核心词汇",
        "noteTag": "★ 同义词：innate / natural",
        "def": "先天的、天生的",
        "sentence": "The belief that top performers possess <mark>inborn</mark> traits is widely overstated.",
        "sentencePlain": "The belief that top performers possess inborn traits is widely overstated.",
        "translation": "认为顶尖精英拥有先天特质的信念被广泛夸大了。"
    },
    {
        "id": "2007-T1-25",
        "year": 2007,
        "text": "Text 1",
        "word": "encode",
        "category": "核心词汇",
        "noteTag": "★ 认知心理学术语 · 信息编码",
        "def": "编码、将……编入记忆",
        "sentence": "The brain learns to <mark>encode</mark> complex chunks of information into long-term working memory.",
        "sentencePlain": "The brain learns to encode complex chunks of information into long-term working memory.",
        "translation": "大脑学会将复杂的信息块编码进长时工作记忆中。"
    },
    {
        "id": "2007-T1-26",
        "year": 2007,
        "text": "Text 1",
        "word": "take to",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 喜欢上/从事",
        "def": "喜欢上；养成……习惯；从事",
        "sentence": "Those who <mark>take to</mark> an activity early often simply benefit from early encouragement and guidance.",
        "sentencePlain": "Those who take to an activity early often simply benefit from early encouragement and guidance.",
        "translation": "那些早早喜欢上某项活动的人，往往只是得益于早期的鼓励与引导。"
    },
    {
        "id": "2007-T1-27",
        "year": 2007,
        "text": "Text 1",
        "word": "deliberate",
        "category": "熟词生义",
        "noteTag": "★ 核心考点 · 刻意练习 (deliberate practice)",
        "def": "刻意的、深思熟虑的",
        "sentence": "Ericsson defines <mark>deliberate</mark> practice as effortful, goal-directed activity guided by a coach.",
        "sentencePlain": "Ericsson defines deliberate practice as effortful, goal-directed activity guided by a coach.",
        "translation": "埃里克森将“刻意练习”定义为在导师指导下需要付出努力且目标明确的活动。"
    },
    {
        "id": "2007-T1-28",
        "year": 2007,
        "text": "Text 1",
        "word": "entail (involve)",
        "category": "核心词汇",
        "noteTag": "★ 同义替换 · involve",
        "def": "牵涉、导致、意味着",
        "sentence": "Truly effective training <mark>entails</mark> setting specific goals and obtaining immediate feedback.",
        "sentencePlain": "Truly effective training entails setting specific goals and obtaining immediate feedback.",
        "translation": "真正有效的训练意味着（涉及）设定明确具体的目标并获取即时反馈。"
    },
    {
        "id": "2007-T1-29",
        "year": 2007,
        "text": "Text 1",
        "word": "set",
        "category": "熟词生义",
        "noteTag": "★ 高频搭配 · 设定目标基准 (set goals)",
        "def": "确立、设定",
        "sentence": "Outstanding performers systematically <mark>set</mark> challenging benchmarks for themselves.",
        "sentencePlain": "Outstanding performers systematically set challenging benchmarks for themselves.",
        "translation": "杰出的表现者系统性地为自己设定富有挑战性的基准。"
    },
    {
        "id": "2007-T1-30",
        "year": 2007,
        "text": "Text 1",
        "word": "focus on",
        "category": "固定短语",
        "noteTag": "★ 高频核心短语 · 专注于",
        "def": "集中于、专注于",
        "sentence": "They constantly <mark>focus on</mark> their weakest areas rather than resting on their laurels.",
        "sentencePlain": "They constantly focus on their weakest areas rather than resting on their laurels.",
        "translation": "他们持续专注于自己最薄弱的环节，而不是坐享既有成果。"
    },
    {
        "id": "2007-T1-31",
        "year": 2007,
        "text": "Text 1",
        "word": "expert",
        "category": "核心词汇",
        "noteTag": "★ 核心词汇 · 专家水平",
        "def": "专家、行家；专业的",
        "sentence": "It requires years of strenuous effort to achieve <mark>expert</mark> performance in any competitive field.",
        "sentencePlain": "It requires years of strenuous effort to achieve expert performance in any competitive field.",
        "translation": "在任何竞争性领域达到专家级的顶尖水平都需要数年艰苦卓绝的努力。"
    },
    {
        "id": "2007-T1-32",
        "year": 2007,
        "text": "Text 1",
        "word": "bare",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 最起码/仅仅",
        "def": "仅仅的、最基本的",
        "sentence": "Ten thousand hours of training is merely the <mark>bare</mark> minimum required to enter the elite tier.",
        "sentencePlain": "Ten thousand hours of training is merely the bare minimum required to enter the elite tier.",
        "translation": "一万小时的训练仅仅是进入精英阶层所需要的最起码的底线。"
    },
    {
        "id": "2007-T1-33",
        "year": 2007,
        "text": "Text 1",
        "word": "rather",
        "category": "核心词汇",
        "noteTag": "★ 考研逻辑反折词 · 确切地说/相反",
        "def": "相当；相反、确切地说",
        "sentence": "Greatness is not born; <mark>rather</mark>, it is carefully cultivated through decades of deliberate toil.",
        "sentencePlain": "Greatness is not born; rather, it is carefully cultivated through decades of deliberate toil.",
        "translation": "伟大并非天生；确切地说，它是经过数十年刻苦磨炼精心培养出来的。"
    },
    {
        "id": "2007-T1-34",
        "year": 2007,
        "text": "Text 1",
        "word": "startling",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 令人吃惊的",
        "def": "令人吃惊的、惊人的",
        "sentence": "The researchers arrived at a <mark>startling</mark> conclusion: innate ability plays far less of a role than assumed.",
        "sentencePlain": "The researchers arrived at a startling conclusion: innate ability plays far less of a role than assumed.",
        "translation": "研究人员得出了一个令人震惊的结论：先天能力所起的作用远低于人们的假设。"
    },
    {
        "id": "2007-T1-35",
        "year": 2007,
        "text": "Text 1",
        "word": "assertion",
        "category": "核心词汇",
        "noteTag": "★ 议论文核心观点词 · 断言",
        "def": "断言、主张、主观认定",
        "sentence": "Their bold <mark>assertion</mark> directly challenged the long-held myth of the natural prodigy.",
        "sentencePlain": "Their bold assertion directly challenged the long-held myth of the natural prodigy.",
        "translation": "他们大胆的主张直接挑战了长久以来关于天生神童的神话。"
    },
    {
        "id": "2007-T1-36",
        "year": 2007,
        "text": "Text 1",
        "word": "achiever",
        "category": "核心词汇",
        "noteTag": "★ 构词：achieve + er",
        "def": "成功者、有成就的人",
        "sentence": "High <mark>achievers</mark> are characterized not by effortless talent, but by extraordinary persistence.",
        "sentencePlain": "High achievers are characterized not by effortless talent, but by extraordinary persistence.",
        "translation": "高成就者的特征不是轻松自如的天分，而是非同寻常的坚持不懈。"
    },
    {
        "id": "2007-T1-37",
        "year": 2007,
        "text": "Text 1",
        "word": "statistics (details)",
        "category": "熟词生义",
        "noteTag": "★ 手写批注 · 意指详细数据/数据细节 (details)",
        "def": "统计数据、详实数据",
        "sentence": "The <mark>statistics</mark> collected over three decades demonstrated that innate traits were rarely predictive.",
        "sentencePlain": "The statistics collected over three decades demonstrated that innate traits were rarely predictive.",
        "translation": "三十多年来收集的详实统计数据表明，先天特征几乎无法预测未来的成就。"
    },
    {
        "id": "2007-T1-38",
        "year": 2007,
        "text": "Text 1",
        "word": "owe A to B",
        "category": "固定短语",
        "noteTag": "★ 考研高频因果搭配 · 归功于",
        "def": "将 A 归功于 B",
        "sentence": "Mozart did not <mark>owe</mark> his masterworks solely <mark>to</mark> divine gift, but to unprecedented early training.",
        "sentencePlain": "Mozart did not owe his masterworks solely to divine gift, but to unprecedented early training.",
        "translation": "莫扎特的杰作绝非仅仅归功于上帝赐予的天赋，而是归功于前所未有的早期训练。"
    },
    {
        "id": "2007-T1-39",
        "year": 2007,
        "text": "Text 1",
        "word": "mania",
        "category": "核心词汇",
        "noteTag": "★ 核心难词 · 狂热痴迷",
        "def": "狂热、狂乱、痴迷",
        "sentence": "The modern <mark>mania</mark> for identifying gifted children often overlooks the supreme power of practice.",
        "sentencePlain": "The modern mania for identifying gifted children often overlooks the supreme power of practice.",
        "translation": "当代社会寻找天才儿童的狂热往往忽视了练习的无上力量。"
    }
]

cards_2007_t2 = [
    {
        "id": "2007-T2-01",
        "year": 2007,
        "text": "Text 2",
        "word": "supplement",
        "category": "核心词汇",
        "noteTag": "★ 核心动词与名词 · 增补",
        "def": "补充、增补",
        "sentence": "Traditional measures of intelligence should be <mark>supplemented</mark> with evaluations of practical creativity.",
        "sentencePlain": "Traditional measures of intelligence should be supplemented with evaluations of practical creativity.",
        "translation": "传统的智力测验应当辅以对实际创造力的评估。"
    },
    {
        "id": "2007-T2-02",
        "year": 2007,
        "text": "Text 2",
        "word": "field",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 学术领域/专业界",
        "def": "领域、学科",
        "sentence": "Researchers across the <mark>field</mark> of cognitive psychology have questioned the validity of a single IQ score.",
        "sentencePlain": "Researchers across the field of cognitive psychology have questioned the validity of a single IQ score.",
        "translation": "认知心理学领域的研究人员一直在质疑单一智商分数的有效性。"
    },
    {
        "id": "2007-T2-03",
        "year": 2007,
        "text": "Text 2",
        "word": "figure out",
        "category": "固定短语",
        "noteTag": "★ 核心动词短语 · 弄明白/算出",
        "def": "弄清楚、理解、计算出",
        "sentence": "Psychologists tried to <mark>figure out</mark> whether intelligence is a unified trait or a collection of distinct abilities.",
        "sentencePlain": "Psychologists tried to figure out whether intelligence is a unified trait or a collection of distinct abilities.",
        "translation": "心理学家们试图弄清楚智力是一种统合特质，还是多种不同能力的集合。"
    },
    {
        "id": "2007-T2-04",
        "year": 2007,
        "text": "Text 2",
        "word": "feature",
        "category": "核心词汇",
        "noteTag": "★ 核心词汇 · 特征/特色",
        "def": "特点、特征；以……为特色",
        "sentence": "Mental adaptability in novel situations remains a hallmark <mark>feature</mark> of true intelligence.",
        "sentencePlain": "Mental adaptability in novel situations remains a hallmark feature of true intelligence.",
        "translation": "在崭新情境中的思维适应能力依然是真正智力的标志性特征。"
    },
    {
        "id": "2007-T2-05",
        "year": 2007,
        "text": "Text 2",
        "word": "analogy",
        "category": "核心词汇",
        "noteTag": "★ 逻辑考点词 · 类比推理",
        "def": "类比、类推",
        "sentence": "Standard test questions often rely on verbal <mark>analogy</mark> and numerical patterns.",
        "sentencePlain": "Standard test questions often rely on verbal analogy and numerical patterns.",
        "translation": "标准化测试试题常常依赖于词汇类比和数字模式规律。"
    },
    {
        "id": "2007-T2-06",
        "year": 2007,
        "text": "Text 2",
        "word": "sequence",
        "category": "核心词汇",
        "noteTag": "★ 核心逻辑词 · 序列",
        "def": "顺序、序列、连续事件",
        "sentence": "Candidates are required to recognize the underlying <mark>sequence</mark> of abstract symbols.",
        "sentencePlain": "Candidates are required to recognize the underlying sequence of abstract symbols.",
        "translation": "应试者被要求识别出抽象符号背后蕴含的排列序列。"
    },
    {
        "id": "2007-T2-07",
        "year": 2007,
        "text": "Text 2",
        "word": "nature",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 本质/天性 (非大自然)",
        "def": "本质、天性",
        "sentence": "The debate over the fundamental <mark>nature</mark> of human intellect has raged for decades.",
        "sentencePlain": "The debate over the fundamental nature of human intellect has raged for decades.",
        "translation": "关于人类智力基本本质的辩论已经激烈进行了数十年。"
    },
    {
        "id": "2007-T2-08",
        "year": 2007,
        "text": "Text 2",
        "word": "coincidence",
        "category": "核心词汇",
        "noteTag": "★ 核心词汇 · 巧合之事",
        "def": "巧合、巧合之事",
        "sentence": "High scores in mathematics and language are not mere <mark>coincidence</mark>; they often reflect a common cognitive factor.",
        "sentencePlain": "High scores in mathematics and language are not mere coincidence; they often reflect a common cognitive factor.",
        "translation": "数学和语言上的高分绝非单纯的巧合；它们往往反映出一种共同的认知因素。"
    },
    {
        "id": "2007-T2-09",
        "year": 2007,
        "text": "Text 2",
        "word": "suit sb to do",
        "category": "固定短语",
        "noteTag": "★ 动词短语搭配 · 使适合",
        "def": "使某人适合做某事",
        "sentence": "A high general intelligence may <mark>suit</mark> a person <mark>to</mark> master various demanding professions.",
        "sentencePlain": "A high general intelligence may suit a person to master various demanding professions.",
        "translation": "高水平的通用智力可能使一个人适合去掌握各种要求苛刻的职业。"
    },
    {
        "id": "2007-T2-10",
        "year": 2007,
        "text": "Text 2",
        "word": "envision",
        "category": "核心词汇",
        "noteTag": "★ 构词：en + vision · 展望设想",
        "def": "展望、设想、预想",
        "sentence": "Early psychometricians did not <mark>envision</mark> how narrowly their tests would eventually be applied.",
        "sentencePlain": "Early psychometricians did not envision how narrowly their tests would eventually be applied.",
        "translation": "早期的心理测验学家并没有预料到他们的测验最终会被应用得如此狭隘。"
    },
    {
        "id": "2007-T2-11",
        "year": 2007,
        "text": "Text 2",
        "word": "deduce",
        "category": "核心词汇",
        "noteTag": "★ 逻辑考点词 · 演绎推导",
        "def": "推论、推断、演绎",
        "sentence": "From these test results, educators attempted to <mark>deduce</mark> a child's overall academic potential.",
        "sentencePlain": "From these test results, educators attempted to deduce a child's overall academic potential.",
        "translation": "从这些测验结果中，教育工作者试图推断出一个孩子的整体学业潜质。"
    },
    {
        "id": "2007-T2-12",
        "year": 2007,
        "text": "Text 2",
        "word": "etude",
        "category": "核心词汇",
        "noteTag": "★ 考点类比术语 · 练习曲",
        "def": "练习曲",
        "sentence": "Mastering basic test drills is akin to practicing a musical <mark>etude</mark> before composing a symphony.",
        "sentencePlain": "Mastering basic test drills is akin to practicing a musical etude before composing a symphony.",
        "translation": "掌握基础的应试训练类似于在创作交响乐前练习一首音乐练习曲。"
    },
    {
        "id": "2007-T2-13",
        "year": 2007,
        "text": "Text 2",
        "word": "term",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 学术术语",
        "def": "术语、专门用语；把……称作",
        "sentence": "Charles Spearman coined the <mark>term</mark> 'g factor' to designate general mental ability.",
        "sentencePlain": "Charles Spearman coined the term 'g factor' to designate general mental ability.",
        "translation": "查尔斯·斯皮尔曼创造了“g因素”这一术语来指代一般智力。"
    },
    {
        "id": "2007-T2-14",
        "year": 2007,
        "text": "Text 2",
        "word": "neurology",
        "category": "核心词汇",
        "noteTag": "★ 学科名词 · 神经学",
        "def": "神经学、神经病学",
        "sentence": "Advances in <mark>neurology</mark> are shedding light on how neural efficiency relates to problem-solving.",
        "sentencePlain": "Advances in neurology are shedding light on how neural efficiency relates to problem-solving.",
        "translation": "神经学的发展正在揭示神经传导效率与问题解决能力之间的关联。"
    },
    {
        "id": "2007-T2-15",
        "year": 2007,
        "text": "Text 2",
        "word": "encompass",
        "category": "核心词汇",
        "noteTag": "★ 核心高频词 · 涵盖包罗",
        "def": "包含、涵盖、围绕",
        "sentence": "True cognitive capacity must <mark>encompass</mark> practical wisdom and emotional adaptability.",
        "sentencePlain": "True cognitive capacity must encompass practical wisdom and emotional adaptability.",
        "translation": "真正的认知能力必须涵盖实践智慧与情绪适应力。"
    },
    {
        "id": "2007-T2-16",
        "year": 2007,
        "text": "Text 2",
        "word": "primarily",
        "category": "核心词汇",
        "noteTag": "★ 程度副词 · 主要地",
        "def": "主要地、首要地",
        "sentence": "The exam was designed <mark>primarily</mark> to identify students who required special instructional assistance.",
        "sentencePlain": "The exam was designed primarily to identify students who required special instructional assistance.",
        "translation": "该考试最初主要是为了识别那些需要特殊教学辅助的学生而设计的。"
    },
    {
        "id": "2007-T2-17",
        "year": 2007,
        "text": "Text 2",
        "word": "generally",
        "category": "核心词汇",
        "noteTag": "★ 频度副词 · 通常大体上",
        "def": "一般地、通常、大体上",
        "sentence": "IQ scores are <mark>generally</mark> correlated with educational attainment and income level.",
        "sentencePlain": "IQ scores are generally correlated with educational attainment and income level.",
        "translation": "智商分数通常与受教育程度和收入水平呈正相关。"
    },
    {
        "id": "2007-T2-18",
        "year": 2007,
        "text": "Text 2",
        "word": "come in",
        "category": "固定短语",
        "noteTag": "★ 口语化动词短语 · 在此起作用",
        "def": "起作用、参与；到达、上市",
        "sentence": "That is where emotional intelligence and interpersonal skills <mark>come in</mark>.",
        "sentencePlain": "That is where emotional intelligence and interpersonal skills come in.",
        "translation": "那正是情商和人际交往技能开始发挥作用的地方。"
    },
    {
        "id": "2007-T2-19",
        "year": 2007,
        "text": "Text 2",
        "word": "populate",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 充塞分布",
        "def": "居住于、充满、构成人口",
        "sentence": "Diverse mental attributes <mark>populate</mark> the complex landscape of the human brain.",
        "sentencePlain": "Diverse mental attributes populate the complex landscape of the human brain.",
        "translation": "多种多样的心理属性构成了人类大脑错综复杂的认知图景。"
    },
    {
        "id": "2007-T2-20",
        "year": 2007,
        "text": "Text 2",
        "word": "distribution",
        "category": "核心词汇",
        "noteTag": "★ 统计学术语 · 正态分布",
        "def": "分布、分配、分配状态",
        "sentence": "Human intelligence follows a classic bell-curve <mark>distribution</mark> across the population.",
        "sentencePlain": "Human intelligence follows a classic bell-curve distribution across the population.",
        "translation": "人类智力在整个人群中呈现出经典的钟形曲线分布。"
    },
    {
        "id": "2007-T2-21",
        "year": 2007,
        "text": "Text 2",
        "word": "divide",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 名词指分歧/隔阂",
        "def": "分歧、鸿沟；分开",
        "sentence": "There remains an ideological <mark>divide</mark> between hereditary theorists and environmental advocates.",
        "sentencePlain": "There remains an ideological divide between hereditary theorists and environmental advocates.",
        "translation": "在遗传决定论者和环境倡导者之间依然存在着一道思想上的鸿沟。"
    },
    {
        "id": "2007-T2-22",
        "year": 2007,
        "text": "Text 2",
        "word": "capture",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 真实体现/捕捉",
        "def": "充分体现、捕捉、捕获",
        "sentence": "Paper-and-pencil tests fail to <mark>capture</mark> the rich nuances of artistic or social genius.",
        "sentencePlain": "Paper-and-pencil tests fail to capture the rich nuances of artistic or social genius.",
        "translation": "纸笔测验无法捕捉并体现艺术才能或社交天赋的丰富微妙之处。"
    },
    {
        "id": "2007-T2-23",
        "year": 2007,
        "text": "Text 2",
        "word": "standardized",
        "category": "核心词汇",
        "noteTag": "★ 核心应试词 · 标准化测试",
        "def": "标准化的",
        "sentence": "Reliance on <mark>standardized</mark> testing can lead to a narrow definition of student capability.",
        "sentencePlain": "Reliance on standardized testing can lead to a narrow definition of student capability.",
        "translation": "对标准化测试的依赖会导致对学生能力的定义过于狭隘。"
    },
    {
        "id": "2007-T2-24",
        "year": 2007,
        "text": "Text 2",
        "word": "critical",
        "category": "核心词汇",
        "noteTag": "★ 多义词 · 批判性思维/关键的",
        "def": "批判性的；关键的、至关重要的",
        "sentence": "Developing <mark>critical</mark> reasoning skills is far more valuable than memorizing isolated facts.",
        "sentencePlain": "Developing critical reasoning skills is far more valuable than memorizing isolated facts.",
        "translation": "培养批判性推理能力远比死记硬背孤立的事实有价值得多。"
    },
    {
        "id": "2007-T2-25",
        "year": 2007,
        "text": "Text 2",
        "word": "assess",
        "category": "核心词汇",
        "noteTag": "★ 学术高频核心动词 · 评定",
        "def": "评定、估价、评估",
        "sentence": "Psychologists must use multiple modalities to <mark>assess</mark> a subject's genuine intellectual depth.",
        "sentencePlain": "Psychologists must use multiple modalities to assess a subject's genuine intellectual depth.",
        "translation": "心理学家必须运用多种形式来评估受试者真正的智力深度。"
    },
    {
        "id": "2007-T2-26",
        "year": 2007,
        "text": "Text 2",
        "word": "matter",
        "category": "熟词生义",
        "noteTag": "★ 动词用法 · 关系重大/要紧",
        "def": "要紧、有重大影响",
        "sentence": "What should really <mark>matter</mark> is whether individuals can apply knowledge to novel real-world challenges.",
        "sentencePlain": "What should really matter is whether individuals can apply knowledge to novel real-world challenges.",
        "translation": "真正至关重要的，应该是个人能否将知识应用于现实生活中的崭新挑战。"
    },
    {
        "id": "2007-T2-27",
        "year": 2007,
        "text": "Text 2",
        "word": "whether or",
        "category": "句型语法",
        "noteTag": "★ 连词短语引导宾语/让步从句",
        "def": "是否、不管……还是……",
        "sentence": "Critics questioned <mark>whether</mark> IQ tests accurately predict real-world success <mark>or</mark> merely school performance.",
        "sentencePlain": "Critics questioned whether IQ tests accurately predict real-world success or merely school performance.",
        "translation": "批评者质疑智商测试究竟是能准确预测现实中的成功，还是仅仅预示着在校学业表现。"
    },
    {
        "id": "2007-T2-28",
        "year": 2007,
        "text": "Text 2",
        "word": "do not necessarily",
        "category": "句型语法",
        "noteTag": "★ 考研经典部分否定句型 · 未必",
        "def": "未必、不一定",
        "sentence": "High analytical test scores <mark>do not necessarily</mark> translate into creative problem-solving ability.",
        "sentencePlain": "High analytical test scores do not necessarily translate into creative problem-solving ability.",
        "translation": "高分的分析测试成绩未必会转化为创造性解决问题的能力。"
    },
    {
        "id": "2007-T2-29",
        "year": 2007,
        "text": "Text 2",
        "word": "toil",
        "category": "核心词汇",
        "noteTag": "★ 文学与学术用词 · 辛勤耕耘",
        "def": "辛劳、苦工；艰苦跋涉",
        "sentence": "Behind every breakthrough lies years of unglamorous <mark>toil</mark> rather than instant inspiration.",
        "sentencePlain": "Behind every breakthrough lies years of unglamorous toil rather than instant inspiration.",
        "translation": "在每一项重大突破背后，都潜藏着数年默默无闻的辛劳付出，而非瞬间的灵感迸发。"
    },
    {
        "id": "2007-T2-30",
        "year": 2007,
        "text": "Text 2",
        "word": "skeptical",
        "category": "核心词汇",
        "noteTag": "★ 作者态度题必背词 · 怀疑态度",
        "def": "怀疑的、多疑的",
        "sentence": "Many contemporary scholars remain deeply <mark>skeptical</mark> of claims that intelligence is fixed at birth.",
        "sentencePlain": "Many contemporary scholars remain deeply skeptical of claims that intelligence is fixed at birth.",
        "translation": "许多当代学者对于智力在出生时就已注定的说法依然深表怀疑。"
    },
    {
        "id": "2007-T2-31",
        "year": 2007,
        "text": "Text 2",
        "word": "impartial",
        "category": "核心词汇",
        "noteTag": "★ 构词：im(否定) + partial(偏袒)",
        "def": "公正的、不偏不倚的",
        "sentence": "Standardized tests were once championed as an <mark>impartial</mark> tool to eliminate social privilege.",
        "sentencePlain": "Standardized tests were once championed as an impartial tool to eliminate social privilege.",
        "translation": "标准化测试曾被誉为消除社会特权的不偏不倚的公正工具。"
    },
    {
        "id": "2007-T2-32",
        "year": 2007,
        "text": "Text 2",
        "word": "biased",
        "category": "核心词汇",
        "noteTag": "★ 反义词：impartial · 有偏见的",
        "def": "有偏见的、片面的",
        "sentence": "Later studies showed that culturally <mark>biased</mark> questions disadvantaged minority candidates.",
        "sentencePlain": "Later studies showed that culturally biased questions disadvantaged minority candidates.",
        "translation": "后续的研究表明，带有文化偏见的问题会让少数族裔考生处于不利地位。"
    }
]

cards_2007_t3 = [
    {
        "id": "2007-T3-01",
        "year": 2007,
        "text": "Text 3",
        "word": "count on",
        "category": "固定短语",
        "noteTag": "★ 核心动词短语 · 指望依靠",
        "def": "指望、依靠",
        "sentence": "Families can no longer <mark>count on</mark> steady lifetime employment with guaranteed company pensions.",
        "sentencePlain": "Families can no longer count on steady lifetime employment with guaranteed company pensions.",
        "translation": "家庭再也不能指望拥有能够享受企业养老金保障的稳定终身就业了。"
    },
    {
        "id": "2007-T3-02",
        "year": 2007,
        "text": "Text 3",
        "word": "spouse",
        "category": "核心词汇",
        "noteTag": "★ 核心家庭词汇 · 配偶 (夫或妻)",
        "def": "配偶",
        "sentence": "When one breadwinner loses a job, having a working <mark>spouse</mark> provides essential emergency protection.",
        "sentencePlain": "When one breadwinner loses a job, having a working spouse provides essential emergency protection.",
        "translation": "当一位家庭经济支柱失业时，拥有一位有工作的配偶能提供至关重要的应急保障。"
    },
    {
        "id": "2007-T3-03",
        "year": 2007,
        "text": "Text 3",
        "word": "play",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 机制运转 (bring into play)",
        "def": "发生作用、运转；间隙",
        "sentence": "Subtle market dynamics were brought into <mark>play</mark> as corporations shifted risk onto employees.",
        "sentencePlain": "Subtle market dynamics were brought into play as corporations shifted risk onto employees.",
        "translation": "随着企业将风险转嫁给员工，微妙的市场机制开始发挥作用。"
    },
    {
        "id": "2007-T3-04",
        "year": 2007,
        "text": "Text 3",
        "word": "reduce",
        "category": "核心词汇",
        "noteTag": "★ 核心动词 · 使陷入/缩减",
        "def": "减少、缩减；使沦落",
        "sentence": "A sudden layoff can quickly <mark>reduce</mark> a comfortable middle-class household to poverty.",
        "sentencePlain": "A sudden layoff can quickly reduce a comfortable middle-class household to poverty.",
        "translation": "一场突如其来的裁员会迅速使一个生活优渥的中产阶级家庭陷入贫困。"
    },
    {
        "id": "2007-T3-05",
        "year": 2007,
        "text": "Text 3",
        "word": "pink slip",
        "category": "固定短语",
        "noteTag": "★ 文化常识与地道俚语 · 解雇信",
        "def": "解雇通知书",
        "sentence": "Receiving a <mark>pink slip</mark> was once a temporary setback, but now often leads to long-term distress.",
        "sentencePlain": "Receiving a pink slip was once a temporary setback, but now often leads to long-term distress.",
        "translation": "收到解雇通知单曾是一个暂时的挫折，如今却常常导致长期的经济困顿。"
    },
    {
        "id": "2007-T3-06",
        "year": 2007,
        "text": "Text 3",
        "word": "implication",
        "category": "核心词汇",
        "noteTag": "★ 考研超高频核心词 · 启示/深远影响",
        "def": "含义、可能的影响、启示",
        "sentence": "Economists are still calculating the broader <mark>implications</mark> of this seismic economic restructuring.",
        "sentencePlain": "Economists are still calculating the broader implications of this seismic economic restructuring.",
        "translation": "经济学家仍在测算这场剧烈的经济重组所带来的更广泛影响。"
    },
    {
        "id": "2007-T3-07",
        "year": 2007,
        "text": "Text 3",
        "word": "look at",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 审视看待",
        "def": "审视、看待、考虑",
        "sentence": "If you <mark>look at</mark> household debt levels, the vulnerability becomes immediately apparent.",
        "sentencePlain": "If you look at household debt levels, the vulnerability becomes immediately apparent.",
        "translation": "如果你审视一下家庭负债水平，这种脆弱性便立刻显露无疑。"
    },
    {
        "id": "2007-T3-08",
        "year": 2007,
        "text": "Text 3",
        "word": "parachute",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 降落伞补偿金 (golden parachute)",
        "def": "降落伞；降落伞式的救助金",
        "sentence": "While executives enjoy lucrative golden <mark>parachutes</mark>, ordinary laborers are left without a safety net.",
        "sentencePlain": "While executives enjoy lucrative golden parachutes, ordinary laborers are left without a safety net.",
        "translation": "尽管高管享有丰厚的“金色降落伞”（离职补偿金），普通劳工却得不到任何安全网的庇护。"
    },
    {
        "id": "2007-T3-09",
        "year": 2007,
        "text": "Text 3",
        "word": "diagnosis",
        "category": "核心词汇",
        "noteTag": "★ 医学与隐喻词 · 诊断结论",
        "def": "诊断、判断",
        "sentence": "A serious medical <mark>diagnosis</mark> can instantly obliterate a family's lifetime savings.",
        "sentencePlain": "A serious medical diagnosis can instantly obliterate a family's lifetime savings.",
        "translation": "一纸严重的医疗诊断结果能瞬间化掉一个家庭一生的积蓄。"
    },
    {
        "id": "2007-T3-10",
        "year": 2007,
        "text": "Text 3",
        "word": "side effect",
        "category": "固定短语",
        "noteTag": "★ 高频搭配 · 副作用/附带后果",
        "def": "副作用、附带后果",
        "sentence": "An unexpected <mark>side effect</mark> of deregulation was the steep rise in individual financial exposure.",
        "sentencePlain": "An unexpected side effect of deregulation was the steep rise in individual financial exposure.",
        "translation": "放松监管的一个出人意料的副作用，是个人财务风险敞口的急剧上升。"
    },
    {
        "id": "2007-T3-11",
        "year": 2007,
        "text": "Text 3",
        "word": "budget",
        "category": "核心词汇",
        "noteTag": "★ 核心生活与财务词 · 预算",
        "def": "预算；编列预算",
        "sentence": "Fixed costs now consume a terrifying percentage of the average family <mark>budget</mark>.",
        "sentencePlain": "Fixed costs now consume a terrifying percentage of the average family budget.",
        "translation": "固定开支如今吞噬了普通家庭预算中令人胆战心惊的巨大比例。"
    },
    {
        "id": "2007-T3-12",
        "year": 2007,
        "text": "Text 3",
        "word": "go into",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 陷入/进入",
        "def": "进入、陷入；投入",
        "sentence": "Families are forced to <mark>go into</mark> massive debt simply to pay for basic healthcare and housing.",
        "sentencePlain": "Families are forced to go into massive debt simply to pay for basic healthcare and housing.",
        "translation": "家庭被迫背负沉重债务，仅仅是为了支付基础的医疗和住房费用。"
    },
    {
        "id": "2007-T3-13",
        "year": 2007,
        "text": "Text 3",
        "word": "weather",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 动词平安度过风暴",
        "def": "经受住、平安度过",
        "sentence": "Today's middle-class families have far fewer resources to <mark>weather</mark> unexpected financial storms.",
        "sentencePlain": "Today's middle-class families have far fewer resources to weather unexpected financial storms.",
        "translation": "当今的中产阶级家庭拥有的资源大不如前，难以平安度过突如其来的经济风暴。"
    },
    {
        "id": "2007-T3-14",
        "year": 2007,
        "text": "Text 3",
        "word": "back-up",
        "category": "核心词汇",
        "noteTag": "★ 核心词汇 · 应急后备",
        "def": "后备、备用支援",
        "sentence": "With both parents already working, families have exhausted their last emergency <mark>back-up</mark>.",
        "sentencePlain": "With both parents already working, families have exhausted their last emergency back-up.",
        "translation": "随着父母双方都在工作，家庭已经耗尽了他们最后的应急后备力量。"
    },
    {
        "id": "2007-T3-15",
        "year": 2007,
        "text": "Text 3",
        "word": "force",
        "category": "熟词生义",
        "noteTag": "★ 动词用法 · 迫使",
        "def": "迫使；力量",
        "sentence": "Spiraling healthcare costs <mark>force</mark> millions into filing for bankruptcy every year.",
        "sentencePlain": "Spiraling healthcare costs force millions into filing for bankruptcy every year.",
        "translation": "持续飙升的医疗开支迫使数百万人每年申请破产。"
    },
    {
        "id": "2007-T3-16",
        "year": 2007,
        "text": "Text 3",
        "word": "work",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 奏效/起作用",
        "def": "起作用、奏效",
        "sentence": "The old financial formulas no longer <mark>work</mark> in an era of heightened economic volatility.",
        "sentencePlain": "The old financial formulas no longer work in an era of heightened economic volatility.",
        "translation": "在这个经济波动加剧的时代，旧有的理财模式已经不再奏效。"
    },
    {
        "id": "2007-T3-17",
        "year": 2007,
        "text": "Text 3",
        "word": "absorb",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 承受财务损失/冲击",
        "def": "承受、承担、吸收",
        "sentence": "Workers are now expected to <mark>absorb</mark> fluctuating investment risks that companies once assumed.",
        "sentencePlain": "Workers are now expected to absorb fluctuating investment risks that companies once assumed.",
        "translation": "如今劳工需要自行承担波动不定的投资风险，而这些风险过去曾由企业承担。"
    },
    {
        "id": "2007-T3-18",
        "year": 2007,
        "text": "Text 3",
        "word": "stock",
        "category": "核心词汇",
        "noteTag": "★ 核心金融词汇 · 股票",
        "def": "股票；库存",
        "sentence": "Replacing defined pensions with <mark>stock</mark> market 401(k) plans shifted investment volatility to workers.",
        "sentencePlain": "Replacing defined pensions with stock market 401(k) plans shifted investment volatility to workers.",
        "translation": "用股市401(k)计划替代既定养老金，将投资的波动风险转嫁给了劳工。"
    },
    {
        "id": "2007-T3-19",
        "year": 2007,
        "text": "Text 3",
        "word": "interest rate",
        "category": "固定短语",
        "noteTag": "★ 经济金融核心常考短语 · 利率",
        "def": "利率",
        "sentence": "Even a slight rise in the adjustable mortgage <mark>interest rate</mark> could trigger a default.",
        "sentencePlain": "Even a slight rise in the adjustable mortgage interest rate could trigger a default.",
        "translation": "即便是浮动房贷利率的微小上涨，也可能引发违约。"
    },
    {
        "id": "2007-T3-20",
        "year": 2007,
        "text": "Text 3",
        "word": "fluctuation",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 波动起伏",
        "def": "波动、起伏",
        "sentence": "Market <mark>fluctuations</mark> can wipe out years of disciplined retirement contributions in weeks.",
        "sentencePlain": "Market fluctuations can wipe out years of disciplined retirement contributions in weeks.",
        "translation": "市场的剧烈波动可以在数周之内化掉数年按期缴纳的养老储蓄。"
    },
    {
        "id": "2007-T3-21",
        "year": 2007,
        "text": "Text 3",
        "word": "campaign for",
        "category": "固定短语",
        "noteTag": "★ 政治社论高频短语 · 奔走争取",
        "def": "为……发起运动/积极争取",
        "sentence": "Reformers continue to <mark>campaign for</mark> universal health insurance and consumer bankruptcy protections.",
        "sentencePlain": "Reformers continue to campaign for universal health insurance and consumer bankruptcy protections.",
        "translation": "改革者们继续为全民健康保险和消费者破产保护奔走呼吁。"
    },
    {
        "id": "2007-T3-22",
        "year": 2007,
        "text": "Text 3",
        "word": "trade",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 权衡取舍 (trade-off)",
        "def": "权衡、交换；行当",
        "sentence": "Families often have to <mark>trade</mark> comprehensive healthcare coverage for affordable monthly premiums.",
        "sentencePlain": "Families often have to trade comprehensive healthcare coverage for affordable monthly premiums.",
        "translation": "各家庭往往不得不牺牲全面的医疗保障，以换取能够负担得起的每月保费。"
    },
    {
        "id": "2007-T3-23",
        "year": 2007,
        "text": "Text 3",
        "word": "payment",
        "category": "核心词汇",
        "noteTag": "★ 核心财务词 · 分期款项",
        "def": "支付款额、分期付款",
        "sentence": "Mortgage <mark>payments</mark> consume an unprecedented fraction of contemporary household earnings.",
        "sentencePlain": "Mortgage payments consume an unprecedented fraction of contemporary household earnings.",
        "translation": "房贷月供消耗了当代家庭收入中前所未有的巨大份额。"
    },
    {
        "id": "2007-T3-24",
        "year": 2007,
        "text": "Text 3",
        "word": "bare (bear过去式)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：bear过去式承受 (bore/bare)",
        "def": "承受、承担",
        "sentence": "Working families <mark>bare</mark> the brunt of corporate restructuring and pension cuts.",
        "sentencePlain": "Working families bare the brunt of corporate restructuring and pension cuts.",
        "translation": "工薪家庭承受着企业重组与养老金削减的主要冲击。"
    },
    {
        "id": "2007-T3-25",
        "year": 2007,
        "text": "Text 3",
        "word": "cost",
        "category": "核心词汇",
        "noteTag": "★ 核心经济词汇 · 代价费用",
        "def": "费用、代价；使付出代价",
        "sentence": "The escalating <mark>cost</mark> of higher education further drains middle-class savings.",
        "sentencePlain": "The escalating cost of higher education further drains middle-class savings.",
        "translation": "高等教育不断攀升的费用进一步抽干了中产阶级的积蓄。"
    },
    {
        "id": "2007-T3-26",
        "year": 2007,
        "text": "Text 3",
        "word": "working against",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 与……相悖/不利",
        "def": "对……不利、阻碍",
        "sentence": "Changing economic tides are actively <mark>working against</mark> prudent family savers.",
        "sentencePlain": "Changing economic tides are actively working against prudent family savers.",
        "translation": "变幻莫测的经济浪潮正不利于那些勤勉谨慎的家庭储蓄者。"
    },
    {
        "id": "2007-T3-27",
        "year": 2007,
        "text": "Text 3",
        "word": "attendant",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 随之而来的 (adj.)",
        "def": "伴随的、随之而来的",
        "sentence": "Flexible labor contracts brought severe job instability and <mark>attendant</mark> emotional anxiety.",
        "sentencePlain": "Flexible labor contracts brought severe job instability and attendant emotional anxiety.",
        "translation": "灵活的劳工合同带来了严重的工作不稳定性以及随之而来的焦虑情绪。"
    },
    {
        "id": "2007-T3-28",
        "year": 2007,
        "text": "Text 3",
        "word": "exercise",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 行使权力/权利",
        "def": "行使、运用",
        "sentence": "Consumers find it impossible to <mark>exercise</mark> genuine choice when medical emergencies strike.",
        "sentencePlain": "Consumers find it impossible to exercise genuine choice when medical emergencies strike.",
        "translation": "当突发医疗紧急状况来临时，消费者发现自己根本无法行使真正的选择权。"
    },
    {
        "id": "2007-T3-29",
        "year": 2007,
        "text": "Text 3",
        "word": "dose",
        "category": "熟词生义",
        "noteTag": "★ 隐喻用法 · 承受一剂打击/良药",
        "def": "一剂、一份",
        "sentence": "The economy delivered a harsh <mark>dose</mark> of reality to those who assumed their jobs were secure.",
        "sentencePlain": "The economy delivered a harsh dose of reality to those who assumed their jobs were secure.",
        "translation": "经济现实给那些自以为工作无虞的人泼了一盆残酷的冷水（送上一剂苦口良药）。"
    },
    {
        "id": "2007-T3-30",
        "year": 2007,
        "text": "Text 3",
        "word": "a good deal",
        "category": "固定短语",
        "noteTag": "★ 等价于 a great deal / a lot · 大量",
        "def": "大量、许多",
        "sentence": "Modern workers shoulder <mark>a good deal</mark> more financial hazard than their parents ever did.",
        "sentencePlain": "Modern workers shoulder a good deal more financial hazard than their parents ever did.",
        "translation": "现代工薪族承担的财务风险比他们父辈所经历的要多得多。"
    },
    {
        "id": "2007-T3-31",
        "year": 2007,
        "text": "Text 3",
        "word": "wholesale",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 全盘的/大规模的 (非批发)",
        "def": "大规模的、全盘的",
        "sentence": "The <mark>wholesale</mark> shift from employer-sponsored welfare to individual risk has redefined capitalism.",
        "sentencePlain": "The wholesale shift from employer-sponsored welfare to individual risk has redefined capitalism.",
        "translation": "从雇主赞助的福利到由个人承担风险的全面（大规模）转变，重新定义了资本主义。"
    },
    {
        "id": "2007-T3-32",
        "year": 2007,
        "text": "Text 3",
        "word": "fallout",
        "category": "熟词生义",
        "noteTag": "★ 核心考点词 · 负面余波/恶果",
        "def": "余波、附带恶果",
        "sentence": "The financial <mark>fallout</mark> of a sudden medical crisis can haunt an innocent household for decades.",
        "sentencePlain": "The financial fallout of a sudden medical crisis can haunt an innocent household for decades.",
        "translation": "一场突如其来的医疗危机所造成的经济余波，能困扰一个无辜家庭长达数十年之久。"
    },
    {
        "id": "2007-T3-33",
        "year": 2007,
        "text": "Text 3",
        "word": "demographic",
        "category": "核心词汇",
        "noteTag": "★ 学术社论高频词 · 人口结构",
        "def": "人口统计的、人口结构的；特定人群",
        "sentence": "This broad <mark>demographic</mark> transformation has left middle-class citizens exposed on multiple fronts.",
        "sentencePlain": "This broad demographic transformation has left middle-class citizens exposed on multiple fronts.",
        "translation": "这种广泛的人口结构转变使得中产阶级民众在多个方面都面临风险。"
    },
    {
        "id": "2007-T3-34",
        "year": 2007,
        "text": "Text 3",
        "word": "deductible",
        "category": "核心词汇",
        "noteTag": "★ 保险医疗专业常考词 · 免赔额",
        "def": "免赔额、自付额",
        "sentence": "Skyrocketing annual <mark>deductibles</mark> mean patients pay thousands out-of-pocket before insurance kicks in.",
        "sentencePlain": "Skyrocketing annual deductibles mean patients pay thousands out-of-pocket before insurance kicks in.",
        "translation": "飙升的年度免赔额意味着病人在保险开始报销前必须先自掏腰包数千美元。"
    }
]

cards_2007_t4 = [
    {
        "id": "2007-T4-01",
        "year": 2007,
        "text": "Text 4",
        "word": "just as",
        "category": "句型语法",
        "noteTag": "★ 连词短语 · 正当……之际/正如",
        "def": "正如……；正当……之际",
        "sentence": "<mark>Just as</mark> public outrage over corporate fraud was subsiding, a new scandal rocked the corporate world.",
        "sentencePlain": "Just as public outrage over corporate fraud was subsiding, a new scandal rocked the corporate world.",
        "translation": "正当公众对企业财务欺诈的愤怒有所平息之际，一场新的丑闻又震动了商界。"
    },
    {
        "id": "2007-T4-02",
        "year": 2007,
        "text": "Text 4",
        "word": "nasty",
        "category": "核心词汇",
        "noteTag": "★ 感情色彩贬义词 · 令人厌恶的/严重的",
        "def": "严重的、令人厌恶的、棘手的",
        "sentence": "Data breaches have introduced a <mark>nasty</mark> new vulnerability into consumer commerce.",
        "sentencePlain": "Data breaches have introduced a nasty new vulnerability into consumer commerce.",
        "translation": "数据泄露事件给消费者商业领域注入了一处令人头疼的严重漏洞。"
    },
    {
        "id": "2007-T4-03",
        "year": 2007,
        "text": "Text 4",
        "word": "executive suite",
        "category": "固定短语",
        "noteTag": "★ 商业语境专有代称 · 高管层",
        "def": "企业高管层、管理层办公室",
        "sentence": "The crisis quickly reached the <mark>executive suite</mark>, forcing board directors to take immediate action.",
        "sentencePlain": "The crisis quickly reached the executive suite, forcing board directors to take immediate action.",
        "translation": "危机迅速波及企业高管层，迫使董事会成员立即采取行动。"
    },
    {
        "id": "2007-T4-04",
        "year": 2007,
        "text": "Text 4",
        "word": "sort out",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 解决处理/理清",
        "def": "解决、理清、收拾",
        "sentence": "Executives must quickly <mark>sort out</mark> the flaws in their internal information controls.",
        "sentencePlain": "Executives must quickly sort out the flaws in their internal information controls.",
        "translation": "高管们必须迅速理清并解决他们内部信息控制中存在的缺陷。"
    },
    {
        "id": "2007-T4-05",
        "year": 2007,
        "text": "Text 4",
        "word": "threaten",
        "category": "核心词汇",
        "noteTag": "★ 核心动词 · 威胁危及",
        "def": "威胁、危及",
        "sentence": "Stolen customer identities <mark>threaten</mark> the very bedrock of online consumer trust.",
        "sentencePlain": "Stolen customer identities threaten the very bedrock of online consumer trust.",
        "translation": "被盗的客户身份信息正在威胁着在线消费者信任的基石。"
    },
    {
        "id": "2007-T4-06",
        "year": 2007,
        "text": "Text 4",
        "word": "put right",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 拨乱反正/纠正",
        "def": "纠正、改正、拨乱反正",
        "sentence": "Management pledged to <mark>put right</mark> any procedural errors that compromised user security.",
        "sentencePlain": "Management pledged to put right any procedural errors that compromised user security.",
        "translation": "管理层承诺纠正任何危及用户安全的操作流程错误。"
    },
    {
        "id": "2007-T4-07",
        "year": 2007,
        "text": "Text 4",
        "word": "be seen as",
        "category": "固定短语",
        "noteTag": "★ 被动搭配 · 被看作/被视作",
        "def": "被视作、被看作",
        "sentence": "Data protection must <mark>be seen as</mark> a core fiduciary duty rather than a mere IT expense.",
        "sentencePlain": "Data protection must be seen as a core fiduciary duty rather than a mere IT expense.",
        "translation": "数据保护必须被视作一项核心信托责任，而非单纯的IT开支。"
    },
    {
        "id": "2007-T4-08",
        "year": 2007,
        "text": "Text 4",
        "word": "earn",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 博得/赢得声誉",
        "def": "博得、赢得",
        "sentence": "A trustworthy reputation takes decades to build; companies must continually <mark>earn</mark> customer loyalty.",
        "sentencePlain": "A trustworthy reputation takes decades to build; companies must continually earn customer loyalty.",
        "translation": "值得信赖的声誉历经数十年艰苦建立；企业必须持续赢得客户的忠诚。"
    },
    {
        "id": "2007-T4-09",
        "year": 2007,
        "text": "Text 4",
        "word": "board",
        "category": "熟词生义",
        "noteTag": "★ 商业语境核心词 · 董事会 (非木板)",
        "def": "董事会",
        "sentence": "The <mark>board</mark> of directors is now legally liable for safeguarding confidential customer assets.",
        "sentencePlain": "The board of directors is now legally liable for safeguarding confidential customer assets.",
        "translation": "董事会如今在保护机密客户资产方面承担着法律责任。"
    },
    {
        "id": "2007-T4-10",
        "year": 2007,
        "text": "Text 4",
        "word": "peer into",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 仔细审视",
        "def": "仔细审视、凝视、窥视",
        "sentence": "Regulators began to <mark>peer into</mark> the opaque third-party contractors processing client data.",
        "sentencePlain": "Regulators began to peer into the opaque third-party contractors processing client data.",
        "translation": "监管机构开始深入审视那些处理客户数据的不透明第三方外包商。"
    },
    {
        "id": "2007-T4-11",
        "year": 2007,
        "text": "Text 4",
        "word": "intricate",
        "category": "核心词汇",
        "noteTag": "★ 考研高阶形容词 · 错综复杂",
        "def": "错综复杂的、复杂精细的",
        "sentence": "Modern corporate networks possess an <mark>intricate</mark> architecture that can hide insidious vulnerabilities.",
        "sentencePlain": "Modern corporate networks possess an intricate architecture that can hide insidious vulnerabilities.",
        "translation": "现代企业网络具备错综复杂的架构，这种架构可能掩藏着隐蔽的漏洞。"
    },
    {
        "id": "2007-T4-12",
        "year": 2007,
        "text": "Text 4",
        "word": "redundancy",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 容灾冗余备份",
        "def": "冗余设计、备用系统；裁员",
        "sentence": "Strong cybersecurity requires built-in system <mark>redundancy</mark> to prevent single points of failure.",
        "sentencePlain": "Strong cybersecurity requires built-in system redundancy to prevent single points of failure.",
        "translation": "强大的网络安全需要内置的系统冗余，以防止出现单点故障。"
    },
    {
        "id": "2007-T4-13",
        "year": 2007,
        "text": "Text 4",
        "word": "behalf",
        "category": "核心词汇",
        "noteTag": "★ 固定搭配 · on behalf of 代表/为了利益",
        "def": "利益、代表",
        "sentence": "Executives must act on <mark>behalf</mark> of shareholders by anticipating digital catastrophes.",
        "sentencePlain": "Executives must act on behalf of shareholders by anticipating digital catastrophes.",
        "translation": "高管们必须代表股东的利益，提前预判数字灾难。"
    },
    {
        "id": "2007-T4-14",
        "year": 2007,
        "text": "Text 4",
        "word": "suggested",
        "category": "核心词汇",
        "noteTag": "★ 常见词 · 建议的/暗示的",
        "def": "建议的；暗示的",
        "sentence": "The <mark>suggested</mark> protocols were deemed too expensive by short-sighted financial officers.",
        "sentencePlain": "The suggested protocols were deemed too expensive by short-sighted financial officers.",
        "translation": "这些被建议的安全协议曾被目光短浅的财务主管认为开销过于昂贵。"
    },
    {
        "id": "2007-T4-15",
        "year": 2007,
        "text": "Text 4",
        "word": "mystery",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 谜团",
        "def": "谜团、难以理解的事物",
        "sentence": "How hackers infiltrated the secure databases remained a deeply disturbing <mark>mystery</mark>.",
        "sentencePlain": "How hackers infiltrated the secure databases remained a deeply disturbing mystery.",
        "translation": "黑客究竟是如何潜入安全数据库的，依然是一个令人深感不安的谜团。"
    },
    {
        "id": "2007-T4-16",
        "year": 2007,
        "text": "Text 4",
        "word": "dimmest",
        "category": "核心词汇",
        "noteTag": "★ 最高级引申搭配 · not have the dimmest idea",
        "def": "最微弱的、最暗淡的；最迟钝的",
        "sentence": "Many executives did not have the <mark>dimmest</mark> grasp of where sensitive consumer records were stored.",
        "sentencePlain": "Many executives did not have the dimmest grasp of where sensitive consumer records were stored.",
        "translation": "许多高管对自己公司敏感的客户记录究竟存放在何处甚至连最模糊的概念都没有。"
    },
    {
        "id": "2007-T4-17",
        "year": 2007,
        "text": "Text 4",
        "word": "likely",
        "category": "核心词汇",
        "noteTag": "★ 考研高频概率词",
        "def": "可能的",
        "sentence": "Unencrypted personal files are the most <mark>likely</mark> targets of sophisticated cyber criminals.",
        "sentencePlain": "Unencrypted personal files are the most likely targets of sophisticated cyber criminals.",
        "translation": "未经加密的个人文件是老练的网络犯罪分子最有可能盯上的目标。"
    },
    {
        "id": "2007-T4-18",
        "year": 2007,
        "text": "Text 4",
        "word": "more likely to",
        "category": "句型语法",
        "noteTag": "★ 考研经典比较句型 · 更有可能做",
        "def": "更有可能做某事",
        "sentence": "Companies with dedicated risk committees were far <mark>more likely to</mark> avert major security scandals.",
        "sentencePlain": "Companies with dedicated risk committees were far more likely to avert major security scandals.",
        "translation": "拥有专门风险委员会的公司更有可能避免重大安全丑闻。"
    },
    {
        "id": "2007-T4-19",
        "year": 2007,
        "text": "Text 4",
        "word": "get into",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 潜入/陷入",
        "def": "进入、陷入；对……产生兴趣",
        "sentence": "Intruders managed to <mark>get into</mark> the internal server by exploiting an unpatched software flaw.",
        "sentencePlain": "Intruders managed to get into the internal server by exploiting an unpatched software flaw.",
        "translation": "入侵者利用一个未打补丁的软件缺陷成功潜入了内部服务器。"
    },
    {
        "id": "2007-T4-20",
        "year": 2007,
        "text": "Text 4",
        "word": "state",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 状况/状态 (非国家)",
        "def": "状态、状况；国家；声明",
        "sentence": "The current chaotic <mark>state</mark> of corporate data governance demands federal legislative intervention.",
        "sentencePlain": "The current chaotic state of corporate data governance demands federal legislative intervention.",
        "translation": "企业数据治理目前这一混乱状况亟需联邦立法的介入。"
    },
    {
        "id": "2007-T4-21",
        "year": 2007,
        "text": "Text 4",
        "word": "affair",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 核心事务",
        "def": "事务、事情、事件",
        "sentence": "Cybersecurity is no longer a technical sidelight, but a central corporate <mark>affair</mark>.",
        "sentencePlain": "Cybersecurity is no longer a technical sidelight, but a central corporate affair.",
        "translation": "网络安全不再是一项次要的技术旁支，而是一项核心的企业事务。"
    },
    {
        "id": "2007-T4-22",
        "year": 2007,
        "text": "Text 4",
        "word": "encourage",
        "category": "核心词汇",
        "noteTag": "★ 核心动词 · 助长/促成",
        "def": "鼓励、促成、助长",
        "sentence": "Lax internal penalties only <mark>encourage</mark> negligent behavior among outsourced database administrators.",
        "sentencePlain": "Lax internal penalties only encourage negligent behavior among outsourced database administrators.",
        "translation": "宽松的内部惩处只会助长外包数据库管理员的玩忽职守行为。"
    },
    {
        "id": "2007-T4-23",
        "year": 2007,
        "text": "Text 4",
        "word": "astray",
        "category": "核心词汇",
        "noteTag": "★ 固定搭配 · go astray 走失/误入歧途",
        "def": "迷路的、走入歧途的",
        "sentence": "When sensitive backup tapes go <mark>astray</mark>, the damage to corporate integrity is incalculable.",
        "sentencePlain": "When sensitive backup tapes go astray, the damage to corporate integrity is incalculable.",
        "translation": "当敏感的备份磁带下落不明（走失）时，对企业信誉造成的损害是无法估量的。"
    },
    {
        "id": "2007-T4-24",
        "year": 2007,
        "text": "Text 4",
        "word": "overshadow",
        "category": "核心词汇",
        "noteTag": "★ 生动形象动词 · 使蒙上阴影",
        "def": "使黯然失色、给……蒙上阴影",
        "sentence": "The catastrophic breach threatened to <mark>overshadow</mark> all of the firm's recent commercial achievements.",
        "sentencePlain": "The catastrophic breach threatened to overshadow all of the firm's recent commercial achievements.",
        "translation": "这一灾难性的信息泄露事件有可能使该公司近期取得的所有商业成就蒙上阴影。"
    },
    {
        "id": "2007-T4-25",
        "year": 2007,
        "text": "Text 4",
        "word": "do the rounds",
        "category": "固定短语",
        "noteTag": "★ 地道表达 · 消息四处流传",
        "def": "四处流传、巡视、兜圈子",
        "sentence": "Rumors of unannounced data thefts began to <mark>do the rounds</mark> in financial markets.",
        "sentencePlain": "Rumors of unannounced data thefts began to do the rounds in financial markets.",
        "translation": "关于未公开数据被盗的谣言开始在金融市场上四处流传。"
    }
]
