# -*- coding: utf-8 -*-

cards_2008_t1 = [
    {
        "id": "2008-T1-01",
        "year": 2008,
        "text": "Text 1",
        "word": "catch up",
        "category": "固定短语",
        "noteTag": "★ 核心动词短语 · 赶上追赶",
        "def": "赶上、追赶",
        "sentence": "While still <mark>catching up</mark> to men in some spheres of modern life, women appear to be way ahead in at least one undesirable category.",
        "sentencePlain": "While still catching up to men in some spheres of modern life, women appear to be way ahead in at least one undesirable category.",
        "translation": "尽管在现代生活的某些领域，女性仍在努力追赶男性，但在至少一个令人不快的方面，女性似乎遥遥领先。"
    },
    {
        "id": "2008-T1-02",
        "year": 2008,
        "text": "Text 1",
        "word": "be way ahead",
        "category": "固定短语",
        "noteTag": "★ 口语高频短语 · 遥遥领先/远在前面",
        "def": "遥遥领先、远在……前面",
        "sentence": "While still catching up to men in some spheres of modern life, women appear to <mark>be way ahead</mark> in at least one undesirable category.",
        "sentencePlain": "While still catching up to men in some spheres of modern life, women appear to be way ahead in at least one undesirable category.",
        "translation": "尽管在现代生活的某些领域，女性仍在努力追赶男性，但在至少一个令人不快的方面，女性似乎遥遥领先。"
    },
    {
        "id": "2008-T1-03",
        "year": 2008,
        "text": "Text 1",
        "word": "undesirable",
        "category": "核心词汇",
        "noteTag": "★ 构词：un + desirable · 不受欢迎的/有害的",
        "def": "不受欢迎的、不良的、有害的",
        "sentence": "While still catching up to men in some spheres of modern life, women appear to be way ahead in at least one <mark>undesirable</mark> category.",
        "sentencePlain": "While still catching up to men in some spheres of modern life, women appear to be way ahead in at least one undesirable category.",
        "translation": "尽管在现代生活的某些领域，女性仍在努力追赶男性，但在至少一个令人不快的方面，女性似乎遥遥领先。"
    },
    {
        "id": "2008-T1-04",
        "year": 2008,
        "text": "Text 1",
        "word": "particularly",
        "category": "核心词汇",
        "noteTag": "★ 程度副词 · 特别是/尤其",
        "def": "特别是、尤其",
        "sentence": "\"Women are <mark>particularly</mark> susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-05",
        "year": 2008,
        "text": "Text 1",
        "word": "susceptible",
        "category": "核心词汇",
        "noteTag": "★ 考研超高频核心词 · 易受影响/易患病",
        "def": "易受影响的、易感的",
        "sentence": "\"Women are particularly <mark>susceptible</mark> to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-06",
        "year": 2008,
        "text": "Text 1",
        "word": "develop",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 患上疾病 (非发展)",
        "def": "逐渐患上；发展、开发",
        "sentence": "\"Women are particularly susceptible to <mark>developing</mark> depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-07",
        "year": 2008,
        "text": "Text 1",
        "word": "depression",
        "category": "核心词汇",
        "noteTag": "★ 核心心理医学词汇 · 抑郁症",
        "def": "抑郁症；萧条、沮丧",
        "sentence": "\"Women are particularly susceptible to developing <mark>depression</mark> and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-08",
        "year": 2008,
        "text": "Text 1",
        "word": "disorder",
        "category": "核心词汇",
        "noteTag": "★ 构词：dis + order · 紊乱失调",
        "def": "紊乱、失调、疾病；混乱",
        "sentence": "\"Women are particularly susceptible to developing depression and anxiety <mark>disorders</mark> in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-09",
        "year": 2008,
        "text": "Text 1",
        "word": "response",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 压力反应机制",
        "def": "反应、应对；应答",
        "sentence": "\"Women are particularly susceptible to developing depression and anxiety disorders in <mark>response</mark> to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "sentencePlain": "\"Women are particularly susceptible to developing depression and anxiety disorders in response to stress compared to men,\" according to Dr. Yehuda, chief psychiatrist at New York's Veteran's Administration Hospital.",
        "translation": "纽约退伍军人管理医院首席精神病医师耶胡达博士指出：“与男性相比，女性在应对压力时尤其容易患上抑郁症和焦虑症。”"
    },
    {
        "id": "2008-T1-10",
        "year": 2008,
        "text": "Text 1",
        "word": "cause",
        "category": "核心词汇",
        "noteTag": "★ 核心因果动词 · 引起导致",
        "def": "导致、引起；原因；事业",
        "sentence": "Studies of both animals and humans have shown that sex hormones somehow affect the stress response, <mark>causing</mark> females under stress to produce more of the trigger chemicals than do males under the same conditions.",
        "sentencePlain": "Studies of both animals and humans have shown that sex hormones somehow affect the stress response, causing females under stress to produce more of the trigger chemicals than do males under the same conditions.",
        "translation": "对动物和人类的研究均表明，性激素在某种程度上会影响压力反应，导致处于压力下的雌性比处于相同条件下的雄性产生更多的诱发化学物质。"
    },
    {
        "id": "2008-T1-11",
        "year": 2008,
        "text": "Text 1",
        "word": "chemical",
        "category": "核心词汇",
        "noteTag": "★ 核心科学名词 · 神经化学物质",
        "def": "化学物质；化学的",
        "sentence": "Studies of both animals and humans have shown that sex hormones somehow affect the stress response, causing females under stress to produce more of the trigger <mark>chemicals</mark> than do males under the same conditions.",
        "sentencePlain": "Studies of both animals and humans have shown that sex hormones somehow affect the stress response, causing females under stress to produce more of the trigger chemicals than do males under the same conditions.",
        "translation": "对动物和人类的研究均表明，性激素在某种程度上会影响压力反应，导致处于压力下的雌性比处于相同条件下的雄性产生更多的诱发化学物质。"
    },
    {
        "id": "2008-T1-12",
        "year": 2008,
        "text": "Text 1",
        "word": "reproductive",
        "category": "核心词汇",
        "noteTag": "★ 核心生理学生物词 · 生殖的",
        "def": "生殖的、繁殖的",
        "sentence": "In several of the studies, when stressed-out female rats had their ovaries (the female <mark>reproductive</mark> organs) removed, their chemical responses became equal to those of the males.",
        "sentencePlain": "In several of the studies, when stressed-out female rats had their ovaries (the female reproductive organs) removed, their chemical responses became equal to those of the males.",
        "translation": "在数项研究中，当承受压力的雌鼠被切除卵巢（女性生殖器官）后，它们的化学反应变得与雄鼠相同。"
    },
    {
        "id": "2008-T1-13",
        "year": 2008,
        "text": "Text 1",
        "word": "add to",
        "category": "固定短语",
        "noteTag": "★ 短语搭配 · 增添/加剧",
        "def": "增加、增添",
        "sentence": "<mark>Adding to</mark> a woman's increased dose of stress chemicals, are her increased \"opportunities\" for stress.",
        "sentencePlain": "Adding to a woman's increased dose of stress chemicals, are her increased \"opportunities\" for stress.",
        "translation": "加重女性体内压力化学物质剂量的，是她们增加的压力“机会”。"
    },
    {
        "id": "2008-T1-14",
        "year": 2008,
        "text": "Text 1",
        "word": "as well",
        "category": "固定短语",
        "noteTag": "★ 句末副词短语 · 也/同样",
        "def": "也、同样",
        "sentence": "\"It's not necessarily that women don't cope <mark>as well</mark>. It's just that they have so much more to cope with,\" says Dr. Yehuda.",
        "sentencePlain": "\"It's not necessarily that women don't cope as well. It's just that they have so much more to cope with,\" says Dr. Yehuda.",
        "translation": "耶胡达博士说：“这并不一定意味着女性应对压力的能力不如男性，只是她们需要应对的事情实在太多了。”"
    },
    {
        "id": "2008-T1-15",
        "year": 2008,
        "text": "Text 1",
        "word": "visibly",
        "category": "核心词汇",
        "noteTag": "★ 程度副词 · 明显地",
        "def": "明显地、看得见地",
        "sentence": "\"Their capacity for tolerating stress may even be greater than men's,\" she observes, \"it's just that they're dealing with so many more things that they become worn out from it more <mark>visibly</mark> and sooner.\"",
        "sentencePlain": "\"Their capacity for tolerating stress may even be greater than men's,\" she observes, \"it's just that they're dealing with so many more things that they become worn out from it more visibly and sooner.\"",
        "translation": "她观察道：“女性忍受压力的能力甚至可能比男性更强，只是因为她们处理的事情太多，以至于她们表现出的疲惫感更明显、也更快出现。”"
    },
    {
        "id": "2008-T1-16",
        "year": 2008,
        "text": "Text 1",
        "word": "random",
        "category": "核心词汇",
        "noteTag": "★ 核心统计词汇 · 随机的",
        "def": "随机的、任意的",
        "sentence": "Dr. Yehuda notes that a man's stress may tend to be triggered more by one-shot events, such as being combat-exposed or facing <mark>random</mark> violence.",
        "sentencePlain": "Dr. Yehuda notes that a man's stress may tend to be triggered more by one-shot events, such as being combat-exposed or facing random violence.",
        "translation": "耶胡达博士指出，男性的压力往往更多地由单发性事件触发，比如经历战斗或面对随机暴力。"
    },
    {
        "id": "2008-T1-17",
        "year": 2008,
        "text": "Text 1",
        "word": "degree",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 学位 (非度数/程度)",
        "def": "学位；程度、等级",
        "sentence": "Adeline Alvarez married at 18 and gave birth to a son, but was determined to finish college: \"I struggled a lot to get the college <mark>degree</mark>.\"",
        "sentencePlain": "Adeline Alvarez married at 18 and gave birth to a son, but was determined to finish college: \"I struggled a lot to get the college degree.\"",
        "translation": "阿德琳·阿尔瓦雷斯在18岁时结婚并生下一个儿子，但她决心完成大学学业：“为了拿到大学学位，我付出了极大的努力。”"
    },
    {
        "id": "2008-T1-18",
        "year": 2008,
        "text": "Text 1",
        "word": "paycheck",
        "category": "核心词汇",
        "noteTag": "★ 生活财务名词 · 薪水",
        "def": "工资、薪金",
        "sentence": "Later, her marriage ended and she became a single mother: \"I lived from <mark>paycheck</mark> to paycheck.\"",
        "sentencePlain": "Later, her marriage ended and she became a single mother: \"I lived from paycheck to paycheck.\"",
        "translation": "后来，她的婚姻破裂，她成了一位单身母亲：“我过着靠薪水维持生计、入不敷出的生活。”"
    },
    {
        "id": "2008-T1-19",
        "year": 2008,
        "text": "Text 1",
        "word": "wear (worn)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：wear的过去分词worn · 磨损/筋疲力尽",
        "def": "磨损、使筋疲力尽",
        "sentence": "\"Their capacity for tolerating stress may even be greater than men's; it's just that they're dealing with so many more things that they become <mark>worn</mark> out from it more visibly and sooner.\"",
        "sentencePlain": "\"Their capacity for tolerating stress may even be greater than men's; it's just that they're dealing with so many more things that they become worn out from it more visibly and sooner.\"",
        "translation": "“女性忍受压力的能力甚至可能比男性更强；只是她们要应对的事情太多，以至于她们更明显、更快地感到精疲力竭（worn 为 wear 过去分词）。”"
    },
    {
        "id": "2008-T1-20",
        "year": 2008,
        "text": "Text 1",
        "word": "nature",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 本质/性质",
        "def": "本质、性质；天性",
        "sentence": "The chronic <mark>nature</mark> of domestic and interpersonal stressors makes them far more difficult to endure than acute events.",
        "sentencePlain": "The chronic nature of domestic and interpersonal stressors makes them far more difficult to endure than acute events.",
        "translation": "家庭和人际压力源的长期性本质，使得它们比突发性事件要难以承受得多。"
    },
    {
        "id": "2008-T1-21",
        "year": 2008,
        "text": "Text 1",
        "word": "domestic",
        "category": "核心词汇",
        "noteTag": "★ 多义词 · 家庭家务的/本国的",
        "def": "家庭的、家务的；国内的",
        "sentence": "Women's stress comes more often from relationships: taking care of children, caring for aging parents, or managing <mark>domestic</mark> and marital burdens.",
        "sentencePlain": "Women's stress comes more often from relationships: taking care of children, caring for aging parents, or managing domestic and marital burdens.",
        "translation": "女性的压力更常来自人际关系：照顾孩子、赡养年迈的父母，或应对家庭及婚姻负担。"
    },
    {
        "id": "2008-T1-22",
        "year": 2008,
        "text": "Text 1",
        "word": "devastating",
        "category": "核心词汇",
        "noteTag": "★ 感情色彩强烈词 · 毁灭性的",
        "def": "毁灭性的、破坏性极大的",
        "sentence": "The wear-and-tear that comes from these longer relationships can be quite <mark>devastating</mark>.",
        "sentencePlain": "The wear-and-tear that comes from these longer relationships can be quite devastating.",
        "translation": "长久关系中所产生的身心损耗（wear-and-tear）可能是相当毁灭性的。"
    },
    {
        "id": "2008-T1-23",
        "year": 2008,
        "text": "Text 1",
        "word": "obligation",
        "category": "核心词汇",
        "noteTag": "★ 伦理法律词汇 · 责任义务",
        "def": "义务、责任",
        "sentence": "\"It's the hardest thing to take care of a teenager, have a job, pay the rent, pay the car payment, and meet every family <mark>obligation</mark>.\"",
        "sentencePlain": "\"It's the hardest thing to take care of a teenager, have a job, pay the rent, pay the car payment, and meet every family obligation.\"",
        "translation": "“一边照顾青春期的孩子、工作、交房租、付车贷，一边还要履行每一项家庭义务，这是最艰难的事情。”"
    },
    {
        "id": "2008-T1-24",
        "year": 2008,
        "text": "Text 1",
        "word": "break",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 喘息间歇/休息机会",
        "def": "休息、喘息机会；打破",
        "sentence": "\"I was living in so much frustration that that was my escape, to go to school and have a <mark>break</mark> to get ahead and do better.\"",
        "sentencePlain": "\"I was living in so much frustration that that was my escape, to go to school and have a break to get ahead and do better.\"",
        "translation": "“我当时生活在极大的挫败感中，上学成了我的避难所和喘息之机，让我能够出人头地、过得更好。”"
    },
    {
        "id": "2008-T1-25",
        "year": 2008,
        "text": "Text 1",
        "word": "inclination",
        "category": "核心词汇",
        "noteTag": "★ 核心心理词汇 · 天性倾向",
        "def": "倾向、意愿、偏好",
        "sentence": "Women often show a greater <mark>inclination</mark> to assume emotional and caregiving burdens within family relationships.",
        "sentencePlain": "Women often show a greater inclination to assume emotional and caregiving burdens within family relationships.",
        "translation": "在家庭关系中，女性往往表现出更大的倾向去承担情感与照料的重负。"
    },
    {
        "id": "2008-T1-26",
        "year": 2008,
        "text": "Text 1",
        "word": "biologically",
        "category": "核心词汇",
        "noteTag": "★ 学科副词 · 生物学生理上",
        "def": "生物学上、生理上",
        "sentence": "Studies indicate that females are <mark>biologically</mark> conditioned to release higher levels of stress-triggering hormones.",
        "sentencePlain": "Studies indicate that females are biologically conditioned to release higher levels of stress-triggering hormones.",
        "translation": "研究表明，雌性在生理生物学机制上更容易释放出更高水平的压力诱发激素。"
    },
    {
        "id": "2008-T1-27",
        "year": 2008,
        "text": "Text 1",
        "word": "be vulnerable to (susceptible)",
        "category": "固定短语",
        "noteTag": "★ 核心考点：等同于 be susceptible to · 易受伤害",
        "def": "易受……伤害的、对……脆弱的",
        "sentence": "Women <mark>are</mark> particularly <mark>vulnerable to</mark> developing depression and anxiety disorders when facing chronic domestic strain.",
        "sentencePlain": "Women are particularly vulnerable to developing depression and anxiety disorders when facing chronic domestic strain.",
        "translation": "在面对长期家庭压力时，女性尤其容易受到抑郁症和焦虑症的伤害（vulnerable 等同于 susceptible）。"
    },
    {
        "id": "2008-T1-28",
        "year": 2008,
        "text": "Text 1",
        "word": "cope with",
        "category": "固定短语",
        "noteTag": "★ 考研超高频核心短语 · 应付处理",
        "def": "应对、处理",
        "sentence": "\"It's not necessarily that women don't cope as well. It's just that they have so much more to <mark>cope with</mark>,\" says Dr. Yehuda.",
        "sentencePlain": "\"It's not necessarily that women don't cope as well. It's just that they have so much more to cope with,\" says Dr. Yehuda.",
        "translation": "耶胡达博士说：“这并不意味着女性应对能力差，只是她们需要去应对（cope with）的事情太多了。”"
    },
    {
        "id": "2008-T1-29",
        "year": 2008,
        "text": "Text 1",
        "word": "be capable of",
        "category": "固定短语",
        "noteTag": "★ 核心能力短语 · 有能力做某事",
        "def": "有能力做某事",
        "sentence": "Women <mark>are capable of</mark> tolerating substantial stress, but persistent cumulative burdens eventually wear them down.",
        "sentencePlain": "Women are capable of tolerating substantial stress, but persistent cumulative burdens eventually wear them down.",
        "translation": "女性完全有能力承受巨大的压力，但持续累积的负担最终会压垮她们。"
    },
    {
        "id": "2008-T1-30",
        "year": 2008,
        "text": "Text 1",
        "word": "trivial",
        "category": "核心词汇",
        "noteTag": "★ 核心考点形容词 · 琐碎微不足道",
        "def": "琐碎的、微不足道的",
        "sentence": "Unlike acute combat trauma, the domestic stressors women face are not <mark>trivial</mark>, but durable and frequent.",
        "sentencePlain": "Unlike acute combat trauma, the domestic stressors women face are not trivial, but durable and frequent.",
        "translation": "与战斗创伤不同，女性所面临的家庭压力绝非微不足道的琐事（not trivial），而是持久且频繁发生的。"
    },
    {
        "id": "2008-T1-31",
        "year": 2008,
        "text": "Text 1",
        "word": "barely",
        "category": "核心词汇",
        "noteTag": "★ 考研半否定副词 · 几乎不/勉强",
        "def": "仅仅、勉强、几乎不",
        "sentence": "The idiom \"I lived from paycheck to paycheck\" indicates that Alvarez's salary <mark>barely</mark> covered her basic household expenses.",
        "sentencePlain": "The idiom \"I lived from paycheck to paycheck\" indicates that Alvarez's salary barely covered her basic household expenses.",
        "translation": "习语“I lived from paycheck to paycheck”表明阿尔瓦雷斯的薪水仅仅勉强（barely）支撑起她的家庭基本开销。"
    }
]

cards_2008_t2 = [
    {
        "id": "2008-T2-01",
        "year": 2008,
        "text": "Text 2",
        "word": "straightforward",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 简单明了的",
        "def": "简单明了的、坦率的",
        "sentence": "It used to be so <mark>straightforward</mark>.",
        "sentencePlain": "It used to be so straightforward.",
        "translation": "过去，（学术出版的过程）曾是非常简单明了的。"
    },
    {
        "id": "2008-T2-02",
        "year": 2008,
        "text": "Text 2",
        "word": "remove A from B",
        "category": "固定短语",
        "noteTag": "★ 动词短语搭配 · 从……中剥离",
        "def": "把 A 从 B 中移除、除掉",
        "sentence": "A journal editor would then <mark>remove</mark> the authors' names and affiliations <mark>from</mark> the paper and send it to their peers for review.",
        "sentencePlain": "A journal editor would then remove the authors' names and affiliations from the paper and send it to their peers for review.",
        "translation": "随后期刊编辑会从论文中删掉作者姓名及其所属机构，并将其发送给同行进行评审。"
    },
    {
        "id": "2008-T2-03",
        "year": 2008,
        "text": "Text 2",
        "word": "affiliation",
        "category": "核心词汇",
        "noteTag": "★ 学术论文核心词汇 · 机构从属",
        "def": "所属机构、隶属关系",
        "sentence": "A journal editor would then remove the authors' names and <mark>affiliations</mark> from the paper and send it to their peers for review.",
        "sentencePlain": "A journal editor would then remove the authors' names and affiliations from the paper and send it to their peers for review.",
        "translation": "随后期刊编辑会从论文中删掉作者姓名及其所属机构，并将其发送给同行进行评审。"
    },
    {
        "id": "2008-T2-04",
        "year": 2008,
        "text": "Text 2",
        "word": "peer",
        "category": "熟词生义",
        "noteTag": "★ 学术阅读必考 · 同行评审 (peer review)",
        "def": "同行、同龄人",
        "sentence": "A journal editor would then remove the authors' names and affiliations from the paper and send it to their <mark>peers</mark> for review.",
        "sentencePlain": "A journal editor would then remove the authors' names and affiliations from the paper and send it to their peers for review.",
        "translation": "随后期刊编辑会从论文中删掉作者姓名及其所属机构，并将其发送给同行（peers）进行评审。"
    },
    {
        "id": "2008-T2-05",
        "year": 2008,
        "text": "Text 2",
        "word": "decline",
        "category": "熟词生义",
        "noteTag": "★ 核心动词 · 拒绝发表 (非下降)",
        "def": "谢绝、拒绝；下降、衰败",
        "sentence": "Depending on the comments received, the editor would accept the paper for publication or <mark>decline</mark> it.",
        "sentencePlain": "Depending on the comments received, the editor would accept the paper for publication or decline it.",
        "translation": "根据收到的评审意见，编辑会决定接受发表该论文或是予以拒绝。"
    },
    {
        "id": "2008-T2-06",
        "year": 2008,
        "text": "Text 2",
        "word": "rest with",
        "category": "固定短语",
        "noteTag": "★ 核心短语 · 责任在于/取决于",
        "def": "归属于……、在于……",
        "sentence": "Copyright <mark>rested with</mark> the journal publisher, and researchers seeking knowledge of the results would have to subscribe to the journal.",
        "sentencePlain": "Copyright rested with the journal publisher, and researchers seeking knowledge of the results would have to subscribe to the journal.",
        "translation": "论文版权归期刊出版商所有（rested with），希望了解研究成果的研究人员必须订阅该期刊。"
    },
    {
        "id": "2008-T2-07",
        "year": 2008,
        "text": "Text 2",
        "word": "no longer (暗含时间轴对比)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：暗含时间轴新旧对比",
        "def": "不再、已不复存在",
        "sentence": "<mark>No longer</mark>.",
        "sentencePlain": "No longer.",
        "translation": "如今这种局面已不复存在（★ 核心考点：暗含时间轴新旧对比，引出学术出版重大变革）。"
    },
    {
        "id": "2008-T2-08",
        "year": 2008,
        "text": "Text 2",
        "word": "fund",
        "category": "核心词汇",
        "noteTag": "★ 核心学术经济词汇 · 资助",
        "def": "为……提供资金、资助；基金",
        "sentence": "The Internet – and pressure from <mark>funding</mark> agencies, who are questioning why commercial publishers are making money from government-funded research – is changing everything.",
        "sentencePlain": "The Internet – and pressure from funding agencies, who are questioning why commercial publishers are making money from government-funded research – is changing everything.",
        "translation": "互联网——以及来自科研资助机构的压力（这些机构开始质疑为什么商业出版商能从政府资助的研究中牟利）——正在改变一切。"
    },
    {
        "id": "2008-T2-09",
        "year": 2008,
        "text": "Text 2",
        "word": "publication",
        "category": "核心词汇",
        "noteTag": "★ 学术出版核心名词",
        "def": "出版、发表；出版物",
        "sentence": "Depending on the comments received, the editor would accept the paper for <mark>publication</mark> or decline it.",
        "sentencePlain": "Depending on the comments received, the editor would accept the paper for publication or decline it.",
        "translation": "根据收到的评审意见，编辑会决定接受发表该论文或是予以拒绝。"
    },
    {
        "id": "2008-T2-10",
        "year": 2008,
        "text": "Text 2",
        "word": "publisher",
        "category": "核心词汇",
        "noteTag": "★ 商业出版主体名词",
        "def": "出版商、出版社",
        "sentence": "Copyright rested with the journal <mark>publisher</mark>, and researchers seeking knowledge of the results would have to subscribe to the journal.",
        "sentencePlain": "Copyright rested with the journal publisher, and researchers seeking knowledge of the results would have to subscribe to the journal.",
        "translation": "论文版权归期刊出版商所有，希望了解研究成果的研究人员必须向其付费订阅。"
    },
    {
        "id": "2008-T2-11",
        "year": 2008,
        "text": "Text 2",
        "word": "access",
        "category": "核心词汇",
        "noteTag": "★ 核心主题词 · 开放获取 (open access)",
        "def": "获取、进入；使用权",
        "sentence": "...who are questioning why commercial publishers are making money from government-funded research by restricting <mark>access</mark> to it...",
        "sentencePlain": "...who are questioning why commercial publishers are making money from government-funded research by restricting access to it...",
        "translation": "……他们质疑商业出版商为何能通过限制对政府资助研究的查阅获取（access）来获取暴利……"
    },
    {
        "id": "2008-T2-12",
        "year": 2008,
        "text": "Text 2",
        "word": "issue",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 发布公布 (非问题/期号)",
        "def": "发布、发行；期号、议题",
        "sentence": "The Organization for Economic Co-operation and Development (OECD) has just <mark>issued</mark> a report describing the far-reaching consequences of this.",
        "sentencePlain": "The Organization for Economic Co-operation and Development (OECD) has just issued a report describing the far-reaching consequences of this.",
        "translation": "经济合作与发展组织（OECD）刚刚发布了一份报告，阐述了这一变革带来的深远影响。"
    },
    {
        "id": "2008-T2-13",
        "year": 2008,
        "text": "Text 2",
        "word": "heavy",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 令人心情沉重的读物",
        "def": "沉重的、沉闷难懂的",
        "sentence": "The report, by John Houghton of Victoria University in Australia and Graham Vickery of the OECD, makes <mark>heavy</mark> reading for publishers who have, so far, made handsome profits.",
        "sentencePlain": "The report, by John Houghton of Victoria University in Australia and Graham Vickery of the OECD, makes heavy reading for publishers who have, so far, made handsome profits.",
        "translation": "该报告由澳大利亚维多利亚大学的约翰·霍顿和OECD的格雷厄姆·维克里撰写，对迄今为止大赚其钱的出版商来说是令人心情沉重的读物。"
    },
    {
        "id": "2008-T2-14",
        "year": 2008,
        "text": "Text 2",
        "word": "in that",
        "category": "句型语法",
        "noteTag": "★ 核心考点：原因连词，等价于 because",
        "def": "在于、因为",
        "sentence": "The first model is the 'Big Deal', <mark>in that</mark> institutional subscribers pay for access to a large collection of online journals through site-licensing agreements.",
        "sentencePlain": "The first model is the 'Big Deal', in that institutional subscribers pay for access to a large collection of online journals through site-licensing agreements.",
        "translation": "第一种模式是“大交易”，原因在于（in that，等价于 because）机构订户通过站点许可协议付费以获取大量在线期刊的查阅权。"
    },
    {
        "id": "2008-T2-15",
        "year": 2008,
        "text": "Text 2",
        "word": "significant",
        "category": "核心词汇",
        "noteTag": "★ 考研高频评价形容词 · 重大的",
        "def": "重大的、显著的、意味深长的",
        "sentence": "The OECD report demonstrates that open access will yield a <mark>significant</mark> increase in the return on public investment in scientific research.",
        "sentencePlain": "The OECD report demonstrates that open access will yield a significant increase in the return on public investment in scientific research.",
        "translation": "OECD报告表明，开放存取将使公众在科学研究上的投资回报获得显著提升。"
    },
    {
        "id": "2008-T2-16",
        "year": 2008,
        "text": "Text 2",
        "word": "far-reaching",
        "category": "核心词汇",
        "noteTag": "★ 复合形容词 · 影响深远",
        "def": "影响深远的、波及广泛的",
        "sentence": "The OECD has just issued a report describing the <mark>far-reaching</mark> consequences of this.",
        "sentencePlain": "The OECD has just issued a report describing the far-reaching consequences of this.",
        "translation": "经济合作与发展组织（OECD）刚刚发布了一份报告，描述了这一变革带来的深远影响。"
    },
    {
        "id": "2008-T2-17",
        "year": 2008,
        "text": "Text 2",
        "word": "so far",
        "category": "固定短语",
        "noteTag": "★ 时态标志词 · 迄今为止",
        "def": "迄今为止；到目前为止",
        "sentence": "The report makes heavy reading for publishers who have, <mark>so far</mark>, made handsome profits.",
        "sentencePlain": "The report makes heavy reading for publishers who have, so far, made handsome profits.",
        "translation": "对迄今为止（so far）大赚其钱的出版商来说，这份报告是令人沉重的沉重打击。"
    },
    {
        "id": "2008-T2-18",
        "year": 2008,
        "text": "Text 2",
        "word": "handsome",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：熟词僻义 · 丰厚可观的 (handsome profits 非英俊)",
        "def": "可观的、数量庞大的",
        "sentence": "The report makes heavy reading for publishers who have, so far, made <mark>handsome</mark> profits.",
        "sentencePlain": "The report makes heavy reading for publishers who have, so far, made handsome profits.",
        "translation": "这份报告对迄今为止获取了丰厚利润（handsome profits，熟词僻义）的出版商来说是一份沉重的读物。"
    },
    {
        "id": "2008-T2-19",
        "year": 2008,
        "text": "Text 2",
        "word": "endeavor",
        "category": "核心词汇",
        "noteTag": "★ 学术核心名词 · 崇高事业",
        "def": "努力、艰苦事业",
        "sentence": "It signals a change in what has, until now, been a key element of scientific <mark>endeavor</mark>.",
        "sentencePlain": "It signals a change in what has, until now, been a key element of scientific endeavor.",
        "translation": "它标志着迄今为止作为科学探索事业（scientific endeavor）关键要素的模式发生了转变。"
    },
    {
        "id": "2008-T2-20",
        "year": 2008,
        "text": "Text 2",
        "word": "go further",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 更进一步",
        "def": "更进一步、走得更远",
        "sentence": "But it <mark>goes further</mark> than that: it signals a change in what has, until now, been a key element of scientific endeavor.",
        "sentencePlain": "But it goes further than that: it signals a change in what has, until now, been a key element of scientific endeavor.",
        "translation": "但报告的意义更进一步（goes further than that）：它标志着科学事业核心要素的深刻变革。"
    },
    {
        "id": "2008-T2-21",
        "year": 2008,
        "text": "Text 2",
        "word": "ready",
        "category": "核心词汇",
        "noteTag": "★ 熟词生义 · 现成便捷的",
        "def": "现成的、便捷的；准备好的",
        "sentence": "The Internet is making access to scientific results a <mark>ready</mark> reality for researchers worldwide.",
        "sentencePlain": "The Internet is making access to scientific results a ready reality for researchers worldwide.",
        "translation": "互联网正使全球研究人员便捷获取科学成果成为触手可及的现实。"
    },
    {
        "id": "2008-T2-22",
        "year": 2008,
        "text": "Text 2",
        "word": "identify",
        "category": "核心词汇",
        "noteTag": "★ 核心动词 · 辨明识别",
        "def": "识别、认出、确认",
        "sentence": "The OECD report <mark>identifies</mark> three main emerging business models for scholarly publishing.",
        "sentencePlain": "The OECD report identifies three main emerging business models for scholarly publishing.",
        "translation": "OECD报告指出了（identifies）学术出版领域正在涌现的三种主要商业模式。"
    },
    {
        "id": "2008-T2-23",
        "year": 2008,
        "text": "Text 2",
        "word": "pay for",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 为……买单",
        "def": "为……付钱；付出代价",
        "sentence": "In open-access publishing, the author or their institution <mark>pays for</mark> the paper to be published, allowing free access to all readers.",
        "sentencePlain": "In open-access publishing, the author or their institution pays for the paper to be published, allowing free access to all readers.",
        "translation": "在开放存取出版中，由作者或其所在机构为论文出版付费（pays for），从而允许所有读者免费查阅。"
    },
    {
        "id": "2008-T2-24",
        "year": 2008,
        "text": "Text 2",
        "word": "deal",
        "category": "熟词生义",
        "noteTag": "★ 商业谈判语境 · 协议交易",
        "def": "协议、交易；待遇",
        "sentence": "The first emerging model is the so-called 'Big <mark>Deal</mark>', in which institutional subscribers pay for access to a collection of online journals.",
        "sentencePlain": "The first emerging model is the so-called 'Big Deal', in which institutional subscribers pay for access to a collection of online journals.",
        "translation": "第一种新兴模式是所谓的“大交易（Big Deal）”，即机构订阅者付费购买对一系列在线期刊的访问权。"
    },
    {
        "id": "2008-T2-25",
        "year": 2008,
        "text": "Text 2",
        "word": "supported by (= depend on)",
        "category": "固定短语",
        "noteTag": "★ 核心考点：等同于 depend on 依赖于",
        "def": "由……所支撑；依赖于",
        "sentence": "The third model is open-access archives, <mark>supported by</mark> organizations such as universities or international laboratories.",
        "sentencePlain": "The third model is open-access archives, supported by organizations such as universities or international laboratories.",
        "translation": "第三种模式是由大学或国际实验室等机构所支持/依赖（supported by，批注：= depend on）的开放存取知识档案库。"
    },
    {
        "id": "2008-T2-26",
        "year": 2008,
        "text": "Text 2",
        "word": "where (非限制性定语从句)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：关系副词引导非限制性定从 (相当于 in which)",
        "def": "在那里",
        "sentence": "The third model is open-access archives, <mark>where</mark> organizations such as universities host and maintain institutional repositories.",
        "sentencePlain": "The third model is open-access archives, where organizations such as universities host and maintain institutional repositories.",
        "translation": "第三种模式是开放存取档案库，在这些档案库中（where 引导非限制性定语从句），大学等机构托管并维护机构知识库。"
    },
    {
        "id": "2008-T2-27",
        "year": 2008,
        "text": "Text 2",
        "word": "repository",
        "category": "核心词汇",
        "noteTag": "★ 科技学术名词 · 知识档案库",
        "def": "知识库、档案库、储藏室",
        "sentence": "In open-access archives, organizations such as universities support institutional <mark>repositories</mark> where research papers are freely stored and accessed.",
        "sentencePlain": "In open-access archives, organizations such as universities support institutional repositories where research papers are freely stored and accessed.",
        "translation": "在开放存取档案库中，大学等机构支持建立机构知识库（repositories），研究论文在其中得以免费存储并供人查阅。"
    }
]
