# -*- coding: utf-8 -*-

cards_2009_t1 = [
    {
        "id": "2009-T1-01",
        "year": 2009,
        "text": "Text 1",
        "word": "mindlessly",
        "category": "核心词汇",
        "noteTag": "★ 构词：mind + less + ly · 漫不经心地",
        "def": "漫不经心地、不假思索地",
        "sentence": "We reach for habit <mark>mindlessly</mark>, setting our brains on auto-pilot and relaxing into routine.",
        "sentencePlain": "We reach for habit mindlessly, setting our brains on auto-pilot and relaxing into routine.",
        "translation": "我们不假思索地依赖习惯，让大脑进入自动巡航状态，放松地沉浸在常规惯例中。"
    },
    {
        "id": "2009-T1-02",
        "year": 2009,
        "text": "Text 1",
        "word": "pilot",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 自动巡航 (auto-pilot)",
        "def": "自动驾驶、飞行员；试点",
        "sentence": "Modern life pushes human consciousness onto an unthinking auto-<mark>pilot</mark>.",
        "sentencePlain": "Modern life pushes human consciousness onto an unthinking auto-pilot.",
        "translation": "现代生活把人类的清醒意识推向了一种未经深思的自动驾驶状态。"
    },
    {
        "id": "2009-T1-03",
        "year": 2009,
        "text": "Text 1",
        "word": "unreflecting",
        "category": "核心词汇",
        "noteTag": "★ 构词：un + reflect + ing · 缺乏反思的",
        "def": "缺乏深思的、未经反思的",
        "sentence": "We slip into <mark>unreflecting</mark> herd behavior without questioning daily assumptions.",
        "sentencePlain": "We slip into unreflecting herd behavior without questioning daily assumptions.",
        "translation": "我们陷入未经反省的羊群随大流行为中，却从不对日常假设提出质疑。"
    },
    {
        "id": "2009-T1-04",
        "year": 2009,
        "text": "Text 1",
        "word": "herd",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 羊群从众心理",
        "def": "兽群、大众人群；成群结队",
        "sentence": "It is comforting to follow the <mark>herd</mark>, but it ultimately deadens inventive thinking.",
        "sentencePlain": "It is comforting to follow the herd, but it ultimately deadens inventive thinking.",
        "translation": "跟随大众羊群随波逐流固然令人感到惬意，但它最终会扼杀创造性思维。"
    },
    {
        "id": "2009-T1-05",
        "year": 2009,
        "text": "Text 1",
        "word": "rule",
        "category": "熟词生义",
        "noteTag": "★ 动词用法 · 支配主宰",
        "def": "支配、统治；规则",
        "sentence": "Ingrained behavioral patterns <mark>rule</mark> our working hours far more than conscious choices do.",
        "sentencePlain": "Ingrained behavioral patterns rule our working hours far more than conscious choices do.",
        "translation": "根深蒂固的行为模式对我们工作时间的支配程度，远甚于清醒的有意识抉择。"
    },
    {
        "id": "2009-T1-06",
        "year": 2009,
        "text": "Text 1",
        "word": "creatures",
        "category": "熟词生义",
        "noteTag": "★ 固定短语 · creatures of habit 习惯的奴隶",
        "def": "凡人、生灵",
        "sentence": "Humans are fundamentally <mark>creatures</mark> of habit, craving predictability in their environments.",
        "sentencePlain": "Humans are fundamentally creatures of habit, craving predictability in their environments.",
        "translation": "人类从本质上而言都是习惯的奴仆（习惯的生灵），渴望所处环境的可预测性。"
    },
    {
        "id": "2009-T1-07",
        "year": 2009,
        "text": "Text 1",
        "word": "instead",
        "category": "核心词汇",
        "noteTag": "★ 考研核心转折副词 · 相反",
        "def": "相反、代替",
        "sentence": "Rather than wrestling with fresh problems, our minds <mark>instead</mark> seize on prepackaged solutions.",
        "sentencePlain": "Rather than wrestling with fresh problems, our minds instead seize on prepackaged solutions.",
        "translation": "我们的头脑并不去努力探究新问题，相反却紧紧抓住了现成的套路化解决方案。"
    },
    {
        "id": "2009-T1-08",
        "year": 2009,
        "text": "Text 1",
        "word": "rather than (引导名词短语)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：引导名词短语对比 · 而不是",
        "def": "而不是",
        "sentence": "We prioritize mental ease <mark>rather than</mark> deliberate intellectual challenge.",
        "sentencePlain": "We prioritize mental ease rather than deliberate intellectual challenge.",
        "translation": "我们优先追求心智上的安逸，而不是（引导名词短语）刻意的智力挑战。"
    },
    {
        "id": "2009-T1-09",
        "year": 2009,
        "text": "Text 1",
        "word": "dismiss",
        "category": "熟词生义",
        "noteTag": "★ 核心态度动词 · 摒弃/不屑一顾",
        "def": "不予考虑、摒弃；解雇",
        "sentence": "Too many adults <mark>dismiss</mark> childlike wonder as an inefficient waste of time.",
        "sentencePlain": "Too many adults dismiss childlike wonder as an inefficient waste of time.",
        "translation": "太多成年人将孩童般的好奇惊叹视作低效的浪费时间而不予理睬。"
    },
    {
        "id": "2009-T1-10",
        "year": 2009,
        "text": "Text 1",
        "word": "bother",
        "category": "核心词汇",
        "noteTag": "★ 否定结构搭配 · not bother to do 懒得费心",
        "def": "费心、操心；烦扰",
        "sentence": "When paths are well-worn, our neurons don't even <mark>bother</mark> to fire vigorously.",
        "sentencePlain": "When paths are well-worn, our neurons don't even bother to fire vigorously.",
        "translation": "当神经通路已经陈旧熟练时，我们的神经元甚至都懒得费心去剧烈放电。"
    },
    {
        "id": "2009-T1-11",
        "year": 2009,
        "text": "Text 1",
        "word": "wear into",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 磨出固定深痕",
        "def": "磨蚀成、形成深痕",
        "sentence": "Everyday habits slowly <mark>wear</mark> deep grooves <mark>into</mark> the neural architecture of the brain.",
        "sentencePlain": "Everyday habits slowly wear deep grooves into the neural architecture of the brain.",
        "translation": "日常习惯慢慢在大脑的神经结构中磨出深深的沟壑（固定路径）。"
    },
    {
        "id": "2009-T1-12",
        "year": 2009,
        "text": "Text 1",
        "word": "fascination",
        "category": "核心词汇",
        "noteTag": "★ 感情色彩名词 · 着迷入神",
        "def": "着迷、魅力、入迷",
        "sentence": "Children view ordinary surroundings with intense <mark>fascination</mark> and pure curiosity.",
        "sentencePlain": "Children view ordinary surroundings with intense fascination and pure curiosity.",
        "translation": "孩子们带着极大的入迷与纯粹的好奇心来观察日常周围的事物。"
    },
    {
        "id": "2009-T1-13",
        "year": 2009,
        "text": "Text 1",
        "word": "wonder",
        "category": "核心词汇",
        "noteTag": "★ 核心名词与动词 · 惊奇之感",
        "def": "惊奇、奇迹；想知道",
        "sentence": "To rekindle original creativity, one must recover a sense of childlike <mark>wonder</mark>.",
        "sentencePlain": "To rekindle original creativity, one must recover a sense of childlike wonder.",
        "translation": "要重新点燃原创的创造力，必须找回孩提时代的那份惊奇之感。"
    },
    {
        "id": "2009-T1-14",
        "year": 2009,
        "text": "Text 1",
        "word": "bypass",
        "category": "核心词汇",
        "noteTag": "★ 构词：by + pass · 避开绕过",
        "def": "绕过、避开",
        "sentence": "Innovative thinkers deliberately choose unusual routines to <mark>bypass</mark> conventional mental ruts.",
        "sentencePlain": "Innovative thinkers deliberately choose unusual routines to bypass conventional mental ruts.",
        "translation": "具有创新精神的思考者故意选择不同寻常的惯例，以避开传统的心智车辙。"
    },
    {
        "id": "2009-T1-15",
        "year": 2009,
        "text": "Text 1",
        "word": "foster",
        "category": "核心词汇",
        "noteTag": "★ 核心褒义动词 · 培养助长",
        "def": "培养、促进、收养",
        "sentence": "Intentionally disrupting daily customs helps <mark>foster</mark> novel neural pathways.",
        "sentencePlain": "Intentionally disrupting daily customs helps foster novel neural pathways.",
        "translation": "有意识地打破日常惯例有助于培育全新的神经通路。"
    },
    {
        "id": "2009-T1-16",
        "year": 2009,
        "text": "Text 1",
        "word": "be born with",
        "category": "固定短语",
        "noteTag": "★ 固定短语搭配 · 生来具有",
        "def": "天生具有……",
        "sentence": "Everyone <mark>is born with</mark> an innate appetite for exploration and creative discovery.",
        "sentencePlain": "Everyone is born with an innate appetite for exploration and creative discovery.",
        "translation": "人人生来就对探索和创造性发现怀有一种天生的渴望。"
    },
    {
        "id": "2009-T1-17",
        "year": 2009,
        "text": "Text 1",
        "word": "approach",
        "category": "熟词生义",
        "noteTag": "★ 考研超高频核心词 · 解决方案/方法",
        "def": "方法、途径；接近",
        "sentence": "Solving unprecedented dilemmas requires an entirely unprecedented cognitive <mark>approach</mark>.",
        "sentencePlain": "Solving unprecedented dilemmas requires an entirely unprecedented cognitive approach.",
        "translation": "解决前所未有的困境需要一种完全前所未有的认知方法。"
    },
    {
        "id": "2009-T1-18",
        "year": 2009,
        "text": "Text 1",
        "word": "perpetuate",
        "category": "核心词汇",
        "noteTag": "★ 考研高阶动词 · 使永存持续",
        "def": "使永存、使持续存在",
        "sentence": "Mindless repetitive tasks merely <mark>perpetuate</mark> outdated organizational dogma.",
        "sentencePlain": "Mindless repetitive tasks merely perpetuate outdated organizational dogma.",
        "translation": "漫不经心的重复性任务只会让过时的组织教条持续存在。"
    },
    {
        "id": "2009-T1-19",
        "year": 2009,
        "text": "Text 1",
        "word": "commonness",
        "category": "核心词汇",
        "noteTag": "★ 构词：common + ness · 司空见惯",
        "def": "平凡、普通、司空见惯",
        "sentence": "The sheer <mark>commonness</mark> of daily rituals blinds us to alternative perspectives.",
        "sentencePlain": "The sheer commonness of daily rituals blinds us to alternative perspectives.",
        "translation": "日常仪式的司空见惯彻底蒙蔽了我们的双眼，让我们看不到其他的视角。"
    },
    {
        "id": "2009-T1-20",
        "year": 2009,
        "text": "Text 1",
        "word": "ruts",
        "category": "熟词生义",
        "noteTag": "★ 形象隐喻 · 陷入成规陈套 (in a rut)",
        "def": "车辙、刻板成规",
        "sentence": "Routine easily degenerates into narrow mental <mark>ruts</mark> that stifle genuine insight.",
        "sentencePlain": "Routine easily degenerates into narrow mental ruts that stifle genuine insight.",
        "translation": "惯例很容易退化为狭隘的心智车辙（刻板陈规），扼杀真正的真知灼见。"
    },
    {
        "id": "2009-T1-21",
        "year": 2009,
        "text": "Text 1",
        "word": "work through",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 克服攻克",
        "def": "克服、理清、逐步解决",
        "sentence": "Creative people are willing to <mark>work through</mark> the initial discomfort of novelty.",
        "sentencePlain": "Creative people are willing to work through the initial discomfort of novelty.",
        "translation": "具备创造力的人愿意逐步克服面对新颖事物时最初产生的不适感。"
    },
    {
        "id": "2009-T1-22",
        "year": 2009,
        "text": "Text 1",
        "word": "kill off",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 扼杀消灭",
        "def": "彻底扼杀、消灭",
        "sentence": "Passive conformity can ruthlessly <mark>kill off</mark> our natural impulse toward inquiry.",
        "sentencePlain": "Passive conformity can ruthlessly kill off our natural impulse toward inquiry.",
        "translation": "消极的顺从随大流会无情地扼杀我们探究未知的天然冲动。"
    },
    {
        "id": "2009-T1-23",
        "year": 2009,
        "text": "Text 1",
        "word": "familiar",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 熟悉的事物",
        "def": "熟悉的、熟知的",
        "sentence": "Clinging to the <mark>familiar</mark> prevents us from venturing into intellectually fruitful territory.",
        "sentencePlain": "Clinging to the familiar prevents us from venturing into intellectually fruitful territory.",
        "translation": "紧抱熟悉之物不放阻碍了我们涉足智力上硕果累累的新天地。"
    },
    {
        "id": "2009-T1-24",
        "year": 2009,
        "text": "Text 1",
        "word": "mechanical",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 机械呆板/不经思考",
        "def": "机械的、呆板的、无意识的",
        "sentence": "Many of our daily workplace choices are entirely <mark>mechanical</mark> rather than contemplative.",
        "sentencePlain": "Many of our daily workplace choices are entirely mechanical rather than contemplative.",
        "translation": "我们职场中的许多日常抉择完全是机械呆板的，而非经过深思熟虑的。"
    },
    {
        "id": "2009-T1-25",
        "year": 2009,
        "text": "Text 1",
        "word": "be characterized by",
        "category": "固定短语",
        "noteTag": "★ 考研学术论述标志短语 · 以……为特征",
        "def": "以……为特征/特色",
        "sentence": "Truly creative minds <mark>are characterized by</mark> a restless refusal to accept the status quo.",
        "sentencePlain": "Truly creative minds are characterized by a restless refusal to accept the status quo.",
        "translation": "真正具有创造力的心智以对现状永不满足的拒绝妥协为显著特征。"
    },
    {
        "id": "2009-T1-26",
        "year": 2009,
        "text": "Text 1",
        "word": "curiosity",
        "category": "核心词汇",
        "noteTag": "★ 心理核心词汇 · 好奇求知欲",
        "def": "好奇心、求知欲",
        "sentence": "Intellectual <mark>curiosity</mark> acts as a vital protective shield against cognitive stagnation.",
        "sentencePlain": "Intellectual curiosity acts as a vital protective shield against cognitive stagnation.",
        "translation": "求知的好奇心是抵御认知僵化停滞的重要盾牌。"
    },
    {
        "id": "2009-T1-27",
        "year": 2009,
        "text": "Text 1",
        "word": "creative",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 创造性的",
        "def": "有创造力的、创新的",
        "sentence": "Discarding rigid preconceptions is the first essential step toward <mark>creative</mark> thinking.",
        "sentencePlain": "Discarding rigid preconceptions is the first essential step toward creative thinking.",
        "translation": "抛弃死板的预设立场是迈向创造性思维的第一项核心步骤。"
    },
    {
        "id": "2009-T1-28",
        "year": 2009,
        "text": "Text 1",
        "word": "suggest",
        "category": "熟词生义",
        "noteTag": "★ 学术论文高频 · 表明显示 (非建议)",
        "def": "表明、显示；暗示",
        "sentence": "Neuroscientific experiments <mark>suggest</mark> that breaking routines stimulates neurogenesis.",
        "sentencePlain": "Neuroscientific experiments suggest that breaking routines stimulates neurogenesis.",
        "translation": "神经科学实验表明，打破日常常规能够刺激神经元新生。"
    }
]

cards_2009_t2 = [
    {
        "id": "2009-T2-01",
        "year": 2009,
        "text": "Text 2",
        "word": "shell out",
        "category": "固定短语",
        "noteTag": "★ 地道俚语搭配 · 掏腰包/支付大笔钱",
        "def": "支付大笔款项、掏腰包",
        "sentence": "Enthusiastic consumers willingly <mark>shell out</mark> hundreds of dollars for commercial DNA testing kits.",
        "sentencePlain": "Enthusiastic consumers willingly shell out hundreds of dollars for commercial DNA testing kits.",
        "translation": "热切的消费者心甘情愿地掏出数百美元购买商业DNA基因检测盒。"
    },
    {
        "id": "2009-T2-02",
        "year": 2009,
        "text": "Text 2",
        "word": "drugstore",
        "category": "核心词汇",
        "noteTag": "★ 生活商业名词 · 药房杂货店",
        "def": "药房、杂货药店",
        "sentence": "Over-the-counter kits displayed in the local <mark>drugstore</mark> made genetic genealogy an impulse purchase.",
        "sentencePlain": "Over-the-counter kits displayed in the local drugstore made genetic genealogy an impulse purchase.",
        "translation": "本地药店陈列的非处方检测盒让基因家谱测验变成了一种冲动消费。"
    },
    {
        "id": "2009-T2-03",
        "year": 2009,
        "text": "Text 2",
        "word": "chief",
        "category": "熟词生义",
        "noteTag": "★ 形容词用法 · 主要的/首要的",
        "def": "主要的、首要的；首领",
        "sentence": "The <mark>chief</mark> attraction of genetic ancestry testing lies in its promise of discovering ancient lineages.",
        "sentencePlain": "The chief attraction of genetic ancestry testing lies in its promise of discovering ancient lineages.",
        "translation": "基因寻根测验的主要吸引力在于其许诺能探寻古老血统。"
    },
    {
        "id": "2009-T2-04",
        "year": 2009,
        "text": "Text 2",
        "word": "paternal",
        "category": "核心词汇",
        "noteTag": "★ 词根：pater(父) · 父系的",
        "def": "父亲的、父系的",
        "sentence": "Y-chromosome analyses trace an unbroken line of <mark>paternal</mark> ancestry through generations.",
        "sentencePlain": "Y-chromosome analyses trace an unbroken line of paternal ancestry through generations.",
        "translation": "Y染色体分析可以世世代代追踪一条不间断的父系祖先血统。"
    },
    {
        "id": "2009-T2-05",
        "year": 2009,
        "text": "Text 2",
        "word": "adopted",
        "category": "核心词汇",
        "noteTag": "★ 核心词汇 · 被领养的",
        "def": "被领养的、收养的；被采纳的",
        "sentence": "Many <mark>adopted</mark> individuals hope genetic kits will reunite them with biological relatives.",
        "sentencePlain": "Many adopted individuals hope genetic kits will reunite them with biological relatives.",
        "translation": "许多被收养者希望基因盒能让他们与亲生血亲重新建立联系。"
    },
    {
        "id": "2009-T2-06",
        "year": 2009,
        "text": "Text 2",
        "word": "track down",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 追查追溯到",
        "def": "追踪查明、追踪找到",
        "sentence": "Genealogists meticulously sift through historical archives to <mark>track down</mark> elusive ancestors.",
        "sentencePlain": "Genealogists meticulously sift through historical archives to track down elusive ancestors.",
        "translation": "家谱学者细致梳理历史档案，以追踪找到难以寻觅的祖先踪迹。"
    },
    {
        "id": "2009-T2-07",
        "year": 2009,
        "text": "Text 2",
        "word": "put up for",
        "category": "固定短语",
        "noteTag": "★ 动词短语搭配 · 供收养出售",
        "def": "供出售、供领养",
        "sentence": "Children <mark>put up for</mark> adoption decades ago now turn to consumer genomics for answers.",
        "sentencePlain": "Children put up for adoption decades ago now turn to consumer genomics for answers.",
        "translation": "几十年前被送去领养的孩子，如今纷纷借助消费级基因组学来寻找答案。"
    },
    {
        "id": "2009-T2-08",
        "year": 2009,
        "text": "Text 2",
        "word": "the latest rage",
        "category": "固定短语",
        "noteTag": "★ 核心考点：俚语短语 · 风靡一时的最新热潮",
        "def": "最新的时尚、风靡一时的事物",
        "sentence": "Tracing one's geographic roots via buccal swabs has become <mark>the latest rage</mark> among hobbyists.",
        "sentencePlain": "Tracing one's geographic roots via buccal swabs has become the latest rage among hobbyists.",
        "translation": "通过口腔拭子追溯个人的地理渊源，已经成为业余爱好者中风靡一时的最新热潮。"
    },
    {
        "id": "2009-T2-09",
        "year": 2009,
        "text": "Text 2",
        "word": "passionate",
        "category": "核心词汇",
        "noteTag": "★ 感情色彩形容词 · 狂热热忱的",
        "def": "狂热的、热情的、热忱的",
        "sentence": "Millions of <mark>passionate</mark> family historians have uploaded their genetic markers onto public databases.",
        "sentencePlain": "Millions of passionate family historians have uploaded their genetic markers onto public databases.",
        "translation": "数百万热情的家族历史探寻者已将他们的遗传标记上传至公共数据库。"
    },
    {
        "id": "2009-T2-10",
        "year": 2009,
        "text": "Text 2",
        "word": "genealogists",
        "category": "核心词汇",
        "noteTag": "★ 学科构词：gene + logy + ist",
        "def": "系谱学者、家谱探寻者",
        "sentence": "Amateur <mark>genealogists</mark> treat company ethnicity estimates as infallible scientific gospel.",
        "sentencePlain": "Amateur genealogists treat company ethnicity estimates as infallible scientific gospel.",
        "translation": "业余家谱学者把商业公司的种族溯源估测当作绝对可靠的科学福音。"
    },
    {
        "id": "2009-T2-11",
        "year": 2009,
        "text": "Text 2",
        "word": "swab",
        "category": "核心词汇",
        "noteTag": "★ 医学取样名词与动词 · 拭子",
        "def": "医用棉签、拭子；用拭子取样",
        "sentence": "Customers simply take a cheek <mark>swab</mark> and mail it to a commercial processing lab.",
        "sentencePlain": "Customers simply take a cheek swab and mail it to a commercial processing lab.",
        "translation": "顾客只需用口腔拭子刮一下面颊，然后寄往商业检测实验室。"
    },
    {
        "id": "2009-T2-12",
        "year": 2009,
        "text": "Text 2",
        "word": "saliva",
        "category": "核心词汇",
        "noteTag": "★ 生理学名词 · 唾液",
        "def": "唾液、口水",
        "sentence": "A small vial of <mark>saliva</mark> provides thousands of DNA markers for automated sequence machines.",
        "sentencePlain": "A small vial of saliva provides thousands of DNA markers for automated sequence machines.",
        "translation": "一小瓶唾液便能为自动化测序仪提供数以千计的DNA标记。"
    },
    {
        "id": "2009-T2-13",
        "year": 2009,
        "text": "Text 2",
        "word": "there be句型",
        "category": "句型语法",
        "noteTag": "★ 核心考点：there be 存在句型倒装",
        "def": "存在、有",
        "sentence": "<mark>There be</mark> severe statistical limits to how precisely any genetic test can identify ancestral origin.",
        "sentencePlain": "There be severe statistical limits to how precisely any genetic test can identify ancestral origin.",
        "translation": "在任何基因检测能够多么精准地识别祖先源头这一点上，存在着严重的统计学局限。"
    },
    {
        "id": "2009-T2-14",
        "year": 2009,
        "text": "Text 2",
        "word": "hawk",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 动词沿街兜售/叫卖",
        "def": "沿街兜售、叫卖；鹰",
        "sentence": "Private startups aggressively <mark>hawk</mark> personalized ancestry tests without fully explaining their limitations.",
        "sentencePlain": "Private startups aggressively hawk personalized ancestry tests without fully explaining their limitations.",
        "translation": "私营初创公司极力兜售个性化寻根检测，却未能充分解释其局限性。"
    },
    {
        "id": "2009-T2-15",
        "year": 2009,
        "text": "Text 2",
        "word": "numbering (分词短语作状语)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：现在分词短语作补充伴随状语",
        "def": "数量达到……",
        "sentence": "DNA companies boast extensive reference panels, <mark>numbering</mark> in the tens of thousands of contemporary subjects.",
        "sentencePlain": "DNA companies boast extensive reference panels, numbering in the tens of thousands of contemporary subjects.",
        "translation": "DNA检测公司夸耀其庞大的参考样本库，其数量高达数以万计的当代受试者。"
    },
    {
        "id": "2009-T2-16",
        "year": 2009,
        "text": "Text 2",
        "word": "line",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 家族血统/宗系",
        "def": "血统、系谱；台词；线路",
        "sentence": "You inherit genetic material through an intricate family tree, not a simple direct <mark>line</mark>.",
        "sentencePlain": "You inherit genetic material through an intricate family tree, not a simple direct line.",
        "translation": "你是通过复杂的家谱树遗传物质的，而非通过单一笔直的直接血统脉络。"
    },
    {
        "id": "2009-T2-17",
        "year": 2009,
        "text": "Text 2",
        "word": "pass down",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 世代相传",
        "def": "代代相传、流传下去",
        "sentence": "Distinctive genetic segments are randomly <mark>passed down</mark> from grandparents to successive generations.",
        "sentencePlain": "Distinctive genetic segments are randomly passed down from grandparents to successive generations.",
        "translation": "具有特征的基因片段从祖父母那里随机地代代相传至后辈子孙。"
    },
    {
        "id": "2009-T2-18",
        "year": 2009,
        "text": "Text 2",
        "word": "A be only as good as B",
        "category": "句型语法",
        "noteTag": "★ 核心考点：原级比较 · A的好坏取决于B",
        "def": "A 的好坏完全取决于 B 的好坏",
        "sentence": "An ancestry estimate <mark>is only as good as</mark> the reference database against which it is compared.",
        "sentencePlain": "An ancestry estimate is only as good as the reference database against which it is compared.",
        "translation": "祖先渊源推测的准确度，完全取决于（A be only as good as B）其与之进行比对的参考数据库的质量。"
    },
    {
        "id": "2009-T2-19",
        "year": 2009,
        "text": "Text 2",
        "word": "reference",
        "category": "核心词汇",
        "noteTag": "★ 科学统计名词 · 参考对照基准",
        "def": "参考、对照；参考样本",
        "sentence": "Without a geographically balanced <mark>reference</mark> population, genetic ancestry conclusions remain skewed.",
        "sentencePlain": "Without a geographically balanced reference population, genetic ancestry conclusions remain skewed.",
        "translation": "如果缺乏地理分布均衡的参考样本人群，基因溯源的结论就依然会存在偏差。"
    },
    {
        "id": "2009-T2-20",
        "year": 2009,
        "text": "Text 2",
        "word": "lump together",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 混为一谈/归并在起",
        "def": "归并在一起、不加区分地混为一谈",
        "sentence": "Commercial algorithms often <mark>lump together</mark> distinct ethnic groups under broad geographic labels.",
        "sentencePlain": "Commercial algorithms often lump together distinct ethnic groups under broad geographic labels.",
        "translation": "商业算法常常把不同的族群不加区分地笼统归并到宽泛的地理标签之下。"
    },
    {
        "id": "2009-T2-21",
        "year": 2009,
        "text": "Text 2",
        "word": "not A but rather B",
        "category": "句型语法",
        "noteTag": "★ 核心考点：并列反向对立 · 不是A而是B",
        "def": "不是 A 而是 B",
        "sentence": "These tests reflect <mark>not</mark> literal historical homelands, <mark>but rather</mark> where modern testers currently reside.",
        "sentencePlain": "These tests reflect not literal historical homelands, but rather where modern testers currently reside.",
        "translation": "这些测试所反映的不是字面意义上的历史故土，而是现代受测人群如今居住的所在。"
    },
    {
        "id": "2009-T2-22",
        "year": 2009,
        "text": "Text 2",
        "word": "promotion",
        "category": "核心词汇",
        "noteTag": "★ 商业核心名词 · 市场推广宣传",
        "def": "推销、宣传；提升、晋升",
        "sentence": "Aggressive marketing <mark>promotion</mark> leads customers to confuse genetic probabilities with cultural identity.",
        "sentencePlain": "Aggressive marketing promotion leads customers to confuse genetic probabilities with cultural identity.",
        "translation": "激进的市场推销宣传导致客户将基因概率与文化认同混为一谈。"
    },
    {
        "id": "2009-T2-23",
        "year": 2009,
        "text": "Text 2",
        "word": "excessive",
        "category": "核心词汇",
        "noteTag": "★ 程度形容词 · 过度的",
        "def": "过度的、过分的",
        "sentence": "Scientists caution against <mark>excessive</mark> faith in simplistic genealogical commercial claims.",
        "sentencePlain": "Scientists caution against excessive faith in simplistic genealogical commercial claims.",
        "translation": "科学家告诫人们不要对过于简单化的商业家谱宣称抱有过度的信任。"
    },
    {
        "id": "2009-T2-24",
        "year": 2009,
        "text": "Text 2",
        "word": "disorganized",
        "category": "核心词汇",
        "noteTag": "★ 构词：dis + organized · 杂乱无章",
        "def": "杂乱无章的、混乱的",
        "sentence": "Early genetic companies relied on <mark>disorganized</mark> and uncurated sample repositories.",
        "sentencePlain": "Early genetic companies relied on disorganized and uncurated sample repositories.",
        "translation": "早期的基因公司依赖的是杂乱无章且未经审慎整理的样本库。"
    }
]

cards_2009_t3 = [
    {
        "id": "2009-T3-01",
        "year": 2009,
        "text": "Text 3",
        "word": "alike (adv后置修饰)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：副词后置修饰两者皆同",
        "def": "同样地、两者都",
        "sentence": "Teachers and parents <mark>alike</mark> recognize that a one-size-fits-all academic curriculum fails many adolescents.",
        "sentencePlain": "Teachers and parents alike recognize that a one-size-fits-all academic curriculum fails many adolescents.",
        "translation": "教师和家长同样地（副词后置）意识到，一刀切的学术课程辜负了许多青少年的期望。"
    },
    {
        "id": "2009-T3-02",
        "year": 2009,
        "text": "Text 3",
        "word": "consistently",
        "category": "核心词汇",
        "noteTag": "★ 频度副词 · 一贯始终如一",
        "def": "一贯地、始终如一地",
        "sentence": "High school dropout rates have remained <mark>consistently</mark> troubling across major metropolitan districts.",
        "sentencePlain": "High school dropout rates have remained consistently troubling across major metropolitan districts.",
        "translation": "各大都市学区的高中辍学率一直令人深感忧虑。"
    },
    {
        "id": "2009-T3-03",
        "year": 2009,
        "text": "Text 3",
        "word": "radically",
        "category": "核心词汇",
        "noteTag": "★ 程度副词 · 根本彻底地",
        "def": "根本上地、彻底地、激进地",
        "sentence": "School systems must <mark>radically</mark> rethink vocational training to align with today's advanced economy.",
        "sentencePlain": "School systems must radically rethink vocational training to align with today's advanced economy.",
        "translation": "学校系统必须从根本上彻底反思职业技能培训，以适应如今的先进经济模式。"
    },
    {
        "id": "2009-T3-04",
        "year": 2009,
        "text": "Text 3",
        "word": "automotive",
        "category": "核心词汇",
        "noteTag": "★ 行业专有名词 · 汽车机动车",
        "def": "汽车的、机动车辆的",
        "sentence": "Modern <mark>automotive</mark> technicians must master computer diagnostics in addition to traditional mechanical skills.",
        "sentencePlain": "Modern automotive technicians must master computer diagnostics in addition to traditional mechanical skills.",
        "translation": "现代汽车技术人员除了掌握传统机械技能外，还必须精通计算机故障诊断。"
    },
    {
        "id": "2009-T3-05",
        "year": 2009,
        "text": "Text 3",
        "word": "counterpart",
        "category": "核心词汇",
        "noteTag": "★ 考研超高频对比词 · 相对对应的人/同行",
        "def": "对应的人或物、同行",
        "sentence": "American vocational students often lag behind their European <mark>counterparts</mark> in technical certifications.",
        "sentencePlain": "American vocational students often lag behind their European counterparts in technical certifications.",
        "translation": "美国职校学生在专业技能认证方面往往落后于其欧洲同行（相对应的人）。"
    },
    {
        "id": "2009-T3-06",
        "year": 2009,
        "text": "Text 3",
        "word": "hunter",
        "category": "核心词汇",
        "noteTag": "★ 隐喻用法 · job-hunter 求职者",
        "def": "猎人、搜寻者",
        "sentence": "Today's job <mark>hunter</mark> requires sophisticated technical credentials rather than a generic diploma.",
        "sentencePlain": "Today's job hunter requires sophisticated technical credentials rather than a generic diploma.",
        "translation": "如今的求职者需要的是精良的技术认证证书，而非一张泛泛的文凭。"
    },
    {
        "id": "2009-T3-07",
        "year": 2009,
        "text": "Text 3",
        "word": "gatherer",
        "category": "核心词汇",
        "noteTag": "★ 构词：gather + er · 收集者",
        "def": "采集者、收集者",
        "sentence": "Society needs analytical problem solvers, not passive <mark>gatherers</mark> of factual data.",
        "sentencePlain": "Society needs analytical problem solvers, not passive gatherers of factual data.",
        "translation": "社会需要的是具备分析能力的问题解决者，而非被动的事实数据收集者。"
    },
    {
        "id": "2009-T3-08",
        "year": 2009,
        "text": "Text 3",
        "word": "put sb through sth",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 使经受折磨/供上学",
        "def": "使某人经受……；供某人上学",
        "sentence": "Forcing all teenagers to <mark>put</mark> themselves <mark>through</mark> advanced calculus makes little pedagogical sense.",
        "sentencePlain": "Forcing all teenagers to put themselves through advanced calculus makes little pedagogical sense.",
        "translation": "强迫所有青少年都让自己经受微积分深造的折磨，在教学法上毫无意义。"
    },
    {
        "id": "2009-T3-09",
        "year": 2009,
        "text": "Text 3",
        "word": "deride",
        "category": "核心词汇",
        "noteTag": "★ 态度动词贬义 · 嘲弄贬低",
        "def": "嘲弄、嘲笑、贬低",
        "sentence": "Snobbish academics unfairly <mark>deride</mark> blue-collar vocational training as second-rate.",
        "sentencePlain": "Snobbish academics unfairly deride blue-collar vocational training as second-rate.",
        "translation": "势利的学术界人士不公平地将蓝领职业培训贬低为次等教育。"
    },
    {
        "id": "2009-T3-10",
        "year": 2009,
        "text": "Text 3",
        "word": "performance",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 学业表现/实绩",
        "def": "表现、实绩、业绩；演出",
        "sentence": "Standardized exam <mark>performance</mark> should not be the sole arbiter of a young person's future potential.",
        "sentencePlain": "Standardized exam performance should not be the sole arbiter of a young person's future potential.",
        "translation": "标准化考试成绩不应成为评判一个年轻人未来潜力的唯一裁判标准。"
    },
    {
        "id": "2009-T3-11",
        "year": 2009,
        "text": "Text 3",
        "word": "suspect",
        "category": "熟词生义",
        "noteTag": "★ 熟词生义 · 动词怀疑/存疑",
        "def": "怀疑、认为……有问题；可疑的",
        "sentence": "Many employers <mark>suspect</mark> that conventional liberal arts credentials do not guarantee workplace readiness.",
        "sentencePlain": "Many employers suspect that conventional liberal arts credentials do not guarantee workplace readiness.",
        "translation": "许多雇主怀疑传统的文科文凭并不能保证员工具备职场就绪能力。"
    },
    {
        "id": "2009-T3-12",
        "year": 2009,
        "text": "Text 3",
        "word": "only with",
        "category": "句型语法",
        "noteTag": "★ 倒装句结构前导 · 只有当……",
        "def": "只有伴随着……",
        "sentence": "<mark>Only with</mark> rigorous technical apprenticeships can non-college youths secure high-wage careers.",
        "sentencePlain": "Only with rigorous technical apprenticeships can non-college youths secure high-wage careers.",
        "translation": "只有伴随着严格的学徒技能训练，不上大学的青年才能获得高薪的职业生涯。"
    },
    {
        "id": "2009-T3-13",
        "year": 2009,
        "text": "Text 3",
        "word": "conventionally",
        "category": "核心词汇",
        "noteTag": "★ 构词：convention + al + ly · 传统惯例地",
        "def": "照惯例地、传统地",
        "sentence": "Success has been <mark>conventionally</mark> measured by college admission rather than occupational mastery.",
        "sentencePlain": "Success has been conventionally measured by college admission rather than occupational mastery.",
        "translation": "依照惯例，成功向来是用能否考上大学而非职业技能掌握程度来衡量的。"
    },
    {
        "id": "2009-T3-14",
        "year": 2009,
        "text": "Text 3",
        "word": "downgrade (v)",
        "category": "核心词汇",
        "noteTag": "★ 核心考点：明确为动词用法 · 贬低/降级",
        "def": "贬低、降级",
        "sentence": "High schools should not <mark>downgrade</mark> technical crafts to accommodate inflated college-for-all slogans.",
        "sentencePlain": "High schools should not downgrade technical crafts to accommodate inflated college-for-all slogans.",
        "translation": "高中不应该贬低实用技术手艺，去迎合那种虚假浮夸的“人人上大学”口号。"
    },
    {
        "id": "2009-T3-15",
        "year": 2009,
        "text": "Text 3",
        "word": "hold",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 持有某种学术观点",
        "def": "拥有、持有；持……观点",
        "sentence": "Pragmatic educators <mark>hold</mark> that diverse career pathways benefit both students and national prosperity.",
        "sentencePlain": "Pragmatic educators hold that diverse career pathways benefit both students and national prosperity.",
        "translation": "务实的教育工作者认为（持有观点），多元化的职业通道既有益于学生也有利于国家繁荣。"
    },
    {
        "id": "2009-T3-16",
        "year": 2009,
        "text": "Text 3",
        "word": "prioritize",
        "category": "核心词汇",
        "noteTag": "★ 构词：priority + ize · 优先考虑",
        "def": "优先考虑、按优先顺序处理",
        "sentence": "Educational policy must <mark>prioritize</mark> practical marketable skills alongside general academic literacy.",
        "sentencePlain": "Educational policy must prioritize practical marketable skills alongside general academic literacy.",
        "translation": "教育政策必须在通用学术素养的同时，优先考虑具备市场实用价值的技能。"
    },
    {
        "id": "2009-T3-17",
        "year": 2009,
        "text": "Text 3",
        "word": "be subject to",
        "category": "固定短语",
        "noteTag": "★ 考研超高频短语 · 服从/经受审查",
        "def": "易受……影响；须服从……",
        "sentence": "Job training curriculums must <mark>be subject to</mark> continual review by private industry partners.",
        "sentencePlain": "Job training curriculums must be subject to continual review by private industry partners.",
        "translation": "职业培训课程必须接受行业私企合作伙伴的持续审查与评估。"
    },
    {
        "id": "2009-T3-18",
        "year": 2009,
        "text": "Text 3",
        "word": "result from",
        "category": "固定短语",
        "noteTag": "★ 因果逻辑短语 · 起因于",
        "def": "由……导致、起因于",
        "sentence": "Youth unemployment frequently <mark>results from</mark> a fundamental mismatch between schooling and market demands.",
        "sentencePlain": "Youth unemployment frequently results from a fundamental mismatch between schooling and market demands.",
        "translation": "青年失业往往起因于学校教育与市场实际需求之间的根本脱节。"
    },
    {
        "id": "2009-T3-19",
        "year": 2009,
        "text": "Text 3",
        "word": "fall",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 责任落在……身上 (fall on)",
        "def": "落下、沦落；衰退",
        "sentence": "The obligation should not <mark>fall</mark> solely on struggling families to bridge this institutional training gap.",
        "sentencePlain": "The obligation should not fall solely on struggling families to bridge this institutional training gap.",
        "translation": "弥合这种体制性培训鸿沟的责任，不应当仅仅落在苦苦挣扎的家庭身上。"
    }
]

cards_2009_t4 = [
    {
        "id": "2009-T4-01",
        "year": 2009,
        "text": "Text 4",
        "word": "intellectual",
        "category": "核心词汇",
        "noteTag": "★ 核心学术词汇 · 知识分子的/智力的",
        "def": "智力的、知识分子的；学者",
        "sentence": "The early settlers established an intense <mark>intellectual</mark> culture despite harsh pioneer living conditions.",
        "sentencePlain": "The early settlers established an intense intellectual culture despite harsh pioneer living conditions.",
        "translation": "尽管拓荒生活环境严酷，早期的移居者依然建立起了一种浓厚深奥的知识分子文化。"
    },
    {
        "id": "2009-T4-02",
        "year": 2009,
        "text": "Text 4",
        "word": "standard",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 水平规范",
        "def": "水平、标准、规范",
        "sentence": "The remarkable <mark>standard</mark> of literacy among ordinary Massachusetts villagers astonished European observers.",
        "sentencePlain": "The remarkable standard of literacy among ordinary Massachusetts villagers astonished European observers.",
        "translation": "普通马萨诸塞村民非凡的识字读写水平让欧洲的观察家们大为震惊。"
    },
    {
        "id": "2009-T4-03",
        "year": 2009,
        "text": "Text 4",
        "word": "nowhere else (倒装全盘否定)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：否定倒装前置 · 全盘否定在别处都不",
        "def": "在别处都不……",
        "sentence": "<mark>Nowhere else</mark> in the seventeenth-century Western world did religion and erudition intertwine so deeply.",
        "sentencePlain": "Nowhere else in the seventeenth-century Western world did religion and erudition intertwine so deeply.",
        "translation": "在17世纪的西方世界中，在其他任何地方（全盘否定倒装）宗教与渊博学识都不曾交织得如此深切。"
    },
    {
        "id": "2009-T4-04",
        "year": 2009,
        "text": "Text 4",
        "word": "attach (importance) to sth",
        "category": "固定短语",
        "noteTag": "★ 考研超高频短语 · 认为……高度重要",
        "def": "认为……重要、高度重视……",
        "sentence": "Puritan ministers <mark>attached</mark> supreme importance <mark>to</mark> the ability of every layman to read scripture.",
        "sentencePlain": "Puritan ministers attached supreme importance to the ability of every layman to read scripture.",
        "translation": "清教徒牧师高度重视每位普通信徒阅读圣经文本的能力。"
    },
    {
        "id": "2009-T4-05",
        "year": 2009,
        "text": "Text 4",
        "word": "preoccupation",
        "category": "核心词汇",
        "noteTag": "★ 构词：pre + occupy + ation · 执念焦点",
        "def": "全神贯注、关心的焦点、执念",
        "sentence": "Their religious <mark>preoccupation</mark> with salvation directly fueled an extraordinary educational renaissance.",
        "sentencePlain": "Their religious preoccupation with salvation directly fueled an extraordinary educational renaissance.",
        "translation": "他们在宗教上对救赎的执着追求，直接推动了一场非凡的教育复兴。"
    },
    {
        "id": "2009-T4-06",
        "year": 2009,
        "text": "Text 4",
        "word": "unfolding",
        "category": "核心词汇",
        "noteTag": "★ 动态名词/形容词 · 逐步展现",
        "def": "逐步展开、发展演化",
        "sentence": "They viewed world history as the majestic <mark>unfolding</mark> of divine providence.",
        "sentencePlain": "They viewed world history as the majestic unfolding of divine providence.",
        "translation": "他们将世界历史视作神圣天意波澜壮阔的逐步展现。"
    },
    {
        "id": "2009-T4-07",
        "year": 2009,
        "text": "Text 4",
        "word": "in keeping with",
        "category": "固定短语",
        "noteTag": "★ 书面短语 · 与……一致契合",
        "def": "与……一致、符合",
        "sentence": "Founding Harvard College in 1636 was <mark>in keeping with</mark> their rigorous scholarly convictions.",
        "sentencePlain": "Founding Harvard College in 1636 was in keeping with their rigorous scholarly convictions.",
        "translation": "1636年创立哈佛学院正与他们严谨治学的坚定信念相一致。"
    },
    {
        "id": "2009-T4-08",
        "year": 2009,
        "text": "Text 4",
        "word": "consider A as B",
        "category": "固定短语",
        "noteTag": "★ 判定动词短语 · 将A视作B",
        "def": "将 A 视作 B",
        "sentence": "The Puritans did not <mark>consider</mark> secular ignorance <mark>as</mark> an acceptable excuse for spiritual piety.",
        "sentencePlain": "The Puritans did not consider secular ignorance as an acceptable excuse for spiritual piety.",
        "translation": "清教徒绝不将世俗的无知视作为虔诚信仰进行开脱的合理借口。"
    },
    {
        "id": "2009-T4-09",
        "year": 2009,
        "text": "Text 4",
        "word": "scenes",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 舞台/活动圈子场景",
        "def": "场景、天地；界、圈子",
        "sentence": "Dramatic <mark>scenes</mark> of religious debate unfolded in drafty wooden meetinghouses every Sunday.",
        "sentencePlain": "Dramatic scenes of religious debate unfolded in drafty wooden meetinghouses every Sunday.",
        "translation": "每逢周日，通风漏风的木质集会厅里都会上演激烈辩论的生动场景。"
    },
    {
        "id": "2009-T4-10",
        "year": 2009,
        "text": "Text 4",
        "word": "virtuosity",
        "category": "核心词汇",
        "noteTag": "★ 艺术学术高阶难词 · 精湛造诣",
        "def": "精湛技艺、高超技艺",
        "sentence": "Preachers exhibited astonishing linguistic <mark>virtuosity</mark> during two-hour theological sermons.",
        "sentencePlain": "Preachers exhibited astonishing linguistic virtuosity during two-hour theological sermons.",
        "translation": "传道士在长达两小时的神学布道中展现出了令人叹服的语言精湛造诣。"
    },
    {
        "id": "2009-T4-11",
        "year": 2009,
        "text": "Text 4",
        "word": "audience",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 听众受众",
        "def": "听众、观众、读者受众",
        "sentence": "The rustic congregational <mark>audience</mark> followed intricate biblical cross-references without difficulty.",
        "sentencePlain": "The rustic congregational audience followed intricate biblical cross-references without difficulty.",
        "translation": "那些淳朴的会众听众能够毫无困难地跟上错综复杂的圣经互文对照。"
    },
    {
        "id": "2009-T4-12",
        "year": 2009,
        "text": "Text 4",
        "word": "besides",
        "category": "核心词汇",
        "noteTag": "★ 递进逻辑连词/介词 · 除此之外",
        "def": "除此之外、况且",
        "sentence": "<mark>Besides</mark> religious tracts, New England households avidly devoured classical English histories.",
        "sentencePlain": "Besides religious tracts, New England households avidly devoured classical English histories.",
        "translation": "除了宗教短文之外，新英格兰的家庭还贪婪地研读古典英格兰历史书籍。"
    },
    {
        "id": "2009-T4-13",
        "year": 2009,
        "text": "Text 4",
        "word": "or so",
        "category": "固定短语",
        "noteTag": "★ 约数短语 · 大约/左右",
        "def": "大约、左右",
        "sentence": "A typical sermon lasted two hours <mark>or so</mark>, packed with dense philosophical proofs.",
        "sentencePlain": "A typical sermon lasted two hours or so, packed with dense philosophical proofs.",
        "translation": "一场典型的布道持续两个小时左右，通篇塞满了密集的哲学论证。"
    },
    {
        "id": "2009-T4-14",
        "year": 2009,
        "text": "Text 4",
        "word": "let alone",
        "category": "固定短语",
        "noteTag": "★ 考研经典递进短语 · 更不用说",
        "def": "更不用说、更谈不上",
        "sentence": "Few modern graduates can follow such theological debates, <mark>let alone</mark> construct them from memory.",
        "sentencePlain": "Few modern graduates can follow such theological debates, let alone construct them from memory.",
        "translation": "很少有现代大学毕业生能够跟上这等神学辩论，更不用说仅凭记忆将其构建出来了。"
    },
    {
        "id": "2009-T4-15",
        "year": 2009,
        "text": "Text 4",
        "word": "intellect",
        "category": "核心词汇",
        "noteTag": "★ 核心心智词汇 · 才智智力",
        "def": "智力、思维能力、才智",
        "sentence": "They believed that cultivating human <mark>intellect</mark> was the most authentic way to honor the Creator.",
        "sentencePlain": "They believed that cultivating human intellect was the most authentic way to honor the Creator.",
        "translation": "他们坚信，开掘人类的智力是尊崇造物主最为纯正真切的方式。"
    },
    {
        "id": "2009-T4-16",
        "year": 2009,
        "text": "Text 4",
        "word": "earnestness",
        "category": "核心词汇",
        "noteTag": "★ 构词：earnest + ness · 诚挚认真",
        "def": "认真、诚挚、殷切",
        "sentence": "The moral <mark>earnestness</mark> of the colonists gave birth to America's first free public school systems.",
        "sentencePlain": "The moral earnestness of the colonists gave birth to America's first free public school systems.",
        "translation": "殖民地定居者在道德上的严肃认真，催生了美国最初的免费公共学校体制。"
    },
    {
        "id": "2009-T4-17",
        "year": 2009,
        "text": "Text 4",
        "word": "dependent",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 依赖取决于 (dependent on)",
        "def": "依赖的、取决于……的",
        "sentence": "Spiritual salvation was perceived as deeply <mark>dependent</mark> upon active and learned reflection.",
        "sentencePlain": "Spiritual salvation was perceived as deeply dependent upon active and learned reflection.",
        "translation": "精神救赎被认为在深层次上依赖于主动且博学的深刻省思。"
    },
    {
        "id": "2009-T4-18",
        "year": 2009,
        "text": "Text 4",
        "word": "left literary (自动词)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：leave不及物自动词用法 · 留下文学遗产",
        "def": "留下文学遗产、弃文从……",
        "sentence": "Few pioneers <mark>left</mark> literary records behind, but early Puritans filled notebooks with copious diaries.",
        "sentencePlain": "Few pioneers left literary records behind, but early Puritans filled notebooks with copious diaries.",
        "translation": "很少有拓荒者留下了文学记录，但早期的清教徒却在笔记本里写满了洋洋洒洒的日记。"
    },
    {
        "id": "2009-T4-19",
        "year": 2009,
        "text": "Text 4",
        "word": "leave",
        "category": "熟词生义",
        "noteTag": "★ 动词多义 · 留下深刻印记",
        "def": "离开；留下、遗留",
        "sentence": "Their writings <mark>leave</mark> an indelible impression of a society intoxicated with ideas and learning.",
        "sentencePlain": "Their writings leave an indelible impression of a society intoxicated with ideas and learning.",
        "translation": "他们的著述给人们留下了一种不可磨灭的深刻印象：那是一个沉醉于思想与博学的社会。"
    },
    {
        "id": "2009-T4-20",
        "year": 2009,
        "text": "Text 4",
        "word": "settle",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 移民定居",
        "def": "定居；解决；安顿",
        "sentence": "When the English Puritans chose to <mark>settle</mark> in the wilderness, books were their most treasured cargo.",
        "sentencePlain": "When the English Puritans chose to settle in the wilderness, books were their most treasured cargo.",
        "translation": "当英格兰清教徒选择在这片荒原定居时，书籍是他们最为珍视的行装。"
    },
    {
        "id": "2009-T4-21",
        "year": 2009,
        "text": "Text 4",
        "word": "account",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 名词历史记录/描述",
        "def": "叙述、记录、记述；解释",
        "sentence": "Contemporary historical <mark>accounts</mark> reveal that illiteracy was virtually eradicated within two generations.",
        "sentencePlain": "Contemporary historical accounts reveal that illiteracy was virtually eradicated within two generations.",
        "translation": "当时的历史记录显示，文盲现象在两代人之内就几乎被彻底根除了。"
    },
    {
        "id": "2009-T4-22",
        "year": 2009,
        "text": "Text 4",
        "word": "sermon",
        "category": "核心词汇",
        "noteTag": "★ 宗教文化核心名词 · 布道讲道",
        "def": "布道、讲道、布道词",
        "sentence": "The weekly Puritan <mark>sermon</mark> functioned as university lecture, news broadcast, and moral tribunal rolled into one.",
        "sentencePlain": "The weekly Puritan sermon functioned as university lecture, news broadcast, and moral tribunal rolled into one.",
        "translation": "清教徒每周一次的布道集大学讲座、新闻播报与道德法庭于一身。"
    },
    {
        "id": "2009-T4-23",
        "year": 2009,
        "text": "Text 4",
        "word": "slight",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 动词轻视/怠慢",
        "def": "微不足道的；轻视、怠慢",
        "sentence": "They refused to <mark>slight</mark> intellectual rigor in favor of emotional religious revivalism.",
        "sentencePlain": "They refused to slight intellectual rigor in favor of emotional religious revivalism.",
        "translation": "他们拒绝为了偏袒情绪化的宗教狂热而轻视严谨的智力求索。"
    },
    {
        "id": "2009-T4-24",
        "year": 2009,
        "text": "Text 4",
        "word": "think of",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 设想/视作",
        "def": "考虑、设想、想起",
        "sentence": "It is impossible to <mark>think of</mark> early American democracy without acknowledging its deeply literate foundations.",
        "sentencePlain": "It is impossible to think of early American democracy without acknowledging its deeply literate foundations.",
        "translation": "要想探究早期美国民主，就绝不可能不承认其深厚广博的识字文化根基。"
    },
    {
        "id": "2009-T4-25",
        "year": 2009,
        "text": "Text 4",
        "word": "bring sth with sb",
        "category": "固定短语",
        "noteTag": "★ 基础短语搭配 · 随身带来",
        "def": "随身携带某物、带来",
        "sentence": "The settlers did not merely cross an ocean; they <mark>brought with</mark> them centuries of intellectual heritage.",
        "sentencePlain": "The settlers did not merely cross an ocean; they brought with them centuries of intellectual heritage.",
        "translation": "那些定居者不仅仅是横渡了大洋；他们随身带来了数百年积累的智识传承。"
    },
    {
        "id": "2009-T4-26",
        "year": 2009,
        "text": "Text 4",
        "word": "obsessed",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 执迷着魔 (obsessed with)",
        "def": "着迷的、心神不宁的、被困扰的",
        "sentence": "Early American colonists were famously <mark>obsessed</mark> with the correct doctrinal interpretation of holy texts.",
        "sentencePlain": "Early American colonists were famously obsessed with the correct doctrinal interpretation of holy texts.",
        "translation": "早期美国殖民者在对圣经教义的正确阐释上表现出了众所周知的执着与着迷。"
    },
    {
        "id": "2009-T4-27",
        "year": 2009,
        "text": "Text 4",
        "word": "earnings",
        "category": "核心词汇",
        "noteTag": "★ 经济名词 · 劳动收入所得",
        "def": "收入、报酬、利润",
        "sentence": "Families allocated substantial portions of their meager <mark>earnings</mark> toward purchasing family Bibles and primers.",
        "sentencePlain": "Families allocated substantial portions of their meager earnings toward purchasing family Bibles and primers.",
        "translation": "各家庭将微薄收入中相当大的一部分专门用来购买家族圣经与启蒙读本。"
    },
    {
        "id": "2009-T4-28",
        "year": 2009,
        "text": "Text 4",
        "word": "superstition",
        "category": "核心词汇",
        "noteTag": "★ 核心文化名词 · 迷信",
        "def": "迷信、迷信观念",
        "sentence": "Rigorous education was viewed as humanity's most potent weapon against pagan <mark>superstition</mark>.",
        "sentencePlain": "Rigorous education was viewed as humanity's most potent weapon against pagan superstition.",
        "translation": "严格的理性教育被视作人类抵御异教迷信的最强大武器。"
    }
]
