# -*- coding: utf-8 -*-

cards_2010_t1 = [
    {
        "id": "2010-T1-01",
        "year": 2010,
        "text": "Text 1",
        "word": "coverage",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 考研高频陷阱 (非“覆盖率”)",
        "def": "新闻报道",
        "sentence": "Of all the changes that have taken place in English-language newspapers during the past quarter-century, perhaps the most far-reaching has been the inexorable decline in the scope and seriousness of their arts <mark>coverage</mark>.",
        "sentencePlain": "Of all the changes that have taken place in English-language newspapers during the past quarter-century, perhaps the most far-reaching has been the inexorable decline in the scope and seriousness of their arts coverage.",
        "translation": "在过去25年里英文报纸所发生的所有变化中，影响最深远的也许是其艺术报道在范围和严肃性上出现的不可阻挡的下滑。"
    },
    {
        "id": "2010-T1-02",
        "year": 2010,
        "text": "Text 1",
        "word": "unfocused",
        "category": "熟词生义",
        "noteTag": "★ 引申褒贬色彩 · 含贬义",
        "def": "无目的的，引申为无固定主题的、漫谈式的",
        "sentence": "We are even farther removed from the <mark>unfocused</mark> newspaper reviews published in England between the turn of the 20th century and the eve of World War II...",
        "sentencePlain": "We are even farther removed from the unfocused newspaper reviews published in England between the turn of the 20th century and the eve of World War II...",
        "translation": "我们与20世纪初至二战前夕在英格兰发表的那些缺乏明确主题、漫谈式的报纸评论相距更加遥远……"
    },
    {
        "id": "2010-T1-03",
        "year": 2010,
        "text": "Text 1",
        "word": "calling",
        "category": "熟词生义",
        "noteTag": "★ 词义专有化 · 非呼叫",
        "def": "使命感、天职",
        "sentence": "These men believed in journalism as a <mark>calling</mark>, and were proud to be published in the daily press.",
        "sentencePlain": "These men believed in journalism as a calling, and were proud to be published in the daily press.",
        "translation": "这些人将新闻业视作一种崇高的使命感（天职），并为自己的文字能发表在日报上而深感自豪。"
    },
    {
        "id": "2010-T1-04",
        "year": 2010,
        "text": "Text 1",
        "word": "save",
        "category": "熟词生义",
        "noteTag": "★ 词性活用 · 介词 prep. = except (非动词“拯救”)",
        "def": "除了",
        "sentence": "Yet only one of his books is now in print, and his vast body of writings on music is unknown <mark>save</mark> to specialists.",
        "sentencePlain": "Yet only one of his books is now in print, and his vast body of writings on music is unknown save to specialists.",
        "translation": "然而，他的著作现在只有一本还在印行，他大量的音乐著述除了专业研究者之外已无人知晓。"
    },
    {
        "id": "2010-T1-05",
        "year": 2010,
        "text": "Text 1",
        "word": "stylist",
        "category": "熟词生义",
        "noteTag": "★ 文学语境义 · 非发型师",
        "def": "文体家、散文名家",
        "sentence": "During his lifetime, though, he was also one of England's foremost classical-music critics, and a <mark>stylist</mark> so widely admired that his Autobiography (1947) became a best-seller.",
        "sentencePlain": "During his lifetime, though, he was also one of England's foremost classical-music critics, and a stylist so widely admired that his Autobiography (1947) became a best-seller.",
        "translation": "然而在他生前，他也是英格兰最重要的古典音乐评论家之一，一位备受推崇的文体家，其《自传》（1947）曾成为畅销书。"
    },
    {
        "id": "2010-T1-06",
        "year": 2010,
        "text": "Text 1",
        "word": "to the point of ...",
        "category": "固定短语",
        "noteTag": "★ 介词短语 · 表程度",
        "def": "到了……的程度/地步",
        "sentence": "It is difficult <mark>to the point of</mark> impossibility for the average reader under the age of forty to imagine a time when high-quality arts criticism could be found in most big-city newspapers.",
        "sentencePlain": "It is difficult to the point of impossibility for the average reader under the age of forty to imagine a time when high-quality arts criticism could be found in most big-city newspapers.",
        "translation": "对于40岁以下的普通读者来说，要想象一个在大多数大城市日报上都能读到高品质艺术评论的时代，已经困难到了几乎不可能的地步。"
    },
    {
        "id": "2010-T1-07",
        "year": 2010,
        "text": "Text 1",
        "word": "A consist of B",
        "category": "固定短语",
        "noteTag": "★语法红线：绝对没有被动态！ (千万不可写成 is consisted of)",
        "def": "A 由 B 组成",
        "sentence": "Yet a considerable number of the most significant collections of criticism published in the 20th century <mark>consisted</mark> in large part <mark>of</mark> newspaper reviews.",
        "sentencePlain": "Yet a considerable number of the most significant collections of criticism published in the 20th century consisted in large part of newspaper reviews.",
        "translation": "然而，20世纪出版的许多最具分量的评论集，在很大程度上都是由报纸上的书评构成的。"
    },
    {
        "id": "2010-T1-08",
        "year": 2010,
        "text": "Text 1",
        "word": "marvel at",
        "category": "固定短语",
        "noteTag": "★ 褒义情感色彩 · 赞叹",
        "def": "对……感到惊奇、由衷赞叹",
        "sentence": "To read such books today is to <mark>marvel at</mark> the fact that their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "sentencePlain": "To read such books today is to marvel at the fact that their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "translation": "今天读到这些著作，人们不禁对这样一个事实感到赞叹：那些博大精深的学术内容，曾经竟然被认为适合刊登在普及发行的日报上。"
    },
    {
        "id": "2010-T1-09",
        "year": 2010,
        "text": "Text 1",
        "word": "take A for granted",
        "category": "固定短语",
        "noteTag": "★ 真题常考形式主语被动语态",
        "def": "将 A 视为理所当然",
        "sentence": "In those far-off days, it was <mark>taken for granted</mark> that the critics of major papers would write in detail and at length about the events they covered.",
        "sentencePlain": "In those far-off days, it was taken for granted that the critics of major papers would write in detail and at length about the events they covered.",
        "translation": "在那些久远的年代里，主流报刊的评论家们对所报道的事件进行详尽且长篇累牍的评述，是被视作理所当然的事情。"
    },
    {
        "id": "2010-T1-10",
        "year": 2010,
        "text": "Text 1",
        "word": "at length",
        "category": "固定短语",
        "noteTag": "★ 篇幅/时间双重含义",
        "def": "详尽地、长篇累牍地；最终地",
        "sentence": "In those far-off days, it was taken for granted that the critics of major papers would write in detail and <mark>at length</mark> about the events they covered.",
        "sentencePlain": "In those far-off days, it was taken for granted that the critics of major papers would write in detail and at length about the events they covered.",
        "translation": "主流报纸的评论家们对所报道的事件进行详尽且充分、长篇的评述。"
    },
    {
        "id": "2010-T1-11",
        "year": 2010,
        "text": "Text 1",
        "word": "be tempted to do",
        "category": "固定短语",
        "noteTag": "★ 客观陈述 · 无贬义",
        "def": "很想做……、忍不住做……",
        "sentence": "“...that I am <mark>tempted to define</mark> ‘journalism’ as ‘a term of contempt applied by writers who are not read to writers who are.’”",
        "sentencePlain": "“...that I am tempted to define ‘journalism’ as ‘a term of contempt applied by writers who are not read to writers who are.’”",
        "translation": "“……以至于我很想把‘新闻业’定义为：由无人问津的作者用在拥有读者群体的作者身上的一个轻蔑词汇。”"
    },
    {
        "id": "2010-T1-12",
        "year": 2010,
        "text": "Text 1",
        "word": "applied by A to B",
        "category": "固定短语",
        "noteTag": "★ 被动搭配：施加/应用于",
        "def": "被 A 用于给 B / 由 A 施加给 B",
        "sentence": "“...‘a term of contempt <mark>applied by</mark> writers who are not read <mark>to</mark> writers who are.’”",
        "sentencePlain": "“...‘a term of contempt applied by writers who are not read to writers who are.’”",
        "translation": "“……一个由无人阅读的作家施加在拥有广大读者的作家身上的鄙视用语。”"
    },
    {
        "id": "2010-T1-13",
        "year": 2010,
        "text": "Text 1",
        "word": "have (little) use for",
        "category": "固定短语",
        "noteTag": "★ 真题否定态度表达",
        "def": "对……不感兴趣、不待见、不屑一顾",
        "sentence": "Journalistic tastes had changed long before his death, and postmodern readers <mark>have little use for</mark> the richly upholstered Victorian prose in which he specialized.",
        "sentencePlain": "Journalistic tastes had changed long before his death, and postmodern readers have little use for the richly upholstered Victorian prose in which he specialized.",
        "translation": "新闻界的品味在他去世前很久就发生了变化，而后现代的读者对他擅长的那种文辞繁复华丽的维多利亚风格散文毫无兴趣。"
    },
    {
        "id": "2010-T1-14",
        "year": 2010,
        "text": "Text 1",
        "word": "inexorable",
        "category": "核心词汇",
        "noteTag": "★ 考研高难形容词",
        "def": "不可阻挡的、不可逆转的",
        "sentence": "Of all the changes that have taken place in English-language newspapers during the past quarter-century, perhaps the most far-reaching has been the <mark>inexorable</mark> decline in the scope and seriousness of their arts coverage.",
        "sentencePlain": "Of all the changes that have taken place in English-language newspapers during the past quarter-century, perhaps the most far-reaching has been the inexorable decline in the scope and seriousness of their arts coverage.",
        "translation": "在过去25年英文报纸发生的所有变化中，影响最深远的也许是其艺术报道在广度和严肃性上不可阻挡的衰落。"
    },
    {
        "id": "2010-T1-15",
        "year": 2010,
        "text": "Text 1",
        "word": "once",
        "category": "核心词汇",
        "noteTag": "★ 词性注意：副词 adv. 曾经",
        "def": "曾经",
        "sentence": "To read such books today is to marvel at the fact that their learned contents were <mark>once</mark> deemed suitable for publication in general-circulation dailies.",
        "sentencePlain": "To read such books today is to marvel at the fact that their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "translation": "其博学的深奥内容曾经被认为适合发表在大众发行的日报上。"
    },
    {
        "id": "2010-T1-16",
        "year": 2010,
        "text": "Text 1",
        "word": "circulation",
        "category": "核心词汇",
        "noteTag": "★ 报刊专有用词：发行量",
        "def": "发行、流通",
        "sentence": "...their learned contents were once deemed suitable for publication in general-<mark>circulation</mark> dailies.",
        "sentencePlain": "...their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "translation": "……适合发表在大众发行流通的日报上。"
    },
    {
        "id": "2010-T1-17",
        "year": 2010,
        "text": "Text 1",
        "word": "daily",
        "category": "核心词汇",
        "noteTag": "★ 复数 dailies 做名词",
        "def": "日报",
        "sentence": "...their learned contents were once deemed suitable for publication in general-circulation <mark>dailies</mark>.",
        "sentencePlain": "...their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "translation": "……适合在面向大众流通的日报上登载。"
    },
    {
        "id": "2010-T1-18",
        "year": 2010,
        "text": "Text 1",
        "word": "farther",
        "category": "核心词汇",
        "noteTag": "★ far 的比较级",
        "def": "更远",
        "sentence": "We are even <mark>farther</mark> removed from the unfocused newspaper reviews published in England...",
        "sentencePlain": "We are even farther removed from the unfocused newspaper reviews published in England...",
        "translation": "我们与那些发表在英格兰的漫谈式报纸评论相比，相距甚至更为遥远了。"
    },
    {
        "id": "2010-T1-19",
        "year": 2010,
        "text": "Text 1",
        "word": "stylish",
        "category": "核心词汇",
        "noteTag": "★ 褒义文风描写",
        "def": "时髦的，风格独特的、文笔考究的",
        "sentence": "...at a time when newsprint was dirt-cheap and <mark>stylish</mark> arts criticism was considered an ornament to the publications in which it appeared.",
        "sentencePlain": "...at a time when newsprint was dirt-cheap and stylish arts criticism was considered an ornament to the publications in which it appeared.",
        "translation": "……在那个新闻纸价格低廉如泥土、文笔优美独特的艺术评论被视作刊物点缀修饰的时期。"
    },
    {
        "id": "2010-T1-20",
        "year": 2010,
        "text": "Text 1",
        "word": "wore",
        "category": "核心词汇",
        "noteTag": "★ wear 的过去式 · wear lightly 引申",
        "def": "穿、佩戴；引申为展现",
        "sentence": "...and even those reviewers who <mark>wore</mark> their learning lightly, like George Bernard Shaw and Ernest Newman, could be trusted...",
        "sentencePlain": "...and even those reviewers who wore their learning lightly, like George Bernard Shaw and Ernest Newman, could be trusted...",
        "translation": "……即便是像萧伯纳和纽曼这样学识渊博而不卖弄（展露得很自然）的评论家，也可以被完全信赖。"
    },
    {
        "id": "2010-T1-21",
        "year": 2010,
        "text": "Text 1",
        "word": "cricket",
        "category": "核心词汇",
        "noteTag": "★ 英国文化常识词",
        "def": "板球运动",
        "sentence": "Neville Cardus... is now known solely as a writer of essays on the game of <mark>cricket</mark>.",
        "sentencePlain": "Neville Cardus... is now known solely as a writer of essays on the game of cricket.",
        "translation": "内维尔·卡杜斯……如今仅仅作为一名板球运动散文作家而为人铭记。"
    },
    {
        "id": "2010-T1-22",
        "year": 2010,
        "text": "Text 1",
        "word": "postmodern",
        "category": "核心词汇",
        "noteTag": "★ 文化前缀 post- 考点",
        "def": "后现代的",
        "sentence": "...and <mark>postmodern</mark> readers have little use for the richly upholstered Victorian prose...",
        "sentencePlain": "...and postmodern readers have little use for the richly upholstered Victorian prose...",
        "translation": "……而后现代的读者对他所擅长的那种词藻堆砌冗余的维多利亚散文不感兴趣。"
    },
    {
        "id": "2010-T1-23",
        "year": 2010,
        "text": "Text 1",
        "word": "headlong",
        "category": "核心词汇",
        "noteTag": "★ 迅猛/鲁莽",
        "def": "鲁莽的、快速迅猛的",
        "sentence": "Moreover, the amateur tradition in music criticism has been in <mark>headlong</mark> retreat.",
        "sentencePlain": "Moreover, the amateur tradition in music criticism has been in headlong retreat.",
        "translation": "此外，音乐评论界的业余鉴赏传统也一直处于迅猛的衰退溃散之中。"
    },
    {
        "id": "2010-T1-24",
        "year": 2010,
        "text": "Text 1",
        "word": "retreat",
        "category": "核心词汇",
        "noteTag": "★ 军事引申为抽象衰退",
        "def": "退步、撤退、衰落",
        "sentence": "Moreover, the amateur tradition in music criticism has been in headlong <mark>retreat</mark>.",
        "sentencePlain": "Moreover, the amateur tradition in music criticism has been in headlong retreat.",
        "translation": "音乐评论界业余传统的溃败退步。"
    },
    {
        "id": "2010-T1-25",
        "year": 2010,
        "text": "Text 1",
        "word": "To do sth is to do ...",
        "category": "句型语法",
        "noteTag": "★ 动词不定式做主表对应",
        "def": "做 A 就是做 B",
        "sentence": "<mark>To read</mark> such books today <mark>is to marvel</mark> at the fact that their learned contents were once deemed suitable...",
        "sentencePlain": "To read such books today is to marvel at the fact that their learned contents were once deemed suitable...",
        "translation": "今天去阅读这样的书籍，就是去赞叹那样一个事实……"
    },
    {
        "id": "2010-T1-26",
        "year": 2010,
        "text": "Text 1",
        "word": "be deemed (to be)",
        "category": "句型语法",
        "noteTag": "★ 学术被动经典句式",
        "def": "被认为是……、被视为……",
        "sentence": "...at the fact that their learned contents were once <mark>deemed</mark> suitable for publication in general-circulation dailies.",
        "sentencePlain": "...at the fact that their learned contents were once deemed suitable for publication in general-circulation dailies.",
        "translation": "……其博学的学术文章曾被认为适合在大众日报上发表。"
    },
    {
        "id": "2010-T1-27",
        "year": 2010,
        "text": "Text 1",
        "word": "in which",
        "category": "句型语法",
        "noteTag": "★ 语法批注：in 前置了！",
        "def": "in 前置了",
        "sentence": "...stylish arts criticism was considered an ornament to the publications <mark>in which</mark> it appeared.",
        "sentencePlain": "...stylish arts criticism was considered an ornament to the publications in which it appeared.",
        "translation": "……风格独特的艺术评论被视作其发表刊物（在其中刊载）的点缀修饰。"
    },
    {
        "id": "2010-T1-28",
        "year": 2010,
        "text": "Text 1",
        "word": "knight",
        "category": "句型语法",
        "noteTag": "★ 名词动用 · 被动语态",
        "def": "封为骑士",
        "sentence": "He was <mark>knighted</mark> in 1967, the first music critic to be so honored.",
        "sentencePlain": "He was knighted in 1967, the first music critic to be so honored.",
        "translation": "他在1967年被封为骑士爵位，是第一位获此荣誉的音乐评论家。"
    }
]

cards_2010_t2 = [
    {
        "id": "2010-T2-01",
        "year": 2010,
        "text": "Text 2",
        "word": "grant",
        "category": "核心词汇",
        "noteTag": "★ 专利法律核心动词 · 授予 (grant a patent)",
        "def": "授予、准予；拨款",
        "sentence": "Over the past decade, thousands of questionable patents have been <mark>granted</mark> for everyday business methods.",
        "sentencePlain": "Over the past decade, thousands of questionable patents have been granted for everyday business methods.",
        "translation": "在过去的十年里，成千上万项成问题的专利被授予了日常商业运营方法。"
    },
    {
        "id": "2010-T2-02",
        "year": 2010,
        "text": "Text 2",
        "word": "patent",
        "category": "核心词汇",
        "noteTag": "★ 核心主题词 · 专利权",
        "def": "专利、专利权；获得专利",
        "sentence": "The Supreme Court agreed to decide whether abstract financial strategies deserve <mark>patent</mark> protection.",
        "sentencePlain": "The Supreme Court agreed to decide whether abstract financial strategies deserve patent protection.",
        "translation": "最高法院同意裁定抽象的金融投资策略是否应享有专利保护。"
    },
    {
        "id": "2010-T2-03",
        "year": 2010,
        "text": "Text 2",
        "word": "appear (to be)",
        "category": "固定短语",
        "noteTag": "★ 学术委婉语气 · 似乎是/显得",
        "def": "似乎是、显得",
        "sentence": "Federal judges <mark>appear to be</mark> increasingly skeptical of monopolies over basic commercial transactions.",
        "sentencePlain": "Federal judges appear to be increasingly skeptical of monopolies over basic commercial transactions.",
        "translation": "联邦法官们似乎越来越怀疑对基础商业交易建立垄断的做法。"
    },
    {
        "id": "2010-T2-04",
        "year": 2010,
        "text": "Text 2",
        "word": "ready",
        "category": "核心词汇",
        "noteTag": "★ 熟词生义 · 准备就绪随时采取行动 (be ready to do)",
        "def": "准备好的；欣然的",
        "sentence": "The legal system stands <mark>ready</mark> to rein in decades of unchecked intellectual property expansion.",
        "sentencePlain": "The legal system stands ready to rein in decades of unchecked intellectual property expansion.",
        "translation": "法律体系随时准备约束数十年来未受遏制的知识产权肆意扩张。"
    },
    {
        "id": "2010-T2-05",
        "year": 2010,
        "text": "Text 2",
        "word": "scale back",
        "category": "固定短语",
        "noteTag": "★ 核心动词短语 · 削减缩减 (scale down/back)",
        "def": "缩减、削减",
        "sentence": "The courts are taking concrete steps to <mark>scale back</mark> overly broad patent rights.",
        "sentencePlain": "The courts are taking concrete steps to scale back overly broad patent rights.",
        "translation": "法院正在采取具体措施，以削减过于宽泛的专利权利范围。"
    },
    {
        "id": "2010-T2-06",
        "year": 2010,
        "text": "Text 2",
        "word": "abuzz",
        "category": "核心词汇",
        "noteTag": "★ 形象生动形容词 · 议论纷纷/炸开了锅",
        "def": "议论纷纷的、嗡嗡作响的",
        "sentence": "Wall Street and Silicon Valley were <mark>abuzz</mark> with anxiety over the forthcoming Bilski verdict.",
        "sentencePlain": "Wall Street and Silicon Valley were abuzz with anxiety over the forthcoming Bilski verdict.",
        "translation": "华尔街和硅谷对即将公布的比尔斯基案判决感到焦虑不安，私下议论纷纷。"
    },
    {
        "id": "2010-T2-07",
        "year": 2010,
        "text": "Text 2",
        "word": "have sb adj",
        "category": "句型语法",
        "noteTag": "★ 核心考点：使役语法 have sb + adj 令某人处于某种状态",
        "def": "使某人处于某种状态",
        "sentence": "The looming appellate decision <mark>has patent lawyers deeply uneasy</mark> about their lucrative business model.",
        "sentencePlain": "The looming appellate decision has patent lawyers deeply uneasy about their lucrative business model.",
        "translation": "迫近的上诉裁决让专利律师们对自己的丰厚业务模式深感不安（have sb adj）。"
    },
    {
        "id": "2010-T2-08",
        "year": 2010,
        "text": "Text 2",
        "word": "a big deal",
        "category": "固定短语",
        "noteTag": "★ 地道表达 · 举足轻重的大事",
        "def": "大事、了不起的事",
        "sentence": "Reversing twelve years of permissive patent precedent is undoubtedly <mark>a big deal</mark> for corporate America.",
        "sentencePlain": "Reversing twelve years of permissive patent precedent is undoubtedly a big deal for corporate America.",
        "translation": "颠覆长达十二年的宽松专利判例，对美国企业界而言无疑是一件惊天大事。"
    },
    {
        "id": "2010-T2-09",
        "year": 2010,
        "text": "Text 2",
        "word": "a great deal (adv)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：副词修饰比较级 · 大大地/得多",
        "def": "大大地、非常",
        "sentence": "The new ruling could restrict business-method claims <mark>a great deal</mark> more severely than anticipated.",
        "sentencePlain": "The new ruling could restrict business-method claims a great deal more severely than anticipated.",
        "translation": "这项新裁决对商业方法专利权利要求的限制可能会比预期的要严格得多（副词用法）。"
    },
    {
        "id": "2010-T2-10",
        "year": 2010,
        "text": "Text 2",
        "word": "curb",
        "category": "核心词汇",
        "noteTag": "★ 考研高频核心动词 · 抑制遏制",
        "def": "遏制、抑制、控制",
        "sentence": "Regulators must intervene to <mark>curb</mark> rampant abuses by predatory patent-holding entities.",
        "sentencePlain": "Regulators must intervene to curb rampant abuses by predatory patent-holding entities.",
        "translation": "监管机构必须介入，以遏制掠夺性专利持有机构猖獗的滥用行为。"
    },
    {
        "id": "2010-T2-11",
        "year": 2010,
        "text": "Text 2",
        "word": "pooling",
        "category": "核心词汇",
        "noteTag": "★ 经济法律术语 · 专利联营合集 (patent pooling)",
        "def": "联合、集中、合并资源",
        "sentence": "Cross-industry patent <mark>pooling</mark> agreements were deployed defensively to ward off speculative lawsuits.",
        "sentencePlain": "Cross-industry patent pooling agreements were deployed defensively to ward off speculative lawsuits.",
        "translation": "跨行业的专利联合共享协议被防御性地部署，以抵御投机性的诉讼。"
    },
    {
        "id": "2010-T2-12",
        "year": 2010,
        "text": "Text 2",
        "word": "explosion",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 数量激增爆发 (非爆炸)",
        "def": "激增、爆发",
        "sentence": "The mid-1990s witnessed an unprecedented <mark>explosion</mark> of dubious internet business filings.",
        "sentencePlain": "The mid-1990s witnessed an unprecedented explosion of dubious internet business filings.",
        "translation": "20世纪90年代中期见证了可疑的互联网商业专利申请数量的前所未有的激增。"
    },
    {
        "id": "2010-T2-13",
        "year": 2010,
        "text": "Text 2",
        "word": "filing (n)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：明确为名词 · 申请案/备案文件",
        "def": "申请案、备案文件",
        "sentence": "The patent office was completely overwhelmed by the tsunami of speculative software <mark>filings</mark>.",
        "sentencePlain": "The patent office was completely overwhelmed by the tsunami of speculative software filings.",
        "translation": "专利局彻底被投机性软件专利申请文件（filings）的狂潮给淹没了。"
    },
    {
        "id": "2010-T2-14",
        "year": 2010,
        "text": "Text 2",
        "word": "emerging (adj)",
        "category": "核心词汇",
        "noteTag": "★ 核心考点：明确为形容词 · 新兴的",
        "def": "新兴的、初露头角的",
        "sentence": "Broad patents can prematurely stifle innovation across rapidly <mark>emerging</mark> technological sectors.",
        "sentencePlain": "Broad patents can prematurely stifle innovation across rapidly emerging technological sectors.",
        "translation": "宽泛的专利可能会在迅速新兴的技术领域中过早扼杀创新。"
    },
    {
        "id": "2010-T2-15",
        "year": 2010,
        "text": "Text 2",
        "word": "conduct a broad review",
        "category": "固定短语",
        "noteTag": "★ 学术司法正式搭配 · 全面审查",
        "def": "进行广泛审查/全面评估",
        "sentence": "The judges decided to <mark>conduct a broad review</mark> of the legal standards governing process patents.",
        "sentencePlain": "The judges decided to conduct a broad review of the legal standards governing process patents.",
        "translation": "法官们决定对管理流程专利的法律标准进行一次全面广泛的审查。"
    },
    {
        "id": "2010-T2-16",
        "year": 2010,
        "text": "Text 2",
        "word": "if only",
        "category": "句型语法",
        "noteTag": "★ 考研经典连词短语 · 哪怕仅仅是为了",
        "def": "哪怕仅仅是为了；要是……多好",
        "sentence": "The court sought to clarify the boundaries, <mark>if only</mark> to reduce ruinous litigation expenditures.",
        "sentencePlain": "The court sought to clarify the boundaries, if only to reduce ruinous litigation expenditures.",
        "translation": "法院试图厘清权利边界，哪怕仅仅是为了减少毁损性的诉讼开支。"
    },
    {
        "id": "2010-T2-17",
        "year": 2010,
        "text": "Text 2",
        "word": "take out",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 办理取得 (take out a patent)",
        "def": "办理、取得",
        "sentence": "Financial brokers rushed to <mark>take out</mark> patents on basic hedging and transaction methods.",
        "sentencePlain": "Financial brokers rushed to take out patents on basic hedging and transaction methods.",
        "translation": "金融经纪人争先恐后地为基础的套期保值与交易方法申请办理专利。"
    },
    {
        "id": "2010-T2-18",
        "year": 2010,
        "text": "Text 2",
        "word": "even as",
        "category": "句型语法",
        "noteTag": "★ 伴随转折连词 · 正当……之时",
        "def": "正当……之际、恰在……之时",
        "sentence": "Patent applications soared, <mark>even as</mark> leading legal scholars questioned their constitutional validity.",
        "sentencePlain": "Patent applications soared, even as leading legal scholars questioned their constitutional validity.",
        "translation": "专利申请量一路飙升，正当此时（even as）顶尖法学学者对这些专利的宪法合规性提出了质疑。"
    },
    {
        "id": "2010-T2-19",
        "year": 2010,
        "text": "Text 2",
        "word": "hedge",
        "category": "熟词生义",
        "noteTag": "★ 金融核心术语 · 对冲避险 (非树篱)",
        "def": "套期保值、防范风险；树篱",
        "sentence": "Bernard Bilski sought to patent a generic mathematical method to <mark>hedge</mark> energy price risks.",
        "sentencePlain": "Bernard Bilski sought to patent a generic mathematical method to hedge energy price risks.",
        "translation": "伯纳德·比尔斯基试图为一种防范（对冲）能源价格风险的通用数学方法申请专利。"
    },
    {
        "id": "2010-T2-20",
        "year": 2010,
        "text": "Text 2",
        "word": "in the wake of",
        "category": "固定短语",
        "noteTag": "★ 考研超高频短语 · 紧随……之后",
        "def": "紧随……而来、作为……的结果",
        "sentence": "<mark>In the wake of</mark> financial deregulation, patent disputes proliferated across Wall Street.",
        "sentencePlain": "In the wake of financial deregulation, patent disputes proliferated across Wall Street.",
        "translation": "紧随金融放松管制之后，专利纠纷在华尔街遍地蔓延。"
    },
    {
        "id": "2010-T2-21",
        "year": 2010,
        "text": "Text 2",
        "word": "signal (v/n)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：兼具动词与名词 · 发出信号表明",
        "def": "发出信号、表明；信号",
        "sentence": "The judges' aggressive questioning seemed to <mark>signal</mark> a major tightening of eligibility criteria.",
        "sentencePlain": "The judges' aggressive questioning seemed to signal a major tightening of eligibility criteria.",
        "translation": "法官们咄咄逼人的质询似乎预示（发出信号表明）准入标准的重大收紧。"
    },
    {
        "id": "2010-T2-22",
        "year": 2010,
        "text": "Text 2",
        "word": "uphold/upheld",
        "category": "核心词汇",
        "noteTag": "★ 司法审判核心词 · 维持原判 (原形/过去式)",
        "def": "维持 原判、支持、维护",
        "sentence": "The appeals bench <mark>upheld</mark> the patent rejection, arguing the formula lacked physical transformation.",
        "sentencePlain": "The appeals bench upheld the patent rejection, arguing the formula lacked physical transformation.",
        "translation": "上诉法庭维持了驳回专利的裁定，认为该公式缺乏物理形态的转化。"
    },
    {
        "id": "2010-T2-23",
        "year": 2010,
        "text": "Text 2",
        "word": "attorney",
        "category": "核心词汇",
        "noteTag": "★ 核心法律词汇 · 代理律师",
        "def": "律师、法定代理人",
        "sentence": "Corporate <mark>attorneys</mark> warned clients that hundreds of thousands of existing patents might become invalid.",
        "sentencePlain": "Corporate attorneys warned clients that hundreds of thousands of existing patents might become invalid.",
        "translation": "企业律师告诫客户，数十万项现有专利可能会变成无效。"
    },
    {
        "id": "2010-T2-24",
        "year": 2010,
        "text": "Text 2",
        "word": "looming",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 迫近威胁",
        "def": "迫近的、赫然隐现的",
        "sentence": "The <mark>looming</mark> Supreme Court ruling cast a long shadow of uncertainty over tech investments.",
        "sentencePlain": "The looming Supreme Court ruling cast a long shadow of uncertainty over tech investments.",
        "translation": "迫在眉睫的最高法院裁决给科技投资领域投下了一层不确定的阴影。"
    },
    {
        "id": "2010-T2-25",
        "year": 2010,
        "text": "Text 2",
        "word": "prevailing",
        "category": "核心词汇",
        "noteTag": "★ 核心形容词 · 盛行占主导的",
        "def": "盛行的、占主导地位的",
        "sentence": "The <mark>prevailing</mark> legal doctrine that anything under the sun made by man is patentable is now crumbling.",
        "sentencePlain": "The prevailing legal doctrine that anything under the sun made by man is patentable is now crumbling.",
        "translation": "那种认为“阳光下人造的任何东西皆可获得专利”的盛行法律学说如今正在土崩瓦解。"
    }
]

cards_2010_t3 = [
    {
        "id": "2010-T3-01",
        "year": 2010,
        "text": "Text 3",
        "word": "drive",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 动词驱动推动 (非驾驶)",
        "def": "驱动、推动；驾驶",
        "sentence": "Popular mythology insists that viral cultural trends are <mark>driven</mark> by influential charismatic trendsetters.",
        "sentencePlain": "Popular mythology insists that viral cultural trends are driven by influential charismatic trendsetters.",
        "translation": "大众神话坚称，病毒式文化潮流是由具有影响力的魅力引潮者所驱动的。"
    },
    {
        "id": "2010-T3-02",
        "year": 2010,
        "text": "Text 3",
        "word": "minority",
        "category": "熟词生义",
        "noteTag": "★ 名词用法 · 极少数人 (a tiny minority)",
        "def": "少数、极少数人",
        "sentence": "Malcolm Gladwell claimed that a tiny <mark>minority</mark> of special individuals dictate what the rest of us buy.",
        "sentencePlain": "Malcolm Gladwell claimed that a tiny minority of special individuals dictate what the rest of us buy.",
        "translation": "马尔科姆·格拉德威尔声称，极少数特殊个体决定了我们其余人购买什么。"
    },
    {
        "id": "2010-T3-03",
        "year": 2010,
        "text": "Text 3",
        "word": "unusually",
        "category": "核心词汇",
        "noteTag": "★ 程度副词 · 异乎寻常特别地",
        "def": "异乎寻常地、特别地",
        "sentence": "These supposed mavens are depicted as <mark>unusually</mark> persuasive and knowledgeable.",
        "sentencePlain": "These supposed mavens are depicted as unusually persuasive and knowledgeable.",
        "translation": "这些所谓的行家被描绘成具有非同寻常的说服力与知识渊博。"
    },
    {
        "id": "2010-T3-04",
        "year": 2010,
        "text": "Text 3",
        "word": "informed",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 见多识广/消息灵通 (well-informed)",
        "def": "消息灵通的、见多识广的",
        "sentence": "Marketers spent millions pursuing consumers who appeared uniquely <mark>informed</mark> about upcoming trends.",
        "sentencePlain": "Marketers spent millions pursuing consumers who appeared uniquely informed about upcoming trends.",
        "translation": "营销人员斥资数百万去追逐那些对未来潮流显得格外消息灵通的消费者。"
    },
    {
        "id": "2010-T3-05",
        "year": 2010,
        "text": "Text 3",
        "word": "intuitively",
        "category": "核心词汇",
        "noteTag": "★ 认知副词 · 凭直觉地",
        "def": "直觉地、凭借直觉地",
        "sentence": "The influencer theory feels <mark>intuitively</mark> compelling because it mirrors traditional notions of leadership.",
        "sentencePlain": "The influencer theory feels intuitively compelling because it mirrors traditional notions of leadership.",
        "translation": "影响者理论在直觉上令人信服，因为它契合了传统的领导力观念。"
    },
    {
        "id": "2010-T3-06",
        "year": 2010,
        "text": "Text 3",
        "word": "compelling",
        "category": "核心词汇",
        "noteTag": "★ 核心论证形容词 · 令人信服的",
        "def": "令人信服的、引人入胜的",
        "sentence": "A tidy narrative about special influencers sounds far more <mark>compelling</mark> than complex network dynamics.",
        "sentencePlain": "A tidy narrative about special influencers sounds far more compelling than complex network dynamics.",
        "translation": "一个关于特殊影响者的简单干练的故事，听起来远比复杂的网络机制更具说服力。"
    },
    {
        "id": "2010-T3-07",
        "year": 2010,
        "text": "Text 3",
        "word": "supposed",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 所谓的 (含质疑色彩)",
        "def": "所谓的、假定的",
        "sentence": "Duncan Watts tested these <mark>supposed</mark> influencers with sophisticated computer simulation models.",
        "sentencePlain": "Duncan Watts tested these supposed influencers with sophisticated computer simulation models.",
        "translation": "邓肯·瓦茨运用精密的计算机仿真模型对这些所谓的“影响者”进行了检验。"
    },
    {
        "id": "2010-T3-08",
        "year": 2010,
        "text": "Text 3",
        "word": "marketer",
        "category": "核心词汇",
        "noteTag": "★ 商业核心名词 · 市场营销者",
        "def": "营销人员、市场商",
        "sentence": "Gullible <mark>marketers</mark> embraced the influencer model without demanding empirical verification.",
        "sentencePlain": "Gullible marketers embraced the influencer model without demanding empirical verification.",
        "translation": "轻信的市场营销人员欣然接纳了影响者模型，却未曾要求经验实证。"
    },
    {
        "id": "2010-T3-09",
        "year": 2010,
        "text": "Text 3",
        "word": "select",
        "category": "熟词生义",
        "noteTag": "★ 动词与形容词 · 挑选/精选",
        "def": "挑选；精选的、优选的",
        "sentence": "Ad agencies sought to <mark>select</mark> key nodes in social graphs to seed advertising campaigns.",
        "sentencePlain": "Ad agencies sought to select key nodes in social graphs to seed advertising campaigns.",
        "translation": "广告代理商试图挑选出社交图谱中的关键节点，用以播种广告营销活动。"
    },
    {
        "id": "2010-T3-10",
        "year": 2010,
        "text": "Text 3",
        "word": "cursory",
        "category": "核心词汇",
        "noteTag": "★ 考研核心态度词 · 敷衍草率粗略",
        "def": "匆忙的、草率的、粗略的",
        "sentence": "Even a <mark>cursory</mark> examination of historical epidemics reveals that contagions depend on overall susceptibility.",
        "sentencePlain": "Even a cursory examination of historical epidemics reveals that contagions depend on overall susceptibility.",
        "translation": "即便只是对历史流行病进行粗略草率的审视，也会发现传染在很大程度上取决于整体易感性。"
    },
    {
        "id": "2010-T3-11",
        "year": 2010,
        "text": "Text 3",
        "word": "anecdotal",
        "category": "核心词汇",
        "noteTag": "★ 核心学术反义词 · 基于轶事传闻 (非实证)",
        "def": "轶事的、基于传闻的",
        "sentence": "Gladwell's conclusions rested primarily on engaging but <mark>anecdotal</mark> storytelling.",
        "sentencePlain": "Gladwell's conclusions rested primarily on engaging but anecdotal storytelling.",
        "translation": "格拉德威尔的结论主要建立在引人入胜但纯属道听途说（基于轶事）的讲述之上。"
    },
    {
        "id": "2010-T3-12",
        "year": 2010,
        "text": "Text 3",
        "word": "fit",
        "category": "熟词生义",
        "noteTag": "★ 动词用法 · 契合符合模型",
        "def": "符合、契合；适合",
        "sentence": "Real-world cascading data did not <mark>fit</mark> the tidy predictions of the influencer doctrine.",
        "sentencePlain": "Real-world cascading data did not fit the tidy predictions of the influencer doctrine.",
        "translation": "现实世界的级联传播数据并不契合影响者学说那简单整齐的预测。"
    },
    {
        "id": "2010-T3-13",
        "year": 2010,
        "text": "Text 3",
        "word": "stem from",
        "category": "固定短语",
        "noteTag": "★ 考研超高频因果短语 · 起源于",
        "def": "起源于、由……产生",
        "sentence": "A social epidemic does not <mark>stem from</mark> the initiator, but from the network's readiness to propagate it.",
        "sentencePlain": "A social epidemic does not stem from the initiator, but from the network's readiness to propagate it.",
        "translation": "一场社会潮流并不起源于发起者，而是起源于网络传播该潮流的就绪状态。"
    },
    {
        "id": "2010-T3-14",
        "year": 2010,
        "text": "Text 3",
        "word": "far less",
        "category": "固定短语",
        "noteTag": "★ 程度副词短语 · 远少于/远不及",
        "def": "远少于、远不及",
        "sentence": "The personal charisma of the first speaker matters <mark>far less</mark> than the general crowd sentiment.",
        "sentencePlain": "The personal charisma of the first speaker matters far less than the general crowd sentiment.",
        "translation": "第一位发言者的个人魅力，远不如大众群体的普遍情绪来得重要。"
    },
    {
        "id": "2010-T3-15",
        "year": 2010,
        "text": "Text 3",
        "word": "a function of",
        "category": "固定短语",
        "noteTag": "★ 核心考点：学术搭配 · 是……的产物/函数",
        "def": "由……决定的结果、是……的函数",
        "sentence": "The success of an idea is largely <mark>a function of</mark> the structural connectivity between ordinary people.",
        "sentencePlain": "The success of an idea is largely a function of the structural connectivity between ordinary people.",
        "translation": "一种观念的成功，在很大程度上是普通人之间结构连接状态的函数（由其决定的产物）。"
    },
    {
        "id": "2010-T3-16",
        "year": 2010,
        "text": "Text 3",
        "word": "outsize",
        "category": "核心词汇",
        "noteTag": "★ 形容词 · 不成比例的庞大",
        "def": "特大的、过大的、不成比例的",
        "sentence": "Popular culture mistakenly attributes an <mark>outsize</mark> role to high-profile celebrities.",
        "sentencePlain": "Popular culture mistakenly attributes an outsize role to high-profile celebrities.",
        "translation": "大众文化错误地将不成比例的巨大作用归结于备受瞩目的各路明星。"
    },
    {
        "id": "2010-T3-17",
        "year": 2010,
        "text": "Text 3",
        "word": "presence",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 存在感/声势影响",
        "def": "存在、风采、声势影响",
        "sentence": "Having an overwhelming digital <mark>presence</mark> does not guarantee that your followers will mirror your choices.",
        "sentencePlain": "Having an overwhelming digital presence does not guarantee that your followers will mirror your choices.",
        "translation": "拥有巨大的数字平台存在感，并不能确保你的追随者会仿效你的选择。"
    },
    {
        "id": "2010-T3-18",
        "year": 2010,
        "text": "Text 3",
        "word": "precisely (adv)",
        "category": "核心词汇",
        "noteTag": "★ 核心考点：明确为副词修饰强调 · 恰恰正是",
        "def": "恰恰、精确地",
        "sentence": "It is <mark>precisely</mark> because human networks are complex that simple top-down marketing fails.",
        "sentencePlain": "It is precisely because human networks are complex that simple top-down marketing fails.",
        "translation": "恰恰（副词修饰）正是因为人类社交网络错综复杂，自上而下的简单营销才会败下阵来。"
    },
    {
        "id": "2010-T3-19",
        "year": 2010,
        "text": "Text 3",
        "word": "in turn",
        "category": "固定短语",
        "noteTag": "★ 逻辑推进短语 · 继而/反过来",
        "def": "继而、转而；反过来",
        "sentence": "Each infected person influences their own neighbors, who <mark>in turn</mark> ignite wider circles.",
        "sentencePlain": "Each infected person influences their own neighbors, who in turn ignite wider circles.",
        "translation": "每一个被感染的人都会影响其近邻，而近邻们继而（反过来）又点燃了更广泛的圈子。"
    },
    {
        "id": "2010-T3-20",
        "year": 2010,
        "text": "Text 3",
        "word": "have (little) to do",
        "category": "固定短语",
        "noteTag": "★ 核心考点：关联结构 · 与……几乎毫无关系",
        "def": "与……几乎无关",
        "sentence": "The ultimate scale of a cascade often <mark>has little to do</mark> with who sparked the initial flame.",
        "sentencePlain": "The ultimate scale of a cascade often has little to do with who sparked the initial flame.",
        "translation": "级联反应的最终规模，往往与究竟是谁点燃了第一把火几乎毫无干系。"
    },
    {
        "id": "2010-T3-21",
        "year": 2010,
        "text": "Text 3",
        "word": "network",
        "category": "核心词汇",
        "noteTag": "★ 系统科学核心词 · 社交网络拓扑",
        "def": "网络、互联体系",
        "sentence": "The architecture of the social <mark>network</mark> dictates whether a rumor extinguishes or goes global.",
        "sentencePlain": "The architecture of the social network dictates whether a rumor extinguishes or goes global.",
        "translation": "社交网络的内在拓扑架构决定了一条谣言是自行湮灭还是风靡全球。"
    },
    {
        "id": "2010-T3-22",
        "year": 2010,
        "text": "Text 3",
        "word": "cascade",
        "category": "熟词生义",
        "noteTag": "★ 考研高阶社科难词 · 级联反应/连锁倾泻",
        "def": "级联反应、连串倾泻",
        "sentence": "An information <mark>cascade</mark> requires a critical density of easily influenced individuals.",
        "sentencePlain": "An information cascade requires a critical density of easily influenced individuals.",
        "translation": "一场信息级联反应需要容易受到影响的个体达到一个临界密度。"
    },
    {
        "id": "2010-T3-23",
        "year": 2010,
        "text": "Text 3",
        "word": "serve as",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 充当/作为",
        "def": "作为、充当",
        "sentence": "Ordinary interconnected citizens <mark>serve as</mark> the true combustible forest for viral ideas.",
        "sentencePlain": "Ordinary interconnected citizens serve as the true combustible forest for viral ideas.",
        "translation": "互相连接的普通公民，才充当了病毒式观念赖以蔓延的真正的易燃森林。"
    },
    {
        "id": "2010-T3-24",
        "year": 2010,
        "text": "Text 3",
        "word": "seem to (暗含否定)",
        "category": "句型语法",
        "noteTag": "★ 核心考点：seem to 表面看似如此/暗含否定潜台词",
        "def": "表面上看似乎……",
        "sentence": "Trendsetters <mark>seem to</mark> dictate fads only because they catch and reflect existing social currents earlier.",
        "sentencePlain": "Trendsetters seem to dictate fads only because they catch and reflect existing social currents earlier.",
        "translation": "潮流引领者表面上似乎（暗含否定）在支配着时尚，仅仅是因为他们更早捕捉并反映了既有的社会潮流。"
    },
    {
        "id": "2010-T3-25",
        "year": 2010,
        "text": "Text 3",
        "word": "readiness",
        "category": "核心词汇",
        "noteTag": "★ 构词：ready + ness · 就绪状态",
        "def": "就绪状态、乐意、敏捷",
        "sentence": "Without a collective <mark>readiness</mark> to embrace change, the most charismatic sales pitch falls on deaf ears.",
        "sentencePlain": "Without a collective readiness to embrace change, the most charismatic sales pitch falls on deaf ears.",
        "translation": "如果缺乏一种欣然拥抱变革的集体就绪状态，再富魅力的推销辞令也会被当成耳旁风。"
    },
    {
        "id": "2010-T3-26",
        "year": 2010,
        "text": "Text 3",
        "word": "suggest (暗含话中有话)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：suggest 暗含深意/潜台词",
        "def": "暗示、话中有话",
        "sentence": "The data <mark>suggest</mark> that marketers waste enormous fortunes pursuing mythical influencers.",
        "sentencePlain": "The data suggest that marketers waste enormous fortunes pursuing mythical influencers.",
        "translation": "统计数据暗示（暗含话中有话）：营销人员在追逐神话般的“超级影响者”上浪费了惊人的巨额财富。"
    }
]

cards_2010_t4 = [
    {
        "id": "2010-T4-01",
        "year": 2010,
        "text": "Text 4",
        "word": "behind the scenes",
        "category": "固定短语",
        "noteTag": "★ 介词短语 · 幕后操纵",
        "def": "在幕后、秘密地",
        "sentence": "Fierce political maneuvering occurred <mark>behind the scenes</mark> to weaken mark-to-market accounting rules.",
        "sentencePlain": "Fierce political maneuvering occurred behind the scenes to weaken mark-to-market accounting rules.",
        "translation": "为了削弱“按市值计价”的会计规则，幕后发生着激烈的政治博弈操弄。"
    },
    {
        "id": "2010-T4-02",
        "year": 2010,
        "text": "Text 4",
        "word": "take aim at (瞄准/将矛头对准)",
        "category": "固定短语",
        "noteTag": "★ 核心考点：take aim at 将矛头对准",
        "def": "将矛头对准、瞄准",
        "sentence": "Frustrated bank executives <mark>took aim at</mark> standard-setters, blaming accounting rules for the financial crisis.",
        "sentencePlain": "Frustrated bank executives took aim at standard-setters, blaming accounting rules for the financial crisis.",
        "translation": "恼羞成怒的银行高管将矛头对准了（take aim at）准则制定者，将金融危机的责任推给会计规则。"
    },
    {
        "id": "2010-T4-03",
        "year": 2010,
        "text": "Text 4",
        "word": "setter",
        "category": "熟词生义",
        "noteTag": "★ 构词核心词 · 准则制定者 (standard-setter)",
        "def": "制定者",
        "sentence": "Independent standard-<mark>setters</mark> like the FASB were created to protect investors from cooked corporate books.",
        "sentencePlain": "Independent standard-setters like the FASB were created to protect investors from cooked corporate books.",
        "translation": "像财务会计准则委员会这样独立的准则制定机构，其设立初衷就是为了保护投资者免受虚假企业账目的蒙蔽。"
    },
    {
        "id": "2010-T4-04",
        "year": 2010,
        "text": "Text 4",
        "word": "enormous",
        "category": "核心词汇",
        "noteTag": "★ 程度形容词 · 庞大巨额的",
        "def": "庞大的、巨大的",
        "sentence": "Banks faced <mark>enormous</mark> balance-sheet write-downs on mortgage-backed securities.",
        "sentencePlain": "Banks faced enormous balance-sheet write-downs on mortgage-backed securities.",
        "translation": "银行在房贷抵押证券上承受着数额巨大的资产负债表资产减记。"
    },
    {
        "id": "2010-T4-05",
        "year": 2010,
        "text": "Text 4",
        "word": "fetch",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 卖出……价格 (非取来)",
        "def": "售得、卖出……价钱",
        "sentence": "Illiquid mortgage assets would <mark>fetch</mark> only fire-sale pennies on the dollar in frozen markets.",
        "sentencePlain": "Illiquid mortgage assets would fetch only fire-sale pennies on the dollar in frozen markets.",
        "translation": "缺乏流动性的抵押贷款资产在被冻结的市场中只能卖出清仓跳楼般的几分钱价格。"
    },
    {
        "id": "2010-T4-06",
        "year": 2010,
        "text": "Text 4",
        "word": "third party",
        "category": "固定短语",
        "noteTag": "★ 法律金融短语 · 第三方/独立第三方",
        "def": "第三方、无利害关系人",
        "sentence": "Valuations calculated by an impartial <mark>third party</mark> were deemed vital for market transparency.",
        "sentencePlain": "Valuations calculated by an impartial third party were deemed vital for market transparency.",
        "translation": "由公正的第三方计算得出的估值，被认为对维持市场透明度至关重要。"
    },
    {
        "id": "2010-T4-07",
        "year": 2010,
        "text": "Text 4",
        "word": "lobbying",
        "category": "核心词汇",
        "noteTag": "★ 政治商业核心名词 · 游说施压",
        "def": "游说、游说活动",
        "sentence": "Aggressive political <mark>lobbying</mark> by commercial lenders pressured Congress to intervene in technical rules.",
        "sentencePlain": "Aggressive political lobbying by commercial lenders pressured Congress to intervene in technical rules.",
        "translation": "商业银行激进的政治游说向国会施加压力，要求其干涉专业技术规则。"
    },
    {
        "id": "2010-T4-08",
        "year": 2010,
        "text": "Text 4",
        "word": "functioning",
        "category": "核心词汇",
        "noteTag": "★ 系统名词 · 正常运转机制",
        "def": "运转、运行功能",
        "sentence": "Transparent reporting is vital to the healthy <mark>functioning</mark> of capitalist capital markets.",
        "sentencePlain": "Transparent reporting is vital to the healthy functioning of capitalist capital markets.",
        "translation": "透明的财务报告对于资本主义资本市场的健康运转至关重要。"
    },
    {
        "id": "2010-T4-09",
        "year": 2010,
        "text": "Text 4",
        "word": "compromise(d) (损害)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：熟词僻义 · 损害/危及 (非妥协)",
        "def": "妥协；损害、危及",
        "sentence": "Regulators feared that yielding to bankers would seriously <mark>compromise</mark> the integrity of financial statements.",
        "sentencePlain": "Regulators feared that yielding to bankers would seriously compromise the integrity of financial statements.",
        "translation": "监管机构担忧向银行家妥协退让会严重损害（危及）财务报表的真实完整性。"
    },
    {
        "id": "2010-T4-10",
        "year": 2010,
        "text": "Text 4",
        "word": "toxic",
        "category": "熟词生义",
        "noteTag": "★ 金融核心隐喻 · toxic assets 有毒不良资产",
        "def": "有毒的；不良的、有毒资产",
        "sentence": "Lenders held vast portfolios of <mark>toxic</mark> debt that no prudent investor would purchase.",
        "sentencePlain": "Lenders held vast portfolios of toxic debt that no prudent investor would purchase.",
        "translation": "放贷机构手握大量有毒（不良）债务资产组合，没有任何谨慎的投资者愿意接盘。"
    },
    {
        "id": "2010-T4-11",
        "year": 2010,
        "text": "Text 4",
        "word": "bruising (激烈的)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：熟词僻义 · 激烈残酷的争端",
        "def": "激烈的、伤痕累累的",
        "sentence": "After a <mark>bruising</mark> encounter with congressional committees, standard-setters were forced to back down.",
        "sentencePlain": "After a bruising encounter with congressional committees, standard-setters were forced to back down.",
        "translation": "在与国会委员会进行了一场激烈残酷的（bruising）交锋之后，会计准则制定者被迫做出了退让。"
    },
    {
        "id": "2010-T4-12",
        "year": 2010,
        "text": "Text 4",
        "word": "cry out",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 大声疾呼抗议",
        "def": "大声疾呼、呼喊要求",
        "sentence": "Banks <mark>cried out</mark> against accounting rules that they claimed worsened the liquidity crunch.",
        "sentencePlain": "Banks cried out against accounting rules that they claimed worsened the liquidity crunch.",
        "translation": "银行针对会计准则大声疾呼抗议，声称该准则加剧了流动性危机。"
    },
    {
        "id": "2010-T4-13",
        "year": 2010,
        "text": "Text 4",
        "word": "question (v)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：明确为动词 · 质疑怀疑",
        "def": "质疑、怀疑",
        "sentence": "Independent analysts began to <mark>question</mark> the true solvency of Wall Street's largest institutions.",
        "sentencePlain": "Independent analysts began to question the true solvency of Wall Street's largest institutions.",
        "translation": "独立分析师们开始质疑华尔街最大金融机构的真实偿付能力。"
    },
    {
        "id": "2010-T4-14",
        "year": 2010,
        "text": "Text 4",
        "word": "motive",
        "category": "核心词汇",
        "noteTag": "★ 核心名词 · 动机目的",
        "def": "动机、目的",
        "sentence": "The real <mark>motive</mark> of the bankers was to conceal deep balance-sheet losses from public scrutiny.",
        "sentencePlain": "The real motive of the bankers was to conceal deep balance-sheet losses from public scrutiny.",
        "translation": "银行家的真实动机是为了掩盖资产负债表上的巨额亏损，避开公众的审视。"
    },
    {
        "id": "2010-T4-15",
        "year": 2010,
        "text": "Text 4",
        "word": "fold (屈服)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：熟词僻义 · 屈服退让/放弃坚持",
        "def": "折叠；屈服、放弃",
        "sentence": "Under intense political arm-twisting, the accounting board finally <mark>folded</mark> and relaxed its rules.",
        "sentencePlain": "Under intense political arm-twisting, the accounting board finally folded and relaxed its rules.",
        "translation": "在强大的政治施压和生拉硬拽之下，会计准则委员会最终屈服（放弃坚持）并放宽了规则。"
    },
    {
        "id": "2010-T4-16",
        "year": 2010,
        "text": "Text 4",
        "word": "rose (rise过去式)",
        "category": "核心词汇",
        "noteTag": "★ 核心考点：不规则动词 rise-rose · 上涨",
        "def": "上涨、上升",
        "sentence": "Financial stocks <mark>rose</mark> sharply the day after mark-to-market rules were officially diluted.",
        "sentencePlain": "Financial stocks rose sharply the day after mark-to-market rules were officially diluted.",
        "translation": "在市值计价规则被正式稀释的次日，金融类股票大幅上涨。"
    },
    {
        "id": "2010-T4-17",
        "year": 2010,
        "text": "Text 4",
        "word": "could yet do sth",
        "category": "句型语法",
        "noteTag": "★ 考研经典虚拟推测 · 迟早还会/仍有可能",
        "def": "迟早还会……、仍有可能做某事",
        "sentence": "Compromising independent standards <mark>could yet come</mark> back to haunt the global economic recovery.",
        "sentencePlain": "Compromising independent standards could yet come back to haunt the global economic recovery.",
        "translation": "牺牲独立准则的做法，迟早还会（仍有可能）回过头来困扰全球经济的复苏。"
    },
    {
        "id": "2010-T4-18",
        "year": 2010,
        "text": "Text 4",
        "word": "overstate",
        "category": "核心词汇",
        "noteTag": "★ 构词：over + state · 夸大虚报",
        "def": "夸大、过分渲染",
        "sentence": "Banks were permitted to <mark>overstate</mark> the worth of defaulted mortgages using internal mathematical models.",
        "sentencePlain": "Banks were permitted to overstate the worth of defaulted mortgages using internal mathematical models.",
        "translation": "银行被允许利用内部数学模型夸大违约抵押贷款的账面价值。"
    },
    {
        "id": "2010-T4-19",
        "year": 2010,
        "text": "Text 4",
        "word": "extent",
        "category": "核心词汇",
        "noteTag": "★ 核心抽象名词 · 范围程度",
        "def": "范围、程度、广度",
        "sentence": "The true <mark>extent</mark> of the lenders' bad debts was conveniently hidden from prospective investors.",
        "sentencePlain": "The true extent of the lenders' bad debts was conveniently hidden from prospective investors.",
        "translation": "放贷机构坏账的真实程度被轻而易举地向潜在投资者隐瞒了起来。"
    },
    {
        "id": "2010-T4-20",
        "year": 2010,
        "text": "Text 4",
        "word": "book (账面的)",
        "category": "熟词生义",
        "noteTag": "★ 核心考点：熟词僻义 · 账面价值 (book value)",
        "def": "账面上的；书本",
        "sentence": "Relaxed rules enabled lenders to report optimistic <mark>book</mark> values that bore no relation to actual market prices.",
        "sentencePlain": "Relaxed rules enabled lenders to report optimistic book values that bore no relation to actual market prices.",
        "translation": "放宽的规则使得放贷机构能够申报乐观的账面（book）价值，而这一价值与实际市场价格毫无关联。"
    },
    {
        "id": "2010-T4-21",
        "year": 2010,
        "text": "Text 4",
        "word": "interests",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 利益集团 (非兴趣/利息)",
        "def": "利益、利益集团；利息",
        "sentence": "Powerful financial <mark>interests</mark> cynically used economic panic to subvert long-standing regulatory safeguards.",
        "sentencePlain": "Powerful financial interests cynically used economic panic to subvert long-standing regulatory safeguards.",
        "translation": "强大的金融利益集团利用经济恐慌，居心叵测地颠覆了长久以来的监管防护机制。"
    },
    {
        "id": "2010-T4-22",
        "year": 2010,
        "text": "Text 4",
        "word": "give in to",
        "category": "固定短语",
        "noteTag": "★ 动词短语 · 向……妥协让步",
        "def": "向……妥协、让步、屈服",
        "sentence": "When standard-setters <mark>give in to</mark> political pressure, investor confidence is mortally wounded.",
        "sentencePlain": "When standard-setters give in to political pressure, investor confidence is mortally wounded.",
        "translation": "当准则制定者向政治压力妥协屈服时，投资者的信心便遭受了致命的打击。"
    },
    {
        "id": "2010-T4-23",
        "year": 2010,
        "text": "Text 4",
        "word": "invite",
        "category": "熟词生义",
        "noteTag": "★ 熟词僻义 · 招致招引恶果 (非邀请)",
        "def": "招致、招引；邀请",
        "sentence": "Obscuring bad debts will only <mark>invite</mark> future banking panics and deeper financial contagion.",
        "sentencePlain": "Obscuring bad debts will only invite future banking panics and deeper financial contagion.",
        "translation": "掩盖坏账只会招致未来的银行恐慌和更为深重的金融传染。"
    },
    {
        "id": "2010-T4-24",
        "year": 2010,
        "text": "Text 4",
        "word": "combative",
        "category": "核心词汇",
        "noteTag": "★ 构词：combat + ive · 充满火药味好斗的",
        "def": "好战的、好斗的、充满火药味的",
        "sentence": "Lawmakers took a <mark>combative</mark> stance against standard-setters, threatening to abolish the FASB entirely.",
        "sentencePlain": "Lawmakers took a combative stance against standard-setters, threatening to abolish the FASB entirely.",
        "translation": "议员们对准则制定者采取了一种充满火药味的攻击性姿态，威胁要彻底废除财务会计准则委员会。"
    },
    {
        "id": "2010-T4-25",
        "year": 2010,
        "text": "Text 4",
        "word": "hostility",
        "category": "核心词汇",
        "noteTag": "★ 核心态度名词 · 公开敌意",
        "def": "敌意、敌对状态",
        "sentence": "Regulators faced open <mark>hostility</mark> on Capitol Hill for defending fair-value accounting principles.",
        "sentencePlain": "Regulators faced open hostility on Capitol Hill for defending fair-value accounting principles.",
        "translation": "监管官员因捍卫公允价值会计原则在国会山遭遇了公开的敌意。"
    },
    {
        "id": "2010-T4-26",
        "year": 2010,
        "text": "Text 4",
        "word": "have been",
        "category": "句型语法",
        "noteTag": "★ 完成时态语境 · 向来是/曾经是",
        "def": "曾经是、向来是",
        "sentence": "Mark-to-market accounting <mark>has been</mark> the cornerstone of international financial credibility for generations.",
        "sentencePlain": "Mark-to-market accounting has been the cornerstone of international financial credibility for generations.",
        "translation": "长期以来，市值计价会计向来是国际金融公信力的基石。"
    },
    {
        "id": "2010-T4-27",
        "year": 2010,
        "text": "Text 4",
        "word": "be reluctant",
        "category": "固定短语",
        "noteTag": "★ 态度考点短语 · 勉强不情愿",
        "def": "勉强的、不情愿做某事",
        "sentence": "Auditors <mark>were reluctant</mark> to sign off on fabricated balance sheets that ignored real market conditions.",
        "sentencePlain": "Auditors were reluctant to sign off on fabricated balance sheets that ignored real market conditions.",
        "translation": "审计师很不情愿在那些无视实际市场行情的虚构资产负债表上签字盖章。"
    },
    {
        "id": "2010-T4-28",
        "year": 2010,
        "text": "Text 4",
        "word": "weakening",
        "category": "核心词汇",
        "noteTag": "★ 动态抽象名词 · 规则削弱",
        "def": "削弱、变弱",
        "sentence": "The <mark>weakening</mark> of technical rules eroded global faith in American corporate reporting.",
        "sentencePlain": "The weakening of technical rules eroded global faith in American corporate reporting.",
        "translation": "专业技术规则的削弱侵蚀了全球对美国企业财报的信任。"
    },
    {
        "id": "2010-T4-29",
        "year": 2010,
        "text": "Text 4",
        "word": "misinterpret",
        "category": "核心词汇",
        "noteTag": "★ 构词：mis + interpret · 曲解误读",
        "def": "曲解、误解",
        "sentence": "Self-serving executives purposely <mark>misinterpret</mark> fair-value rules to deflect blame from poor management.",
        "sentencePlain": "Self-serving executives purposely misinterpret fair-value rules to deflect blame from poor management.",
        "translation": "自私自利的高管故意曲解公允价值规则，以推卸自身管理不善的责任。"
    },
    {
        "id": "2010-T4-30",
        "year": 2010,
        "text": "Text 4",
        "word": "indicator",
        "category": "核心词汇",
        "noteTag": "★ 核心学术名词 · 衡量指标",
        "def": "指标、指示物",
        "sentence": "Market prices remain the most reliable <mark>indicator</mark> of an asset's true economic value.",
        "sentencePlain": "Market prices remain the most reliable indicator of an asset's true economic value.",
        "translation": "市场价格依然是衡量一项资产真实经济价值最为可靠的指标。"
    },
    {
        "id": "2010-T4-31",
        "year": 2010,
        "text": "Text 4",
        "word": "peer",
        "category": "熟词生义",
        "noteTag": "★ 商业同业对比 · 同类机构 (peer institutions)",
        "def": "同业机构、同行企业",
        "sentence": "Banks feared that reporting heavy write-downs would put them at a severe disadvantage against <mark>peer</mark> institutions.",
        "sentencePlain": "Banks feared that reporting heavy write-downs would put them at a severe disadvantage against peer institutions.",
        "translation": "银行担心报告巨额资产减记会使他们在与同业机构的竞争中处于严重劣势。"
    }
]
